### DISCUSSION TITLE
Error: Request to enterprise repo failed due to tunneling socket could not be established

### DISCUSSION THREAD

**Discussion by usagibear** [actions/checkout#1012] [General]
Not sure if this is the right place to post this, but when I run actions/checkout@v3 in my workflow in my enterprise instance of GitHub on a self-hosted Windows runner, I get the following error and do not understand it:

`Error: request to https://my-enterprise-git.com/api/v3/repos/myorg/myrepo/.../... failed, reason: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND myproxy.com`

I am able to checkout with actions/checkout@v3 just fine in a simple workflow like the following:

```yml
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

Though the above would fail on the `run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."` due to syntax issues for some other reason.

What can I do about it?

Thanks!
