### DISCUSSION TITLE
Private Repository not found

### DISCUSSION THREAD

**Discussion by mpeeren** [actions/checkout#1023] [Q&A] [answered]
Hi,

I have an issue on my github actions workflow. Was working well yesterday.

Today impossible to checkout the repository at the beginning of my flow

```
name: Dev

on:
push:
branches:
- develop

jobs:
build:
runs-on: windows-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v2
    with:
      token: '${{ secrets.Dev }}'
      submodules: 'recursive'      
```

Error return is :

repository 'https://github.com/organisation/repository/' not found

The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128

I found issue saying it was on github side, but all looks ok on their side. 
https://github.com/actions/checkout/issues/254

Did I miss something?
