### DISCUSSION TITLE
cached git submodules but get a warning "fatal: not a git repository"

### DISCUSSION THREAD

**Discussion by adoyle-h** [actions/checkout#1028] [Q&A]
I use [actions/cache](https://github.com/actions/cache) to cache all git submodules. But get a warning at POST RUN actions/checkout.

<img width="943" alt="CleanShot 2022-12-02 at 18 03 59@2x" src="https://user-images.githubusercontent.com/1998490/205267800-39953ab0-3afc-4e5f-8f9a-c9ddd747da28.png">

I want to reuse the caches of submodules, so `.git/modules/test/fixture/assert` should be empty.
So how to fix these warnings?

Is there any option to skip submodules when actions/checkout run `/usr/bin/git submodule foreach`?

My workflow steps:

```yaml
    steps:
      - uses: actions/checkout@v3

      - name: Cache test/fixture
        id: cache-test-fixture
        uses: actions/cache@v3
        with:
          path: |
            test/fixture/assert
            test/fixture/bats
            test/fixture/bats-file
            test/fixture/support
          key: ${{ runner.os }}-test-fixture

      - name: Update git submodules
        if: steps.cache-test-fixture.outputs.cache-hit != 'true'
        run:
          git submodule update --init --recursive
```

.gitmodules:

```
[submodule "test/fixture/bats"]
	path = test/fixture/bats
	url = https://github.com/bats-core/bats-core.git
  shallow = true
[submodule "test/fixture/assert"]
	path = test/fixture/assert
	url = https://github.com/bats-core/bats-assert.git
  shallow = true
[submodule "test/fixture/bats-file"]
	path = test/fixture/bats-file
	url = https://github.com/bats-core/bats-file.git
  shallow = true
[submodule "test/fixture/support"]
	path = test/fixture/support
	url = https://github.com/bats-core/bats-support.git
  shallow = true
```

**Comment by vpavlin** [comment]
Also hitting this - is it not possible to cache submodules?

**Comment by oerp-odoo** [comment]
I am using it this way:

```yaml
      - name: Checkout myrepo
        uses: actions/checkout@v3
      - name: Cache Submodules
        id: cache-submodule
        uses: actions/cache@v3
        with:
          path: |
            my/sub1
            my/sub2
          key: ${{ runner.os }}-submodules
      - name: Update git submodules
        if: steps.cache-submodule.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          submodules: recursive
```
I get same warning, but it looks like caching still works
