### DISCUSSION TITLE
How to get the latest commit on concurrency workflows?

### DISCUSSION THREAD

**Discussion by JohnTitor** [actions/checkout#1125] [Q&A]
`actions/checkout` seems to get a commit when triggered, not the _latest_ one when you run the same workflow with the [concurrency settings](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency).
Let's say we have an example that pushes a commit when triggered, like:

```yaml
concurrency: ${{ github.workflow }} # set the concurrency setting at workflow level
# ...
- uses: actions/checkout@v3
- run: |
  # making some file and git config changes
  git commit -am "update something"
  git push
```

If we run this workflow twice immediately, the second run won't have a commit pushed on the first run. Is there a way to get it on the second?
This can be resolved by `git pull`'ing before committing but I wonder if `actions/checkout` could resolve it somehow, and I guess it'd be a better way.
