### DISCUSSION TITLE
What's the fastest way to check if branch is up to date with the main branch?

### DISCUSSION THREAD

**Discussion by gajus** [actions/checkout#1547] [Q&A]
This is what we are using at the moment:

```yaml
  before_all:
    name: 'before all'
    runs-on:
      - self-hosted
      - contra-general-purpose
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check if branch is ahead of main
        run: |
          if ! git merge-base --is-ancestor origin/main ${{ github.event.pull_request.head.sha }};
          then echo "This branch is not up to date with main";
          exit 1; fi
      - run: echo "Starting CI"
```

However, this step is taking upwards of 2 minutes in our large repository.
