### DISCUSSION TITLE
checkout multi repos at the same dir not work

### DISCUSSION THREAD

**Discussion by pplmx** [actions/checkout#1577] [Q&A]
## Its output

```log
/usr/bin/git config --global --add safe.directory /home/runner/work/yoooo.fun/yoooo.fun/hugo

/usr/bin/git config --global --add safe.directory /home/runner/work/yoooo.fun/yoooo.fun/hexo
```
which is not my expectation:
`/home/runner/work/repo1`
`/home/runner/work/repo2`

here is my config:

```yml
jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout yoooo.fun repo
                uses: actions/checkout@v4
                with:
                    submodules: recursive  # Fetch the Docsy theme
                    fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
                    path: hugo             # like as "git clone <repo_url> hugo"
            -   name: Checkout caoyu.info repo
                uses: actions/checkout@v4
                with:
                    repository: pplmx/caoyu.info
                    token: ${{ secrets.PAT }}
                    path: hexo             # like as "git clone <repo_url> hexo"
```
