### DISCUSSION TITLE
Is there a way to to list all the branches from an external repo?

### DISCUSSION THREAD

**Discussion by awhisler** [actions/checkout#1635] [General]
I have a use case where we are running a pipeline that runs QA testing automation but sometimes, based on new requirements, I want the ref to change if there is an existing branch out there with the same name as the current repo
![image](https://github.com/actions/checkout/assets/2396250/776252e0-735e-489d-b041-00501dd81938)

Workflow goes as follow:
1. On PR on a front end framework, the github action is triggered and it checks out an external repo, clones it, and brings it to this repo
2. But whenever I need to make a change on the automation to accommodate new requirements, I add a branch with the same name as the front end repo
3. So what I want to be able to do is list all the branches in this remote repo so that I can say 'if one of these branches matches the current branch, use that branch as the ref' and if not, just use main

I saw there was a fetch-depth property but looking at the documentation, I don't exactly see how I can list this history or access the list

**Comment by Chiragsd13** [comment]
You can solve this without `fetch-depth` — the trick is `git ls-remote` to probe the remote branch list before checkout.

Here is a workflow snippet that does exactly what you describe:

```yaml
- name: Resolve ref for external repo
  id: resolve-ref
  env:
    BRANCH: ${{ github.head_ref }}  # the PR branch name
  run: |
    # Check if this branch exists in the external repo
    MATCH=$(git ls-remote --heads https://github.com/your-org/external-repo.git "refs/heads/$BRANCH" | wc -l)
    if [ "$MATCH" -gt "0" ]; then
      echo "ref=$BRANCH" >> $GITHUB_OUTPUT
    else
      echo "ref=main" >> $GITHUB_OUTPUT
    fi

- uses: actions/checkout@v4
  with:
    repository: your-org/external-repo
    ref: ${{ steps.resolve-ref.outputs.ref }}
    token: ${{ secrets.GITHUB_TOKEN }}
```

`git ls-remote --heads` does not clone the repo — it just queries the remote refs over the network, so it is fast. The `wc -l` check returns `1` if the branch exists, `0` if it does not.

If the external repo is private, replace the HTTPS URL with the SSH form and make sure your runner has the appropriate deploy key or PAT configured.

For the pattern you described (test repo branch mirrors the frontend branch), this is the standard approach most teams use.
