### DISCUSSION TITLE
Caching results

### DISCUSSION THREAD

**Discussion by serrg** [actions/checkout#259] [General]
Hi,
I would like to open a topic regarding caching results of `actions/checkout@v2`.

Let's assume that we have a workflow like:
```
jobs:
  lint:
    steps:
      - uses: actions/checkout@v2
  test:
    needs: lint
    steps:
      - uses: actions/checkout@v2
  build:
    needs: test
    steps:
      - uses: actions/checkout@v2
  push:
    needs: build
    steps:
      - uses: actions/checkout@v2
```
and in every job we need to checkout repository again.

What about adding first step like:
```
jobs:
  download_code:
    steps:
      - uses: actions/checkout@v2
```
and use artefact of checkout in any other connected jobs ?

In `CircleCI` we can do something like:
```
jobs:
  checkout_code:
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  lint:
    executor: node
    steps:
      - attach_workspace:
          at: ~/repo
```

The only solution I know for now is using `actions/cache@v1`
