### DISCUSSION TITLE
[Question] cleaning up: should I worry about comitting fetched repo if I commit in a following step

### DISCUSSION THREAD

**Discussion by manuartero** [actions/checkout#384] [Q&A]
Hi there. 

This is our use case: we are fetching a repo containing a toolkit of Github Actions to be used in our own workflows

```yaml
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Checkout our github-actions repo
        uses: actions/checkout@v2
        with:
          repository: ......
          path: .github/actions
```

Later on, in this very same workflow we're running a lint action that formats and **commits code.** 

**Q**: Should we have another action to cleaning up the `.github/actions` folder?
