### DISCUSSION TITLE
Pushing content from a folder to a branch without the folder?

### DISCUSSION THREAD

**Discussion by Andre601** [actions/checkout#405] [Q&A] [answered]
I'm in the work of creating a workflow to automatically push changes made to a folder within a specific branch to another branch, that is used to publish the content to GitHub Pages.

I have the following folder structure.

```
(root)
  |
  |- .github
  |    |
  |    |- workflows
  |         |
  |         |- publish.yml # The workflow
  |
  |- site # Contains the content I want to push
  |
  |- README.md # Give some into
```

In addition do I have the branches `development` (default) and `master` (publishing)

My goal now is, to take the content in `site` and push it to the master branch using git.
I currently struggle with the following issues tho:

1. I'm not an expert with git, so I don't know how I should setup everything that it will push `development` into `master`
2. I don't want master to be an exact copy of development. I want the content of `site` to be in the root for master, so that it is visible in GitHub Pages.

To close this off is here the current not working Workflow file:
```yaml
name: Deploy Site

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory
    branches:
    - development # Only trigger on the development branch

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Deploy Files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add site # Add changes made in site to commit
        git commit -m "Update Website (${GITHUB_SHA:0:7})"
        git push master origin # Is this how it will be pushed?
```

I appreciate any help.

**Comment by peaceiris** [comment, marked as answer]
How about the following workflow?

[peaceiris/actions-gh-pages: GitHub Actions for GitHub Pages 🚀 Deploy static files and publish your site easily. Static-Site-Generators-friendly.](https://github.com/peaceiris/actions-gh-pages)

```yaml
name: Deploy Site

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory
    branches:
    - development # Only trigger on the development branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: master
```
