### DISCUSSION TITLE
Workflow using $default-branch not triggered

### DISCUSSION THREAD

**Discussion by jeffmaury** [actions/checkout#429] [Q&A]
I have a workflow whose trigger is the following:

```
name: Deploy

on:
  pull_request:
    branches: [ $default-branch ]
  push:
    branches: [ $default-branch, 'production' ]
```

However, I don't see it being triggered when a new PR is submitted.
