### DISCUSSION TITLE
How to checkout "master" in addition to latest PR commit?

### DISCUSSION THREAD

**Discussion by pepoluan** [actions/checkout#434] [Q&A]
Currently I have the following steps in my GA workflow:

```yaml
      - name: "Checkout latest PR commit"
        uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Update modules & install deps"
        # language=bash
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python setup.py develop
      - name: "flake8 Style Checking"
        # language=bash
        run: |
          pip install colorama flake8
          python -m flake8 aiosmtpd setup.py housekeep.py release.py
      - name: "Static Type Checking"
        # language=bash
        run: |
          pip install pytype
          pytype --keep-going --jobs auto .
      - name: "Other QA Checks"
        # language=bash
        run: |
          pip install pytest pytest-mock check-manifest
          pytest -v aiosmtpd/qa
          check-manifest -v
```

Now, one of the tests _need_ to access the `master` branch. I've tried adding another checkout step, like so:

```yaml
      - name: "Checkout latest master"
        uses: actions/checkout@v2
        with:
          ref: "master"
      - name: "Checkout latest PR commit"
        uses: actions/checkout@v2
```

But that checkout step got nuked when the second step began:

```
Removing previously created refs, to avoid conflicts
  /usr/bin/git rev-parse --symbolic-full-name --verify --quiet HEAD
  refs/heads/master
  /usr/bin/git checkout --detach
  HEAD is now at b47eeb0 Fix RTD requirements.txt and bump
  /usr/bin/git rev-parse --symbolic-full-name --branches
  refs/heads/master
  /usr/bin/git branch --delete --force master
  Deleted branch master (was b47eeb0).
```

So how do I checkout _both_ `master` and the latest PR commit?

**Comment by yahel2410** [comment]
I think you can use the `path` input to specify another dir for the `master` checkout. E.g:

```
      - name: "Checkout latest master"
        uses: actions/checkout@v3
        with:
          ref: "master"
          path: "./master-branch`          # <======== here
      - name: "Checkout latest PR commit"
        uses: actions/checkout@v3
```

Notice that I use `v3` of the `actions/checkout` action
