### DISCUSSION TITLE
How to checkout lfs inside private submodule?

### DISCUSSION THREAD

**Discussion by tamuhey** [actions/checkout#457] [Q&A]
Hi, I want to checkout LFS files inside a submodule, which is a private repo.
How to do that?

**Comment by dskvr** [comment]
+1

**Comment by yair-mantis** [comment]
try the `ssh-key` option as secret,


```yaml
name: CI 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          lfs: 'true'
          submodules: 'recursive'
          ssh-key: ${{ secrets.git_ssh_key }}

        env:
          GIT_CURL_VERBOSE: '1'
          GIT_TRACE: '1'
```
the `env` trace are just for debug
