### DISCUSSION TITLE
Pushing to a new remote server using actions.

### DISCUSSION THREAD

**Discussion by Bas-Man** [actions/checkout#544] [Q&A] [answered]
Hi,
I was wondering if it is possible to have checkout push to a new remote host.

I would like to do something like

```
name: Linode Pull update

on:
  push:
    branches:
      - linode

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.LINODE_KEY }}
          ssh-strict: false
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout linode
          git remote add prod ssh://user@host/var/repos/some-repo.git
          git push prod
```

Does this look correct? At the moment I am getting an error with SSH. So it might be a config error on my side.

Just wondering if I am on the right path or not.
Thanks.
