### DISCUSSION TITLE
Using cache as part of a Debian package installation action.

### DISCUSSION THREAD

**Discussion by awalsh128** [actions/checkout#585] [Q&A]
I am leveraging the cache to synchronize required Debian packages in my action.

```yaml
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: "~/cache-deps"
          key: cache-deps

      - name: Install Dependencies
        run: ${{github.workspace}}/.github/workflows/deps_install.sh "~/cache-deps"
```

```bash
#!/bin/bash

cache_dir=$1
packages="dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen"

for dir in `ls $cache_dir`; do
  remove=true
  for package in $packages; do
    if [ $dir == $package ]; then
      remove=false
      break
    fi
  done
  [ $remove ] && rm -fr $cache_dir/$dir
done

for package in $packages; do
 
  package_dir=$cache_dir/$package

  if [ -d $package_dir ]; then
  
    echo "Restoring $package from cache $package_dir..."    
    sudo cp --verbose --force --recursive $package_dir/* /
    sudo apt-get --yes --only-upgrade install $package

  else

    echo "Clean install $package and caching to $package_dir..."
    sudo apt-get --yes install $package

    echo "Caching $package to $package_dir..."
    mkdir --parents $package_dir
    # Pipe all package files (no folders) to copy command.
    sudo dpkg -L $package | 
      while IFS= read -r f; do 
        if test -f $f; then echo $f; fi;
      done | 
      xargs cp -p -t $package_dir
  fi

done
```

It would be nice to integrate the work into a single action. Part of me to just fork this repo and add my wrapper functionality. Is there a better way to do this or any other ideas on accomplishing this?
