### DISCUSSION TITLE
Permission error when archive shall be written to disk

### DISCUSSION THREAD

**Discussion by jeltsch** [actions/checkout#586] [Q&A]
I’m trying to use an image from Docker Hub, `makarius/isabelle`, for automated builds. However, checking out the repository fails with the error `EACCES: permission denied, open '/__w/⟨repository-name⟩/⟨repository-name⟩/⟨uuid⟩.tar.gz'`. A minimal workflow file that triggers this error is as follows:
```
name: Automated checkout

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    container: makarius/isabelle
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
```
The repository is downloaded using the GitHub REST API.

How can I fix this workflow?
