### DISCUSSION TITLE
No Way to Use Deploy Key Only For Specific Submodule?

### DISCUSSION THREAD

**Discussion by xanderdunn** [actions/checkout#907] [Q&A]
I have a private repository. It has two submodules in it. One of them is public, and one of them is private. 

```
      - name: Checkout my repo
        uses: actions/checkout@v3
```
The above succeeds, but fails to fetch any of the submodules.

```
      - name: Checkout my repo
        uses: actions/checkout@v3
        with:
            submodules: 'true'      
```
The above fails because it can't checkout the private submodule.

I create a deploy key on the private submodule's repository, and add the private key as a secret on the repository where I'm running this GitHub Action. However:

```
      - name: Checkout my repo
        uses: actions/checkout@v3
        with:
            submodules: 'true'
            ssh-key: ${{ secrets.ACTION_SSH_SECRET }}
```
The above fails because it tries to use the `ssh-key` for all three repositories: this repo, the public submodule, and the private submodule. This fails on both this repo and the public submodule because the deploy key is only on the private submodule. 

So, I manually check out reach repository:
```
      - name: Checkout my repo
        uses: actions/checkout@v3
      - name: Checkout public submodule
        run: |
          git clone https://github.com/foundry-rs/forge-std subnet-evm/test_precompile/lib/forge-std
          cd subnet-evm/test_precompile/lib/forge-std
          git submodule update --init --recursive

      - name: Checkout private submodule
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ACTION_SSH_SECRET }}" > ~/.ssh/id_deploy_key
          chmod 600 ~/.ssh/id_deploy_key
          cd subnet-evm
          GIT_SSH_COMMAND='ssh -i ~/.ssh/id_deploy_key' git clone --single-branch --branch my_branch git@github.com:my-org/private-repo.git
```

Is there really no way to do this with the checkout action? Must I maintain all of the above manually? It's fragile because I'm not actually using what's in the .gitmodules, I've hard-coded every repo to be checked out in the GitHub Action. It would be nice if the ssh-key could be specified for a specific submodule, or if it would fallback to the default credentials if the ssh-key fails.
