### DISCUSSION TITLE
how to `git config` before `git checkout`

### DISCUSSION THREAD

**Discussion by jtmoon79** [actions/checkout#976] [Q&A] [answered]
In my rust workflow yaml file, I have `uses: actions/checkout@v2`. I would like to run a `git config` command _before_ the code checkout occurs. How can I do that?

In other words, what would I change here?
```yaml
  job_rust_msrv_os:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --verbose
```

**Comment by dscho** [comment, marked as answer]
You should be able to run `git config --global ...` and that should be picked up by the `actions/checkout` step.

**Comment by jtmoon79** [comment]
In my case, this looked like

```yaml
  job_rust_msrv_os:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --verbose
      - ``  job_rust_msrv_os:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          git config --global core.protectNTFS false
      - uses: actions/checkout@v2
      - run: cargo build --verbose
```
