### ISSUE TITLE
"fetch-depth: 0" doesn't fetch all branches

### ISSUE THREAD

**Issue by vitalyk-multinarity** [actions/checkout#1017]
I'm using the following snipped for checkout:

```
- name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

but when I run 'git branch ' later I see just one branch.
Please suggest,
Thanks,
Vitaly
