### ISSUE TITLE
`git log` is empty

### ISSUE THREAD

**Issue by tushar-deepsource** [actions/checkout#1049]
Using the following method to checkout:

```yaml
steps:
- name: Checkout code
  uses: actions/checkout@v2
  with:
    fetch-depth: 50
    ref: ${{ github.event.pull_request.head.sha }}
```

The git directory (`/github/workspace`) gets into this state:

- `git log` is empty
- `git rev-list --all` is empty
- `$GITHUB_REF` is `refs/pull/123/merge`

This changed recently, within the past couple days -- `git log` didn't use to be empty before.
