### ISSUE TITLE
Ability to fallback to a different branch on failure

### ISSUE THREAD

**Issue by znarf** [actions/checkout#105]
This is a feature request. Because it's an advanced feature, I understand that it might not be directly implemented but some smaller features would unlock it.

## Use case

At Open Collective, we have 2 main repositories, one for our API and one for our Frontend. In our CI, we have e2e tests which are requiring a checkout of both API and Frontend to run.

- In the most simple scenario, we run a checkout of `master` in both projects
- In the most common scenario, we run the e2e tests on feature branches of the API, and they run fine with the `master` Frontend because they don't require any modifications of the Frontend
- In an advanced scenario, if a feature needs a modification on both API and Frontend, we're using by convention the same exact branch name on API and Frontend (ie: `feat/new-events-page`) and we want the e2e test to use checkouts of these branches.

## Status Quo

We're using some magic script that is implementing the functionality using downloaded tarballs  (didn't write that!) .
https://github.com/opencollective/opencollective-api/blob/master/scripts/ci_checkout_frontend.sh

## GitHub Actions to the rescue

We would like to use a nicely written GitHub Action for that. My initial implementation would be:

```
      - name: Checkout (frontend - matching branch)
        uses: actions/checkout@v2-beta
        with:
          repository: opencollective/opencollective-frontend
          path: opencollective-frontend
          ref: ${{ github.ref }}

      - name: Checkout (frontend - master)
        if: failure()
        uses: actions/checkout@v2-beta
        with:
          repository: opencollective/opencollective-frontend
          path: opencollective-frontend
          ref: master
```

https://github.com/opencollective/opencollective-api/pull/3031
https://github.com/opencollective/opencollective-api/pull/3031/checks?check_run_id=343540511

It's almost working but unfortunately the first command is sending a CI failure and we can't proceed normally after.

## Feature Request

1) Ability to skip the failure signal if the checkout doesn't work

```
      - name: Checkout (frontend - matching branch)
        uses: actions/checkout@v2-beta
        with:
          repository: 'opencollective/opencollective-frontend'
          ref: ${{ github.ref }}
          silentFailure: true
```

2) Ability to know if the checkout with a given id failed

```
      - name: Checkout (frontend - matching branch)
        uses: actions/checkout@v2-beta
        id: checkout-matching-branch
        with:
          repository: 'opencollective/opencollective-frontend'
          ref: ${{ github.ref }}
          silentFailure: true

      - name: Checkout (frontend - master)
        if: steps.checkout-matching-branch.outputs.failure === 'true'
        uses: actions/checkout@v2-beta
        with:
          repository: 'opencollective/opencollective-frontend'
          ref: master
```

**Comment by chrispat** [comment]
@znarf You can always set `continue-on-error` for the step and a failure will not cause the overall workflow to fail https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error.

**Comment by znarf** [comment]
@chrispat Thank you for pointing on `continue-on-error`, I missed that. That could effectively replace the first item.

For the second item, I guess that should not be complicated to implement, I shared a proof of concept as Pull Request, let me know what you think.

**Comment by chrispat** [comment]
@znarf the second item is not something that really should be implemented in a single action, it would need to be implemented in the runner so it is consistently applied to all actions.  We do have a feature on our backlog to add `steps.<step id>.outcome` to the context.

**Comment by znarf** [comment]
@chrispat all right, let me know if there is an open issue so I can have a look.

**Comment by chrispat** [comment]
@znarf unfortunately those issues are not in a public repo.

**Comment by znarf** [comment]
@chrispat Would the work be in https://github.com/actions/toolkit ? If yes, which of the packages  https://github.com/actions/toolkit/tree/master/packages would be affected?

**Comment by chrispat** [comment]
@znarf the work has to happen in the runner which is they only place where state is stored between executions of different actions.

**Comment by ericsciple** [comment]
this should be a small change. i'll open an ADR soon.

**Comment by ericsciple** [comment]
Thinking more about this, i believe you will get hit with a retry if you rely on failure.

A better solution might be to check if the branch exists (query REST API), and set an output that you can use in the `if` condition to determine whether to checkout from the other repo.

Something like this:
```
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: check-branch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/git/ref/:ref
          owner: some-owner
          repo: some-repo
          ref: heads/master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - if: steps.check-branch.outputs.status == 200
        run: echo Branch exists
      - if: steps.check-branch.outputs.status != 200
        run: echo Branch does not exist
```

However when 404, it appears octokit/request-action creates error annotations so i'm not sure thats what you want but it's close. Might be a good starting point.

**Comment by ericsciple** [comment]
also i noticed it doesnt appear to set any outputs when 404 (not even `status`)

**Comment by ximon18** [comment]
I worked around this by testing for the existence of the branch then checking out the right branch. See: 
https://github.com/NLnetLabs/krill/commit/942f6a9fe9b43c2ddcd5adec261964359133d8e0

**Comment by ericsciple** [comment]
closing. fwiw proposal here for adding step outcome https://github.com/actions/runner/pull/274

**Comment by negebauer** [comment]
i"m having an issue with the steps check. If I do the following:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test failed
        id: failed
        run: exit 1
      - name: Test not failed
        id: notfailed
        if: success() || failure()
        run: exit 0
      - name: Should run
        id: bar
        if: steps.notfailed.outcome == 'success'
        run: exit 0
```

The `Should run` step doesn't run, even thought `steps.notfailed.outcome == 'success'` evaluates to `true`.

But if I write the step as

```yaml
      - name: Should run
        id: bar
        if: steps.notfailed.outcome == 'success' || success()
        run: exit 0
```

It works. It's like the step check is not enough? (Given that `success()` is false since the first step failed.
