### ISSUE TITLE
Support selecting individual submodules to update

### ISSUE THREAD

**Issue by prein** [actions/checkout#1095]
The goal is shorter checkout times for repos with many submodules. A particular job may need just one of many modules.
It would be an equivalent of looping over
```
git submodule update --init $submodule_name
```
where a list of `submodule_name` would come from parameter passed to `actions/checkout` like so (for example):
```
  - uses: actions/checkout@v3
        with:
          submodules:
            only:
              - foo
              - bar
```
Ideally the implementation would have also the possibility for blacklisting the modules (naming the ones to not to update) with equivalent of  `-c submodule."contrib/foo".update=none`
