### ISSUE TITLE
Documentation about pushing to repo is out of date 

### ISSUE THREAD

**Issue by enthusiasmus** [actions/checkout#1121]
Dear developers,

the documentation for pushing back to a repo seems not to be up to date.

documentation:
![grafik](https://user-images.githubusercontent.com/1102208/212886155-9641561f-aaa2-4fe6-a668-55c2abfc2384.png)

output from github action:
![grafik](https://user-images.githubusercontent.com/1102208/212886108-0dec9ef0-22ee-43a5-afe5-f42a167473df.png)

Still trying to figure out, how to push back to my repo. Lets see.
Best regards

**Comment by cadenzah** [comment]
Maybe same problem here.

My repository is a private one. I built my app bundle and `cd` on it, initiating a new repository whose remote origin is same as the previous one. I tried to make a orphan branch(`gh-pages`) and pushed it, and I got the following error:

`fatal: could not read Username for 'https://github.com/': No such device or address`

Here is a total Github workflow yaml below:

```yaml
name: Build and Deploy on Github Page
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  setup-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to ${{ github.ref }} branch 🛎️
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      
      - name: Setup Node.js 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate .env ⚙️
        run: |
          echo "_PAGE_TITLE=\"${{ vars._PAGE_TITLE }}\"" >> .env
          echo "_PAGE_DESCRIPTION=\"${{ vars._PAGE_DESCRIPTION }}\"" >> .env
          echo "_PAGE_URL=\"${{ vars._PAGE_URL }}\"" >> .env
          echo "_REPO_NAME=\"${{ vars._REPO_NAME }}\"" >> .env
      
      - name: Install app 📦
        run: yarn install # yarn install

      - name: Setup Git Identity 🐙
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          # git config --global credential.helper cache # works same whether or not
      
      - name: Build and Deploy 🚀
        run: yarn gh-deploy
```

```sh
#!/usr/bin/env sh

# https://vitejs.dev/guide/static-deploy.html
set -e

yarn build

cd dist

echo > .nojekyll

git init
git checkout -B main
git add -A
git commit -m 'github page deploy'

# same as the repository which started the github action
git remote add origin https://github.com/cadenzah/xxxxx.git

git push -f origin main:gh-pages

cd ..
rm -rf dist
```

I wonder what is wrong with my configuration. Is it the issue with credential(PAT)?
