### ISSUE TITLE
How to make multiple jobs checkout separately

### ISSUE THREAD

**Issue by smallprogram** [actions/checkout#1129]
I have a workflows, 
```yml
name: "Auto update packages"
env:
  TZ: Asia/Shanghai


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Modify the source code
        run: |
          # socuce code change

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "some commit message"
          branch: packages

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Modify the source code
        run: |
          # socuce code change

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "some commit message"
          branch: packages
```

When the first checkout action runs, the obtained git head is `9dfd42c3cf2da4d9da8a84e18cc4fece96ce5f45`

After the first job modifies the source code and submits it, the git head of the repository is `39b5e42c136276298c53a14fed27ad9877f61f5c`

Normally, the checkout action of the second job should get the git head `39b5e42c136276298c53a14fed27ad9877f61f5c`, but in fact the git head obtained by the second checkout action is still `9dfd42c3cf2da4d9da8a84e18cc4fece96ce5f45`, is there any way to get the second job to the latest source version?
