### ISSUE TITLE
extremely slow on windows

### ISSUE THREAD

**Issue by asottile** [actions/checkout#1150]
this action adds significant overhead to getting set up, I don't really know why but I tried comparing it in an empty repo against `time git clone ...`

- actions/checkout@v3 ([an empty repo from github](https://github.com/asottile/test-plz-ignore/actions/runs/4050302098/jobs/6967565903)): 11+ seconds
- `time git clone --depth=1 (an empty repo from github)` (on a `windows-latest` runner): `.613s`
- actions/checkout@v3 pre-commit/pre-commit: 37+ seconds
- `time git clone --depth=1 https://github.com/pre-commit/pre-comit` (on a `windows-latest` runner): `.802s`

I get that windows tends to be slower than the linux runners, but this feels unacceptably slow.  even linux feels slower than it should be (`actions/checkout@v3` in pre-commit takes 2 seconds there)

here's the yaml that I used to test this (will probably delete the empty repo above since I just wanted to see how long it takes):

```yaml
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        set -x
        time git clone https://github.com/asottile/test-plz-ignore --depth=1
        time git clone https://github.com/pre-commit/pre-commit --depth=1
      shell: bash
```
