### ISSUE TITLE
Workflow does not automatically trigger a workflow using a custom PAT in @v3 version

### ISSUE THREAD

**Issue by ofer987** [actions/checkout#1167]
We followed the steps in [Triggering a workflow from a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) using `actions/checkout@v3` to automatically trigger another workflow using a custom Personal Access Token that _only_ had the `repo` and `workflow` permissions. But it _did not_ automatically trigger.

The workflow file was located in `.github/workflows/ci.yml`, and it looked like this,

```yaml
name: CI

on: [push]

jobs:
  create_tag:
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create tag
        run: |
          git tag release--1.0.0
          git push --tags "https://$BOT_USERNAME:$BOT_PASSWORD@github.com/<org>/<repo-name>.git"
        shell: bash
        env:
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}

  deploy:
    needs: [create_tag]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/release-')
        shell: bash
        run: |
          <deploy-command>
```

Is this a bug in the `v3` version?

We resolved it by downgrading to the `v1` version.

Thank you,
Dan

CC: @aliaksandrlitr

**Comment by benjamin-bergia** [comment]
I think I am having the same issue. Unfortunately I checkout multiple repos with `path` and so I cannot revert to v1 :( 
After testing with `v2` and `v2.0.0` it still doesn't work. 

My repo is private so I don't know if it's related

**Comment by Thinkuknow** [comment]
So

**Comment by twang817** [comment]
I struggled with this a bit too.  It turns out `actions/checkout` v2 & v3 will configure git to use an authentication token as part of the repository configuration.

This means that the token used _during checkout_ is the persisted form of authentication for all future git commands.  Passing authentication in the URL thereafter does **not** work.

The solution is either:
1. Set the token on the checkout step.  Later steps will not need any additional authentication configuration
2. Set the persist_credentials to false in the action step, and all later steps will need to handle authentication.

```yaml
name: CI

on: [push]

jobs:
  create_tag:
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Create tag
        run: |
          git tag release--1.0.0
          git push --tags "https://$BOT_USERNAME:$BOT_PASSWORD@github.com/<org>/<repo-name>.git"
        shell: bash

  deploy:
    needs: [create_tag]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/release-')
        shell: bash
        run: |
          <deploy-command>
```
