### ISSUE TITLE
/github/home/.gitconfig does not exist for container runs

### ISSUE THREAD

**Issue by arbourd** [actions/checkout#1169]
### Issue

If running a job that uses a container like the below, the file `/github/home/.gitconfig` will not exist.

```yaml
  example:
    runs-on: ubuntu-latest
    container:
      image: alpine
```

[Here is a demo](https://github.com/arbourd/dotfiles/actions/runs/4149133047/jobs/7177815475).

The `safe.directory` settings [set by the command](https://github.com/actions/checkout/blob/ac593985615ec2ede58e132d2e21d2b1cbd6127c/src/git-source-provider.ts#L52) `git config --system --add safe.directory <path>
` is a no-op, if the job is running in a container.

### Workaround

Use the `--system` scope over `--global`:

```console
$ git config --system --add safe.directory <path>
```

```yaml
  example:
    runs-on: ubuntu-latest
    container:
      image: alpine

    steps:
      - uses: actions/checkout@v3
      - run: git config --system --add safe.directory <path>
```

**Comment by destroyersrt** [comment]
I tried the workaround but it doesn't seem to work in my case. 

<img width="613" alt="image" src="https://user-images.githubusercontent.com/46970362/218958494-7a7cc7a1-acb5-407a-8b7d-c570b3018c36.png">

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/46970362/218958238-1f856875-6d86-489f-bb9c-0743ca509f11.png">

**Comment by arbourd** [comment]
> I tried the workaround but it doesn't seem to work in my case.
> 
> <img alt="image" width="613" src="https://user-images.githubusercontent.com/46970362/218958494-7a7cc7a1-acb5-407a-8b7d-c570b3018c36.png">
> 
> <img alt="image" width="1330" src="https://user-images.githubusercontent.com/46970362/218958238-1f856875-6d86-489f-bb9c-0743ca509f11.png">

Uses `--system` instead of `--global`

**Comment by arbourd** [comment]
> I tried the workaround but it doesn't seem to work in my case.
> 
> <img alt="image" width="613" src="https://user-images.githubusercontent.com/46970362/218958494-7a7cc7a1-acb5-407a-8b7d-c570b3018c36.png">
> 
> <img alt="image" width="1330" src="https://user-images.githubusercontent.com/46970362/218958238-1f856875-6d86-489f-bb9c-0743ca509f11.png">

Try without the `sudo`? Might ahve something to do with the Slither action itself too and if it spins up containers.

**Comment by destroyersrt** [comment]
At first I tried without `sudo` but got permission denied error.

**Comment by LecrisUT** [comment]
Should note that the workaround described here is only for container runs

**Comment by xjlin0** [comment]
Workaround doesn't work for me, when I switch from --global to --system, it fails with permission error
```yaml
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: change --global to --system
        run: git config --system --add safe.directory /app
```
results:
```
Run git config --system --add safe.directory /app
error: could not lock config file /etc/gitconfig: Permission denied
Error: Process completed with exit code 255.
```
Any suggestions? thanks!

**Comment by xjlin0** [comment]
@LecrisUT thanks for the reminder, could you let me know the containers specific thing?  My repo is running Django in the container, could I make its github actions pass by the workaround? thanks!

**Comment by LecrisUT** [comment]
The container specific here refers to the Gihub action running as:
```
jobs:
  pytest:
    runs-on: ubuntu-latest
    container: fedora:laters
```
In this case there are specific volumes that are mounted and specific flags passed. When you run your own setup via `docker-compose`, you need to check what this does to replicate it. I don't know exactly what this does tbh.

**Comment by ST-DDT** [comment]
FFR: Using the users opzion might help here for the related issue:
https://github.com/actions/runner/issues/2033#issuecomment-1598547465

**Comment by theory** [comment]
I banged my head on what I think is this issue _all day_. Consider this config:

```yaml
name: Test Git
on:
  push:
jobs:
  bundle:
    name: Git
    runs-on: ubuntu-latest
    container: alpine/git
    steps:
    - uses: actions/checkout@v4
    - run: git archive -v --format zip --prefix foo/ --output foo.zip HEAD
```

This results in [this error](https://github.com/theory/test-pgxn-tools/actions/runs/7590852429/job/20678060042):

```
fatal: detected dubious ownership in repository at '/__w/test-pgxn-tools/test-pgxn-tools'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/test-pgxn-tools/test-pgxn-tools
```

Shouldn't we be able to do Git stuff with the repo in a container? Curious, I tried changing the last line to:

``` yaml
    - run: git config safe.directory
```

It simply exits with no error message, as in [this run](https://github.com/theory/test-pgxn-tools/actions/runs/7590864039/job/20678089250):

```
Run git config safe.directory
  git config safe.directory
  shell: sh -e {0}
Error: Process completed with exit code 1.
```

Is that because the global config file is missing? I find it simply wild that there is no error message.

Anyway, I then tried setting the global config:

``` yaml
    - run: git config --global --add safe.directory "$PWD"
```

And [that works](https://github.com/theory/test-pgxn-tools/actions/runs/7590886232/job/20678145360). But I admit I'm pretty confused about why this isn't set up by default when an action starts.

So fine, I can manually put this line into my workflow YAML files, but I'm mystified as to why it's necessary. Is it this issue or am I missing something?

Thanks for bearing with my examples.

**Comment by theory** [comment]
> It simply exits with no error message, as in [this run](https://github.com/theory/test-pgxn-tools/actions/runs/7590864039/job/20678089250):

FWIW I see the same error using actions/checkout@v3 in [this build](https://github.com/theory/test-pgxn-tools/actions/runs/7590984103/job/20678394657) an using actions/checkout@v2 in [this build](https://github.com/theory/test-pgxn-tools/actions/runs/7591000518/job/20678436101). Color me confused.

**Comment by theory** [comment]
I'm [fixing the issue in pgxn-tools](/pgxn/docker-pgxn-tools/pull/9) by adding this line to the `Dockerfile` to disable the check inside the running container:

```sh
git config --system --add safe.directory '*'
```

Is there any reason that is likely to be a security issue?

**Comment by feltech** [comment]
Thanks for this. Adding a step to our job with `git config --system --add safe.directory $(pwd)` works around the issue.

For info, did a little experiment and added a step to print the `id` and owner of `pwd` - for some reason `actions/checkout` checks out the repo as user 1001, even though there is no such user in the container. Output from CI
```
Run id
  id
  ls -ld $(pwd)
  shell: sh -e {0}
uid=0(root) gid=0(root) groups=0(root)
drwxr-xr-x 7 1001 127 4096 Aug 15 15:40 /__w/OpenAssetIO-Test-CMake/OpenAssetIO-Test-CMake
```

For reference, the upstream change to git that performs this check appears to be https://github.com/git/git/commit/f4aa8c8bb11dae6e769cd930565173808cbb69c8

**Comment by mxw-sec** [comment]
Any working arounds for this, I am seeing the same /github/home/.gitconfig doesn't exist message on Terraform-docs/gh-actions.

**Comment by damlys** [comment]
That works for me so far

```
name: example
jobs:
  example:
    name: example
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/devcontainer:1.0.0
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: git clone fix
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
```

`$GITHUB_WORKSPACE` allows me to use that between repositories without changes

**Comment by vvanouytsel** [comment]
The following should also work, and saves you an extra `run` step.

```yaml
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          set-safe-directory: ${{ github.workspace }}
```
