### ISSUE TITLE
Alpine 3.7: Error relocating /__e/node16_alpine/bin/node: getentropy: symbol not found

### ISSUE THREAD

**Issue by mlocati** [actions/checkout#1183]
With this action:

```yml
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: php:7.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
```

we have this error:

```
Error relocating /__e/node16_alpine/bin/node: getentropy: symbol not found
```
