### ISSUE TITLE
.git directory is not where it's expected to be

### ISSUE THREAD

**Issue by Southclaws** [actions/checkout#1188]
I'm trying to clone a small _separate_ repo into the repo of the running action in order to commit some output artifacts there.

```yaml
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: myorg/mocks
          token: ${{ secrets.MOCK_REPO_TOKEN }}
          path: tests/mocks
```

The first invocation is the normal checkout step to get my codebase into the CI, then I'm checking out a different repo into a (gitignored) subdirectory.

Then my code dumps some outputs into this and later on I commit+push to the other repo:

```yaml
      - name: Commit changes
        working-directory: tests/mocks
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add -f .
          git commit -m"mockgen"
          git push
```

The problem is, if I add an `ls -la` to my command, there's no `.git` directory here. What actually happened was this final step committed the changes to the main repository (from which the action is running) and uploaded those files there, not `myorg/mocks`.

Is there a reason the .git directory is missing? Can I configure this action to do a normal git clone with that directory present in `path: tests/mocks`?
