### ISSUE TITLE
[bug] 'fetch-depth: 0' always miss current tag

### ISSUE THREAD

**Issue by Freed-Wu** [actions/checkout#1190]
```yaml
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

Then
```
git tag 0.0.3
git push --tags
```

Expected: in CI machine, `git describe` will return `0.0.3`
Actual: `0.0.2-1-ged78cae`
