### ISSUE TITLE
Checkout with fetch-depth: 0 leads me to wrong ref.

### ISSUE THREAD

**Issue by sukyoungjeong-furiosa** [actions/checkout#1262]
```yaml
name: Trigger-when-success
on:
  status:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'success' &&
      github.event.context == 'test'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
```

I'm using a manifest as above.

I intended to checkout to the commit with full history so that I can make use of several git subcommands.

The result log shows below message, and I found that `actions/checkout` has led me to remotes/origin/main, not to the commit that triggered the github actions.

```
   * [new branch]      main            -> origin/main
   * [new branch]      test_pr -> origin/test_pr
  /usr/bin/git branch --list --remote origin/main
    origin/main
  /usr/bin/git rev-parse refs/remotes/origin/main
  b8810315ca71904820101d25e04c4ce4a4a9d413
Determining the checkout info
Checking out the ref
/usr/bin/git log -1 --format='%H'
'b8810315ca71904820101d25e04c4ce4a4a9d413'
```

**Comment by jww3** [comment]
Per the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#status), this is the expected behavior when using the `status` event.

Note that `GITHUB_SHA` is documented as being the "Last commit on default branch"

In order to checkout the specific commit that the status event pertains to, please try the following:

```
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.sha }}
        fetch-depth: 0
```

More information about available event information can be found here:
https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#status
