### ISSUE TITLE
Using custom partition table alter the build folder access

### ISSUE THREAD

**Issue by DDANPEAL** [actions/checkout#1282]
I have the following action in my Github repository for esp32 project

```
name: Build firmware

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0 
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.3
          target: esp32
          
      - name: Get latest tag name
        id: version_value
        run: |
          tag=$(git describe --tags --abbrev=0 --match "v*")
          echo "value=${tag:1}" >> $GITHUB_OUTPUT
      - name: folder settings
        run: ls -l /
      
      - name: build folder settings
        run: ls -l build

      - name: Build and Export Binaries
        env:
          version_value: ${{ steps.version_value.outputs.value }} 
        run: |
          sudo chmod a+w build
          mv build/*.bin build/"${version_value}".bin
          cp build/*.bin ${{github.workspace}}/
          
        working-directory: ${{github.workspace}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ESP-IDF Binaries
          path: |
            *.bin
```
This works well and I can see the artifacts when using the default sdkconfig ( partition table only )

```
#
# Partition Table
#
CONFIG_PARTITION_TABLE_SINGLE_APP=y
# CONFIG_PARTITION_TABLE_TWO_OTA is not set
# CONFIG_PARTITION_TABLE_CUSTOM is not set
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv"
CONFIG_PARTITION_TABLE_FILENAME="partitions_singleapp.csv"
CONFIG_PARTITION_TABLE_OFFSET=0x8000
CONFIG_PARTITION_TABLE_MD5=y
# end of Partition Table

```

Changing the above part to 

```
#
# Partition Table
#
# CONFIG_PARTITION_TABLE_SINGLE_APP is not set
# CONFIG_PARTITION_TABLE_TWO_OTA is not set
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv"
CONFIG_PARTITION_TABLE_FILENAME="partitions.csv"
CONFIG_PARTITION_TABLE_OFFSET=0x8000
CONFIG_PARTITION_TABLE_MD5=y
# end of Partition Table
```

I get the following error

STEP : Build and Export Binaries
```
Run sudo chmod a+w build
  sudo chmod a+w build
  cp build/*.bin /home/runner/work/esp_idf_build_test/esp_idf_build_test/
  mv /home/runner/work/esp_idf_build_test/esp_idf_build_test/*.bin /home/runner/work/esp_idf_build_test/esp_idf_build_test/"${version_value}".bin
  shell: /usr/bin/bash -e {0}
  env:
    version_value: 0.0.2
mv: target '/home/runner/work/esp_idf_build_test/esp_idf_build_test/0.0.2.bin' is not a directory
Error: Process completed with exit code [1](https://github.com/DDANPEAL/esp_idf_build_test/actions/runs/4678519626/jobs/8287348320#step:7:1).

```

I'm not sure how further I can investigate this !
I check folders permission for when it fails or success and didn't see any changes
