### ISSUE TITLE
input default value   Unrecognized named-value

### ISSUE THREAD

**Issue by wanghaisheng** [actions/checkout#1294]
https://github.com/gpt-university/chatgpt-tweets-scraper-monitor/blob/main/.github/workflows/scrape.yml
```

on:
  workflow_dispatch:

    inputs:
      hashtags:
        description: 'hashtags，you can type like this:aaa or  aaa,bbb,ccc'
        type: enviroment
        required: True
        default: ${{ vars.KEYWORDS }}

      outdir:
        description: 'out dir '
        type: enviroment
        required: True      
        default: ${{ vars.OUT }}
```

```
The workflow is not valid. .github/workflows/scrape.yml (Line: 22, Col: 18): Unrecognized named-value: 'vars'. Located at position 1 within expression: vars.KEYWORDS .github/workflows/scrape.yml (Line: 28, Col: 18): Unrecognized named-value: 'vars'. Located at position 1 within expression: vars.OUT
```
![image](https://user-images.githubusercontent.com/2363295/232323993-f38209a2-1438-455d-91bb-15ced7792de3.png)
