### ISSUE TITLE
checkout@v3 can't remove previously created refs - permission denied error

### ISSUE THREAD

**Issue by cedrichak** [actions/checkout#1302]
I'm creating an action on a self hosted runner. actions/checkout returns an error when recreating refs and deleting my folders.

![Screenshot 2023-04-25 at 13 38 15](https://user-images.githubusercontent.com/127934248/234265111-4e27335b-9c3f-48c5-82de-b144a3501510.png)

This is the yaml file, i can't seem to get it to work. Does anyone have an idea on what's the issue?

```
name: CICD-testing

on:
  push:
    branches:
      - 'ci_cd_server'

jobs:
  algo-test:
    runs-on: self-hosted # ubuntu server
    permissions:
      actions: write
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: check for swimtraxx device
        run: |
          apt-get update
          cd testfiles
          ls /dev/ttyA*
```
