### ISSUE TITLE
Reuse/cache existing repository instead of always removing it?

### ISSUE THREAD

**Issue by oerp-odoo** [actions/checkout#1314]
I use repository that has some large submodules and it takes about 2 minutes to checkout, which is too long. Though I use self hosted runners and after each checkout, repository is kept there. I also use single repo for all projects, so there is always single repository being checked out.

So it would be much faster if it would just pull latest changes and not all repository all the time.

In checkout logs I see it always does this: `2023-05-12T06:35:36.9026578Z Deleting the contents of '/opt/runner/actions-runner/_work/repo/repo'`, before fetching.

I understand that there could be implications that fetched code might get corrupted, if not cleaned up properly, but it would still be nice to have this flexibility.

**Comment by ingomueller-net** [comment]
I am in a similar situation and think I just found a good solution. I also have a (relatively small) repository with a large submodule that took about 2 minutes to check out. I did **not** see any log entry about deleting, though. My solution is to cache the `.git` folder with the [cache action](https://github.com/actions/cache) like this:

```yaml

    - name: Cache git folder
      uses: actions/cache@v3
      with:
        path: checkout_path/.git
        key: git-folder

    - name: Checkout project
      uses: actions/checkout@v3
      with:
        path: checkout_path
        submodules: recursive
```

This brings the time down to about 10s plus another 10s or less for saving and restoring the cache.
