### ISSUE TITLE
Using checkout to clone repo from github into self hosted github 

### ISSUE THREAD

**Issue by N7WEra** [actions/checkout#1316]
I'm trying to use checkout to clone a repository from the official github site (github.com) into my corporate self-hosted github instances. Let's say for example our self-hosted github is git.example.com.

in my github action I have the following:
```
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: RANDOM_ORG/RANDOM_REPO
```

The checkout will search for this organisation and repository in the self-hosted github instead of in the offical github site (github.com).
I tried to change it from `RANDOM_ORG/RANDOM_REPO` to `https://github.com/RANDOM_ORG/RANDOM_REPO` but than the built complain `Invalid repository 'https://github.com/RANDOM_ORG/RANDOM_REPO'. Expected format {owner}/{repo}.`.

Is there a way to clone from the official github into self-hosted github using checkout?
