### ISSUE TITLE
The process '/usr/bin/git' failed with exit code 1

### ISSUE THREAD

**Issue by agluszak** [actions/checkout#1326]
For some reason git started failing on checkout after I enabled [auto-commiting changes made by prettier ](https://github.com/creyD/prettier_action)

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/update/jsoniter-scala-core-2.23.0*:refs/remotes/origin/update/jsoniter-scala-core-2.23.0* +refs/tags/update/jsoniter-scala-core-2.23.0*:refs/tags/update/jsoniter-scala-core-2.23.0*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 20 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/update/jsoniter-scala-core-2.23.0*:refs/remotes/origin/update/jsoniter-scala-core-2.23.0* +refs/tags/update/jsoniter-scala-core-2.23.0*:refs/tags/update/jsoniter-scala-core-2.23.0*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/update/jsoniter-scala-core-2.23.0*:refs/remotes/origin/update/jsoniter-scala-core-2.23.0* +refs/tags/update/jsoniter-scala-core-2.23.0*:refs/tags/update/jsoniter-scala-core-2.23.0*
```

See: https://github.com/build-server-protocol/build-server-protocol/actions/runs/5003971723/jobs/8966282180#step:2:129

**Comment by qxmips** [comment]
I have same issue.

**Comment by cwg50805** [comment]
Same :(

**Comment by guychienll** [comment]
I have same issue too !

**Comment by ArjunDandagi** [comment]
BUMP:
we are seeing the same issue in our actions runner now

**Comment by polytopes-design** [comment]
Same

**Comment by haooliveira84** [comment]
same here :(

**Comment by kenorb** [comment]
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/v2.000-dev*:refs/remotes/origin/v2.000-dev* +refs/tags/v2.000-dev*:refs/tags/v2.000-dev*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 16 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/v2.000-dev*:refs/remotes/origin/v2.000-dev* +refs/tags/v2.000-dev*:refs/tags/v2.000-dev*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/v2.000-dev*:refs/remotes/origin/v2.000-dev* +refs/tags/v2.000-dev*:refs/tags/v2.000-dev*
  Error: The process '/usr/bin/git' failed with exit code 1
```

The same error after dozens of re-runs.

Weird, because it was working couple of months before.

**Comment by hieutomra** [comment]
Same error and symptom for us.
We are running with self-hosted runner. I tried to run the same command as the runner would and with `export GIT_TRACE=1`
```
[...]
09:45:10.394902 run-command.c:654       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/REDACTED
09:45:10.395717 git.c:745               trace: exec: git-remote-https origin https://github.com/REDACTED
09:45:10.395736 run-command.c:654       trace: run_command: git-remote-https origin https://github.com/REDACTED
Username for 'https://github.com': foo
Password for 'https://foo@github.com': 
09:45:22.693484 run-command.c:654       trace: run_command: git maintenance run --auto --no-quiet
09:45:22.694565 git.c:458               trace: built-in: git maintenance run --auto --no-quiet

$ echo $? 
1 
```

**Comment by ElRojo** [comment]
I'm also having this issue. The ref is a tag and it works on some tags, but not on others.

**Comment by asombaty** [comment]
I am having this issue for the past week now.

**Comment by Olfi01** [comment]
I had the same problem and fixed it. In my case, the branch was still called master, but I was trying to checkout main.

**Comment by george-gca** [comment]
I am currently facing this issue with two actions:

<details>
 <summary>Prettier action</summary>

[Failed action](https://github.com/levxyca/diciotech/actions/runs/12149561326/job/33880496829?pr=267)

```yml
name: Prettier

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Run Prettier
        uses: AbdulRehman-1/pr-prettier@initial
        with:
          only_changed: true
          prettier_options: --write **/*.{css,html,js,json,liquid,md,scss,yaml,yml}
```

</details>

<details>
 <summary>format my data files</summary>

[Failed action](https://github.com/levxyca/diciotech/actions/runs/12149561325/job/33880496786?pr=267)

```yml
name: Sort data files

on:
  push:
    branches:
      - main
    paths:
      - "_data/**"

  pull_request:
    paths:
      - "_data/**"

  workflow_dispatch:

jobs:
  sort-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Get changed data files
        id: changed-data
        uses: tj-actions/changed-files@v45.0.4
        with:
          files: _data/**.yml

      - name: Setup Python
        if: steps.changed-data.outputs.any_changed == 'true'
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.12"

      - name: Sort data files
        if: steps.changed-data.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-data.outputs.all_changed_files }}
        run: |
          for file in $ALL_CHANGED_FILES; do
            echo "Formatting $file"
            python3 format_data.py -f $file
          done

      # commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5.0.1
        if: steps.changed-data.outputs.any_changed == 'true'
        with:
          commit_message: Sort data files

```
</details>
