### ISSUE TITLE
Sparse checkout seems to be triggered when not intended

### ISSUE THREAD

**Issue by bzbarsky-apple** [actions/checkout#1378]
We have some GitHub CI that uses the checkout action like so:
```
            - uses: Wandalen/wretry.action@v1.0.36
              name: Checkout
              with:
                  action: actions/checkout@v3
                  with: |
                      submodules: true
                      token: ${{ github.token }}
                  attempt_limit: 3
                  attempt_delay: 2000
```

As of this morning all checkouts stopped working with this error:
```
Error: fatal: --filter can only be used when extensions.partialClone is set
```

You can compare a failing run at https://github.com/project-chip/connectedhomeip/actions/runs/5223466703/jobs/9430364364 with a passing run from a few hours earlier at https://github.com/project-chip/connectedhomeip/actions/runs/5222975743/jobs/9429182655.

The failing run is running this git command:
```
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --filter=blob:none --depth=1 origin +136a312c1cd14c44c6187211b9e56365abc168eb:refs/remotes/pull/27177/merge
```

while the passing one ran this one:
```
 /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +afef8aa2c4add14255a80d46cb44c8380326c934:refs/remotes/pull/27157/merge
```

note the extra `--filter=blob:none` that is present in the failing command.  This is presumably a change from https://github.com/actions/checkout/pull/1369.  I do see that that bit is conditoned on `settings.sparseCheckout` in that PR, but we are not setting `sparseCheckout` to anything anywhere in our repository...
