### ISSUE TITLE
git-lfs cannot be found in a self-hosted runner

### ISSUE THREAD

**Issue by fengwang** [actions/checkout#1401]
Steps to reproduce
1. Install  actions-runner-linux-x64-2.299.2 in Archlinux/Ubuntu1804, setup token and service
2. Create an action script in folder `.github/workflows`  including

```yaml
name: CI

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]


jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: cleanup
        run: |
          echo Will clean from here.
          echo $PATH
          whoami
          echo Clean is skipped.
          which git
          uname -a
          which apt
          echo $PATH

      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: 'recursive'
          token: ${{ secrets.ACCESS_TOKEN }}

        env:
          GIT_CURL_VERBOSE: '1'
          GIT_TRACE: '1'
```

I encountered build error with message 

```
[build](https://github.xxxxxxxx.com/xxxxxx/XXXXXXXXXX/actions/runs/396556/jobs/633216#step:3:23)
Unable to locate executable file: git-lfs. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

The `cleanup` step produces information like this:

```
Run echo Will clean from here.
Will clean from here.
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
azureuser
Clean is skipped.
/usr/bin/git
Linux AIC-GithubActionsRunner 5.[1](https://github.hexagon.com/hxgn-ih-tc/AIC-GEO-ProjectKandinsky2/actions/runs/396556/jobs/633216#step:2:1)5.0-1033-azure #40~20.04.1-Ubuntu SMP Tue Jan 24 [16](https://github.hexagon.com/hxgn-ih-tc/AIC-GEO-ProjectKandinsky2/actions/runs/396556/jobs/633216#step:2:17):06:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/apt
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

The checkout step produces error information

```
Run actions/checkout@v3
Syncing repository: XXXXXXXX/xxxxxxxx
Getting Git version info
  Working directory is '/home/azureuser/actions-runner/_work/XXXXXXXX/XXXXXXXX'
  /usr/bin/git version
  [20](https://github.xxxxxxxxxx.com/xxxxxx/XXXXXXXX/actions/runs/396556/jobs/633216#step:3:21):09:09.676113 git.c:439               trace: built-in: git version
  git version 2.25.1
  Error: Unable to locate executable file: git-lfs. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
Note: 
1. `XXXXXXX` and `xxxxxx` are sensitive information get masked
2. `git-lfs` is already installed and configured in the host system (ArchLinux/Ubuntu 1804)

**Comment by jbelien** [comment]
To avoid this issue, here is the step I've added **before** the `actions/checkout`:
```yaml
- name: Initialize LFS
  run: |
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    sudo apt-get install git-lfs
```

**Comment by jpr5** [comment]
> To avoid this issue, here is the step I've added **before** the `actions/checkout`:
> 
> ```yaml
> - name: Initialize LFS
>   run: |
>     curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
>     sudo apt-get install git-lfs
> ```

How does that even work?  The self-runner I'm using on Linux doesn't have `sudo` installed.  And it appears stuff doesn't run as root so you can't call `apt-get` directly.  How'd that work for you @jbelien ?

**Comment by agucollado** [comment]
In my case I'm using a self hosted runner, which doesn't include git cli, so adding this action before the checkout solves the problem.
https://github.com/dev-hanz-ops/install-gh-cli-action

```
- name: Install GH CLI
  uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
  with:
    gh-cli-version: 2.32.0 # optional, see action.yml for current default
```

**Comment by rowanG077** [comment]
For those using nixos, I had to add `git-lfs` to `extraPackages` even though it is installed locally on the system:

```
  services.github-runners = {
    some_runner = {
      enable = true;
      url = ....;
      tokenFile = ...;
      replace = true;
      extraPackages = [ pkgs.git-lfs ];
    };
  };
```

**Comment by dminca** [comment]
> To avoid this issue, here is the step I've added **before** the `actions/checkout`:
> 
> - name: Initialize LFS
>   run: |
>     curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
>     sudo apt-get install git-lfs

This worked perfectly fine for me

```sh
Preparing to unpack .../git-lfs_3.7.1_amd64.deb ...
Unpacking git-lfs (3.7.1) ...
Setting up git-lfs (3.7.1) ...
Git LFS initialized.
Run actions/checkout@v6
  with:
    lfs: true
    repository: sampleorg/samplerepo-docs
    token: ***
    ssh-strict: true
    ssh-user: git
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    show-progress: true
    submodules: false
    set-safe-directory: true
Syncing repository: sampleorg/samplerepo-docs
Getting Git version info
Temporarily overriding HOME='/home/runner/_work/_temp/00000000-0000-0000-0000-000000000000' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/_work/samplerepo-docs/samplerepo-docs
Deleting the contents of '/home/runner/_work/samplerepo-docs/samplerepo-docs'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
/usr/bin/git lfs install --local
Updated Git hooks.
Git LFS initialized.
Fetching the repository
Determining the checkout info
Fetching LFS objects
/usr/bin/git sparse-checkout disable
/usr/bin/git config --local --unset-all extensions.worktreeConfig
Checking out the ref
/usr/bin/git log -1 --format=%H
efdbee09cea6d80a2588170df3b286eeea691e10

```

**Comment by sergii-auctane** [comment]
This also works:
```
    steps:
      - name: Install LFS
        run: |
          sudo apt-get update && sudo apt-get install git-lfs   
```
But this should solve it for everyone: https://github.com/actions/runner/pull/4259
