### ISSUE TITLE
How to use "show-progress"?

### ISSUE THREAD

**Issue by koppor** [actions/checkout#1446]
README.md says, `show-progress` is an option:

![grafik](https://github.com/actions/checkout/assets/1366654/36c0226b-fdfa-45b2-8bbf-ce785c3c1cd4)

```yaml
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: 'false'
          show-progress: 'false'
```

Leads to:

> Warning: Unexpected input(s) 'show-progress', valid inputs are ['repository', 'ref', 'token', 'ssh-key', 'ssh-known-hosts', 'ssh-strict', 'persist-credentials', 'path', 'clean', 'sparse-checkout', 'sparse-checkout-cone-mode', 'fetch-depth', 'fetch-tags', 'lfs', 'submodules', 'set-safe-directory', 'github-server-url']

What am I doing wrong?

**Comment by dwdraju** [comment]
I faced same issue. The warning appears on "Post Checkout" phase.

**Comment by patrick-stephens** [comment]
I don't think that option is in the v3 version, it doesn't seem to appear in the docs anyway for 3.6.0: https://github.com/actions/checkout/tree/v3.6.0

Have you tried using the latest v4 version?

**Comment by koppor** [comment]
As noted in the referenced issue, the current doc on main is V3 - and shows show-progress...

https://github.com/actions/checkout/blob/3df4ab11eba7bda6032a0b82a6bb43b11571feac/README.md?plain=1#L96

**Comment by koppor** [comment]
Interestingly, this was released with version v4: https://github.com/actions/checkout/pull/1067

I will close this issue as the README.md will surely be updated the next hours.

**Comment by dwdraju** [comment]
Confirmed this works in v4 ✅ 
```
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
```
