### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')

### ISSUE THREAD

**Issue by kevin-brashears-fhr** [actions/checkout#1464]
Upgraded to v4 from v3 and am getting errors with the default setup:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
```
I am running on a self hosted Windows runner that does not have any sort of NodeJS installed.

This worked fine with the default setup for actions checkout on v3:
```
jobs:
  job:
    runs-on: [self-hosted, selfHostedTagName]
    steps:
      - uses: actions/checkout@v4
```
![image](https://github.com/actions/checkout/assets/103589703/04c6f789-39f6-43db-bc6e-ad65b05be2fc)
