### ISSUE TITLE
checkout@v4 doesnt work inside container action

### ISSUE THREAD

**Issue by copdips** [actions/checkout#1474]
v4 doesnt work, but it's working for v3.

```yml
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: node:14.16
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
```

Error message:

```console
Run actions/checkout@v4
/usr/bin/docker exec  7cbdf08ca47fe2456a9002981cd5b884c8e98459104cbf71a6412df305a5614c sh -c "cat /etc/*release | grep ^ID"
/__e/node[20](https://github.com/pernod-ricard-coe-data/cicd-test/actions/runs/6198845372/job/16830116625#step:4:21)/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
```
