### ISSUE TITLE
Fetching an empty repository fails

### ISSUE THREAD

**Issue by roblabla** [actions/checkout#1477]
Currently, the action will fail when trying to fetch an empty repository. This is because `git fetch origin` on an empty repository causes `git` to (silently) return 1, which `actions/checkout` treats like an error.

My expectation is that `actions/checkout` on an empty repo should behave similarly to `git clone`-ing that repository - it should lead to having an empty repository created, with the origin already setup.

For context: I'm trying to make a simple workflow that's meant to synchronize a reverse engineering database (ghidra) with a local git history. To achieve this, I have a repo that contains all the scripts necessary for the task, and a separate repo containing only the git history. When we create that separate repo, it will start as a clean canvas without any history, so the "managing" repo will fail to try to clone it using `actions/checkout`.

<details><summary>Here are the full logs: (taken from [this run](https://github.com/roblabla/th06/actions/runs/6210021951/job/16857890291)).</summary>

```
Run actions/checkout@v4
  with:
    repository: happyhavoc/th06-re
    path: th06-re
    ssh-key: ***
    ref: main
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    show-progress: true
    lfs: false
    submodules: false
    set-safe-directory: true
Syncing repository: happyhavoc/th06-re
Getting Git version info
  Working directory is '/home/runner/work/th06/th06/th06-re'
  /usr/bin/git version
  git version 2.42.0
Temporarily overriding HOME='/home/runner/work/_temp/c3ae8c56-46c7-42cb-af36-676f5458ce37' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/th06/th06/th06-re
Initializing the repository
  /usr/bin/git init /home/runner/work/th06/th06/th06-re
  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint: 
  hint: 	git config --global init.defaultBranch <name>
  hint: 
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint: 
  hint: 	git branch -m <name>
  Initialized empty Git repository in /home/runner/work/th06/th06/th06-re/.git/
  /usr/bin/git remote add origin git@github.com:happyhavoc/th06-re.git
Disabling automatic garbage collection
  /usr/bin/git config --local gc.auto 0
Setting up auth
  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
  Temporarily overriding GIT_SSH_COMMAND="/usr/bin/ssh" -i "$RUNNER_TEMP/d12075fd-27f6-41a8-aa6f-a2e4eaad121f" -o StrictHostKeyChecking=yes -o CheckHostIP=no -o "UserKnownHostsFile=$RUNNER_TEMP/d12075fd-27f6-41a8-aa6f-a2e4eaad121f_known_hosts"
  /usr/bin/git config --local core.sshCommand "/usr/bin/ssh" -i "$RUNNER_TEMP/d12075fd-27f6-41a8-aa6f-a2e4eaad121f" -o StrictHostKeyChecking=yes -o CheckHostIP=no -o "UserKnownHostsFile=$RUNNER_TEMP/d12075fd-27f6-41a8-aa6f-a2e4eaad121f_known_hosts"
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 18 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 16 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
  Error: The process '/usr/bin/git' failed with exit code 1
```

</details>

<details><summary>And here's the YAML</summary>

```yaml
name: Export Ghidra Database

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'happyhavoc/th06-re'
        path: th06-re
        ssh-key: ${{ secrets.GHIDRA_SSH_AUTH }}
        ref: main
    - name: Get ghidra
      run: |
        curl -L https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.3_build/ghidra_10.3.3_PUBLIC_20230829.zip -o /tmp/ghidra.zip
        unzip -d /tmp /tmp/ghidra.zip
        echo /tmp/ghidra_*/support >> $GITHUB_PATH
    - name: Export ghidra
      run: |
        echo "$GHIDRA_SSH_AUTH" > ssh_key
        python script/export_ghidra_database.py --user-mappings config/ghidra-user-maps.toml --username github-action --ssh-key ssh_key --program th06_102h.exe 'ghidra://roblab.la/Touhou 06' th06-re
      env: # Or as an environment variable
        GHIDRA_SSH_AUTH: ${{ secrets.GHIDRA_SSH_AUTH }}
    - name: Push
      run: git push origin HEAD
```

</details>
