### ISSUE TITLE
hugo .GitInfo.Date returns the current date when the repo is cloned via v2

### ISSUE THREAD

**Issue by jasikpark** [actions/checkout#149]
I'm using this action for testing my `hugo` site with `percy`. When cloning with `v2`, the `hugo` mechanism for getting the last modified state for articles doesn't work since that information seems to be set to the current date?

Using `v1` of `checkout` seems to solve my problem, but I would like to figure out whether I can configure `v2` to work.

```yml
name: Percy
on:
  push:
    branches:
    - "master"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          image: latest-ext
      - name: Percy
        uses: percy/snapshot-action@v0.1.1
        with:
          build-directory: "public"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```

**Comment by jasikpark** [comment]
ok, so switching to 

```yml
uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

solved my problem. thanks!!
