### ISSUE TITLE
v2 doesn't work with alpine containers

### ISSUE THREAD

**Issue by mhumeSF** [actions/checkout#151]
.github/workflows/main.yml
```
on: [push]

jobs:
  container-job:
    runs-on: self-hosted

    container:
      image: alpine/git

    steps:
      - uses: actions/checkout@v2
```

When running this action, I get an error during the checkout process.
```
Run actions/checkout@v2
/usr/bin/docker exec  37cf0b426abd3ab0f4dcf1843b8a76349feeaa81c59390eada6479105cef7851 sh -c "cat /etc/*release | grep ^ID"
Container distribution is alpine. Running JavaScript Action with external tool: node12_alpine
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/__e/node12_alpine/bin/node\": stat /__e/node12_alpine/bin/node: no such file or directory": unknown
##[error]Node run failed with exit code 126
```
