### ISSUE TITLE
Using `ref` and `fetch-depth: 0` assumes that `ref` is either branch or tag

### ISSUE THREAD

**Issue by jbergstroem** [actions/checkout#1515]
I'm passing a commit to `ref` instead of a branch or tag. When using `fetch-depth: 0` in conjunction to this, I run into a checkout error (output from job):

```bash
/usr/bin/git branch --list --remote origin/cfe42d2a
/usr/bin/git tag --list cfe42d2a
Error: A branch or tag with the name 'cfe42d2a' could not be found
```

#### Debug info

- `Download action repository 'actions/checkout@v4' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)`
- This job is invoked via `workflow_call` where an input is what git ref to check out.
- Job:
  ```yaml
  e2e-test:
    name: Run E2E tests
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref != '' && inputs.ref || github.sha }}
  ```

..looking at the code, I can't help but feeling that the case is not covered?
https://github.com/actions/checkout/blob/b4ffde65f46336ab88eb53be808477a3936bae11/src/ref-helper.ts#L29-L60

..finally, if I skip passing `fetch-depth: 0`, I run into this issue: https://github.com/actions/checkout/issues/1313
