### ISSUE TITLE
v4 forces use of git@github.com even when no `ssh-key` are provided

### ISSUE THREAD

**Issue by sebsto** [actions/checkout#1518]
When using `actions/checkout@v4`, the action adds the following lines to `~/.gitconfig` even when no `ssh-key` are provided.

This breaks the global git config and prevents the pipeline to complete.

```
[url "ssh://git@github.com"]
	insteadOf = https://github.com
[gc]
	auto = 0
```

Here is my workflow definition :

```yaml
...

jobs:
  pre-build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

...
```

Reverting to `actions/checkout@v3` solves the issue.  v3 does not add the HTTPS to SSH redirect to the global git config.

I think I trace it down to [this line of code](https://github.com/actions/checkout/blob/ec3a7ce113134d7a93b817d10a8272cb61118579/src/git-auth-helper.ts#L124) that does not work as expected 

I think this might be related to https://github.com/actions/checkout/issues/650
