### ISSUE TITLE
Prevent "Deleting the contents of ..."

### ISSUE THREAD

**Issue by steven-prybylynskyi** [actions/checkout#1525]
I have a very basic scenario.

```yml
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          token: ${{ ... }}

      - name: Checkout single file from another repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          repository: company/repo-name
          ref: main
          token: ${{ ... }}
          sparse-checkout: scripts/some-script.ts
          sparse-checkout-cone-mode: false
```

And in the output (and using `ls`) I can see that content of the repo is always deleted

```
Run actions/checkout@v4
Syncing repository: company/repo-name
...
Deleting the contents of '/home/runner/work/repo-name/repo-name'
```

I believe it is a bug or design flaw for this action and missing documentation on this behaviour.

**Comment by steven-prybylynskyi** [comment]
Ok, it looks like one must use `path` to put the content of the repo to another folder.

But that creates the `.git` folder inside that folder and there's also a need to use `mv` to move the example script up a level since the script looks have code that looks at relative path `../`

**Comment by steven-prybylynskyi** [comment]
I can do something like this:

```
      - name: Checkout single file
        run: |
          git remote add some-repo https://github.com/company/some-repo.git
          git fetch some-repo main
          git checkout some-repo/main -- scripts/generateActionsDoc.ts
```

This works perfectly

That interacts with the `.git` folder in the repository where the GitHub Actions runner is executing the workflow, but that's not modifying the current branch or the working directory. The `git checkout` command checks out only the specified file into the working directory, leveraging the information stored in the existing .git folder.

**Comment by moshe-azaria-sage** [comment]
[This is](https://github.com/actions/checkout?tab=readme-ov-file#Checkout-multiple-repos-side-by-side) how to do it according to the documentation:

```
- name: Checkout
  uses: actions/checkout@v4
  with:
    path: main

- name: Checkout private tools
  uses: actions/checkout@v4
  with:
    repository: my-org/my-private-tools
    token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
    path: my-tools
```

This example is for private repos. for public you don't need the `token`.

**Comment by shinebayar-g** [comment]
It looks like it happens when the second checkout tries to use the root directory.

Instead of this

```yaml
- name: Checkout lib
  uses: actions/checkout@v4
  with:
    repository: owner/repo
    path: lib

- name: Checkout
  uses: actions/checkout@v4
```

do this

```yaml
- name: Checkout
  uses: actions/checkout@v4

- name: Checkout lib
  uses: actions/checkout@v4
  with:
    repository: owner/repo
    path: lib
```

**Comment by steven-pribilinskiy** [comment]
That's exactly the case I was trying to achieve

```
- name: Checkout
  uses: actions/checkout@v4

- name: Checkout lib
  uses: actions/checkout@v4
  with:
    repository: owner/second-repo
    path: second-repo
```

The problem with this "official approach" is that this creates the `second-repo` folder and you might need to do the following if the temporary folder `second-repo` is not suitable:

- move files/folders to the root folder
- delete content of the git repo

So you are ending with two steps

```
- name: Checkout lib
  uses: actions/checkout@v4
  with:
    repository: owner/second-repo
    path: second-repo

- name: Move my second-repo files
  run: | 
     mv -r !(.*|*.git) ..
     rm -rf second-repo
```

**Explanation:**

  • `mv -r` is an invalid combination of options. The correct option for moving directories is -R or --recursive.
  • `!(.*|*.git)` is a shell glob pattern that matches all files and directories except for those starting with a dot (.) or ending with .git.
  • `..` represents the parent directory.
  • `rmdir <folder_name>` removes the specified directory if it is empty.
    • `<folder_name>` should be replaced with the actual name of the folder you want to remove.


So there is this proposed hacky way to use a named remote
```
      - name: Checkout single file
        run: |
          git remote add some-repo https://github.com/company/some-repo.git
          git fetch some-repo main
          git checkout some-repo/main -- scripts/generateActionsDoc.
```

**Explanation:**

- `git remote add some-repo ...`  adds a new remote repository named `some-repo` with the specified git repo URL
- `git fetch some-repo main` fetches the latest changes from the `main` branch of the `some-repo` remote repository.
- `git checkout some-repo/main -- scripts/generate.ts`: Checks out the file `scripts/generate.ts` from the main branch of the `some-repo` remote repository and updates your working directory with it. 
 
The best part, is that this does not switch branches and it only updates the specified file.

Now this approach has its own flaws of course when it comes to downloading folders. It would look something like that

```
git sparse-checkout init --cone
git sparse-checkout set <folder-path>
git remote add some-repo https://github.com/company/some-repo.git
git fetch some-repo
git checkout some-repo/main
```

So for more complex situation a combination of `actions/checkout@v4` with bash `mv -r ...` is preferable.
