### ISSUE TITLE
Encounter Error /home/runner/work/_temp/...: app: No such file or directory During GitHub Actions Workflow

### ISSUE THREAD

**Issue by pepqymumpuni** [actions/checkout#1535]
Hi GitHub Support Team,

I hope this message finds you well. I'm reaching out to report a recurring issue I've encountered with my GitHub Actions workflow. During the execution of a GitHub Actions workflow in my repository, I'm consistently receiving the following error:

```
/home/runner/work/_temp/f1222d53-b743-408e-9f01-001a2cf124e2.sh: line 33: app: No such file or directory
Error: Process completed with exit code 1.
```

main.yaml
```
  E2ETestSPVCockpit:
    needs: [FormatingStandart]
    if: github.event.inputs.squad == 'spvcockpit'
    name: E2E test for squad spvcockpit
    environment: SIT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Cypress environment from GitHub Secret
        run: echo "${{ secrets.CYPRESS_ENV }}" >> cypress.env.json
      - name: Extract Cypress environment variables
        run: |
          echo "CYPRESS_PROJECT_ID=$(jq -r '.["cypress-cloud"]["spv-project-id"]' < cypress.env.json)" >> $GITHUB_ENV
          echo "CYPRESS_RECORD_KEY=$(jq -r '.["cypress-cloud"]["spv-record-key"]' < cypress.env.json)" >> $GITHUB_ENV
      - name: Cypress run for squad spvcockpit
        uses: cypress-io/github-action@v6
        with:
          command: npm run run:e2e:spvcockpit -- --record --key ${{ env.CYPRESS_RECORD_KEY }}
          browser: chrome
        env:
          CYPRESS_PROJECT_ID: ${{ env.CYPRESS_PROJECT_ID }}
```

And i put my cypress.env.json to github secrets

![Uploading Screen Shot 2023-11-07 at 19.50.21.png…]()
