### ISSUE TITLE
Not able to checkout private repositories

### ISSUE THREAD

**Issue by blade2005** [actions/checkout#1555]
Getting this error on checking out my repo in actions.
>  Error: fatal: repository 'https://github.com/<redacted>/<redacted>/' not found

I found an old issue about this such as #985 #983 #686 #417 

Is github having issues with actions right now?

This started last night for me.

Edit 1:
Here is one section of my workflow
```yaml
name: Default

on: push
permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  spell-check:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: ${{ vars.TASK_VERSION}}
      - run: task spellcheck
```

Edit 2: After ripping more out of my pr and reconstructing it, the workflow actually breaks because of the permissions.

Edit 3:
per the directions on [Setting up github oidc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings) the  contents is required because perms when you add something it blows away the defaults but it's not documented on the checkout anywhere what permissions are needed. 
```yaml
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read
```
