### ISSUE TITLE
checkout@v4 occasionally stuck on checkout

### ISSUE THREAD

**Issue by jaronoff97** [actions/checkout#1559]
Hello! I have a fairly straightforward use case, but I'm seeing a checkout that takes far longer than it should. Usually my time is under 10s, but for this run it was over 10 minutes!
```
  <jobname>:
    name: <name>
    if: github.event.pull_request.draft == false
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
```

<img width="1120" alt="Screenshot 2023-11-28 at 8 47 47 PM" src="https://github.com/actions/checkout/assets/10070047/0ac675ea-28c6-4a52-a9a0-4673bf262e4c">

This has now happened in three separate instances in three different jobs. Please let me know if there's any extra context i can provide.
