### ISSUE TITLE
Unable to resolve action `actions/checkout@v4`, unable to find version `v4`

### ISSUE THREAD

**Issue by strawberry1234365** [actions/checkout#1562]
I am trying to utilize the new Checkout multiple repos (private) feature with actions/checkout@v4 however I am getting this error message when I try to run it:

Error: Unable to resolve action `actions/checkout@v4`, unable to find version `v4`

I am currently using a self-hosted runner and am wondering if that is where the issue is stemming from? Any help/suggestions would be appreciated!

**Comment by guru-desh** [comment]
I run into the same issue as well on a self-hosted runner

**Comment by wismoyo** [comment]
Same issue here..

**Comment by sitinur4** [comment]
I run into the same issue as well ( Jan 24 2025)

**Comment by Livius90** [comment]
Same error for `actions/configure-pages`:
https://github.com/actions/configure-pages/issues/176

**Comment by zektorum** [comment]
Same issue with GitHub-hosted runner
```yml
name: Build

on: [push]

env:
  PYTHON_VERSION: 3.13

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4.2.2
      - uses: actions/setup-python@5.3.0
        with:
          python-version: $PYTHON_VERSION
      - run: python -m build
```

```
Error: Unable to resolve action `actions/checkout@4.2.2`, unable to find version `4.2.2`. Unable to resolve action `actions/setup-python@5.3.0`, unable to find version `5.3.0`
```

**Comment by damianarata** [comment]
I run into the same issue as well ( Mar 10 2025)

**Comment by srujan-b** [comment]
same here

**Comment by jeevesbarton** [comment]
same here

**Comment by scottb-remitly** [comment]
Same here Apr 2025

**Comment by dniald** [comment]
I'm also facing the same issue. Any workaround on this?

<img width="716" alt="Image" src="https://github.com/user-attachments/assets/3017f270-013c-4967-b02c-7fa2e25e0dec" />

<img width="646" alt="Image" src="https://github.com/user-attachments/assets/90369296-0330-491c-80ed-3d237131652e" />

**Comment by JuroOravec** [comment]
I think I got the same error as @Scality-EmerikNicole 

```
Current runner version: '2.324.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: None
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: No MediaTypeFormatter is available to read an object of type 'ActionDownloadInfoResponseCollection' from content with media type 'text/plain'.
Retrying in 1[2](https://github.com/django-components/django-components/actions/runs/15250264865/job/42885352277?pr=1214#step:1:2).941 seconds
Error: Missing download info for actions/checkout@v4
```

See https://github.com/django-components/django-components/actions/runs/15250264865/job/42885352277?pr=1214

**Comment by NicolasGuary** [comment]
Indeed, some GitHub APIs are down it seems : https://www.githubstatus.com/

**Comment by vinayak0035** [comment]
worked for me just

**Comment by ngocdd** [comment]
I got the same issue now

**Comment by miversen** [comment]
I also experience the problem

**Comment by miversen** [comment]
I manage to solve the problem and it turned out to not be an issue with actions/checkout@v4 itself. In my case, the issue was a broken third-party action elsewhere in the workflow. GitHub resolves all actions up front, so if any action can't be fetched, even checkout fails.

To debug, I used a minimal workflow:

```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
```

✅ That worked. I then added steps back one at a time until it broke — and found the culprit.
