### ISSUE TITLE
workflow action with submodule checkout failing

### ISSUE THREAD

**Issue by sfelsheim** [actions/checkout#1564]
Hello,  I am running GitHub enterprise, but have to use my personal GitHub account to post this issue. 

I am trying to create a workflow action to build a dotnet core solution.

```
name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore PlanService/PDS.sln
    - name: Build
      run: dotnet build PlanService/PDS.sln --no-restore
```
When it executes, it fails saying the submodule repository does not exist (it does) 

![image](https://github.com/actions/checkout/assets/12235090/608caee5-1c7e-44b9-94f4-eb4c734e8bff)

Any help would be appreciated.  

Steve
