### ISSUE TITLE
Using on Raspberry Pi 4 arm cause "GLIBCXX_3.4.26 not found" 

### ISSUE THREAD

**Issue by hannesa2** [actions/checkout#1565]
Hi,
I use it on a self hosted Linux arm runner (Raspberry Pi 4) 
```

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
```

and run into 
`
/home/github/actions-runner/externals/node20/bin/node: /lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/github/actions-runner/externals/node20/bin/node)`

as workaround I use `actions/checkout@v3` This works properly.

Do you have a hint how to solve v4 on my Raspberry ?
