### ISSUE TITLE
doc: Tags forks and pull-requests

### ISSUE THREAD

**Issue by LecrisUT** [actions/checkout#1574]
The documentation is rather unclear how these features interact with each other. Let's assume we have the following action:
```yaml
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: git describe --tags
```

The ambiguity arises from, where do the tags come from: the target repo or the fork, or both? How do we control to be one or the other?
