### ISSUE TITLE
Can I check out a new branch?

### ISSUE THREAD

**Issue by zkytony** [actions/checkout#1657]
Is it possible to checkout a ref that does not exist (such as a new branch)?
```
    - uses: actions/checkout@v4
      with:
        ref: "new-branch"
```

**Comment by cory-miller** [comment]
That's not what this action is meant for, but you could do something like this if you need it:

```
    - uses: actions/checkout@v4
      with:
        ref: "existing-branch"
    - run: |
        git checkout -b new-branch
```
