### ISSUE TITLE
Why don't you write the default value in the `description` in the `inputs` options?

### ISSUE THREAD

**Issue by minsoo-web** [actions/checkout#1659]
### Background 

I didn't realize that the default value of the `fetch-depth` option is `1` until I looked in the `README` 
Of course, user should read the documentation before using it, but if the default value was included in the `description`, I could have solved this problem with a tooltip that appears on hover.

<img width="655" alt="image" src="https://github.com/actions/checkout/assets/57122180/c8f7a555-a8c5-4e83-9cdd-d4bb4808d2cb">

### Suggestion 

Why not include a default value in the description?

```yml
fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags. Default value is 1'
    default: 1
```

like this?
