### ISSUE TITLE
Failing to install node modules from private repos [using urls]

### ISSUE THREAD

**Issue by jsg2021** [actions/checkout#166]
I'm trying to setup a workflow that simply runs npm install/test. I'm having problems with projects that have private github urls. I tried settng `token` with a PAT that has full repo scopes... no luck. Any insight? npm issues `git clone` commands... by the description w/ persisting the token, I'd expect this to work😕 

```json
{
  "name": "foo",
  "dependencies": {
    "some-private-module": "SomeAcmeCo/some-private-repo"
  }
}
```

**Comment by jsg2021** [comment]
I think I found the issue.  The docs tell me to use a PAT, but git's extraheader configs want a base64'd "username:pat".  I copied the command in the action's error trying to clone the https private repo, and it failed the same way.

I ran the command that this action uses to setup the persisted auth (`git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***`) and still failed. When I updated the value for token to be the base64 name/token combo it worked... but the action broke. 😕

**Comment by ericsciple** [comment]
The token is persisted in the local git config so authenticated commands (fetch/push) will work.

If you are running git clone, then git creates a separate .git folder on disk (now a different local git config).

**Comment by jsg2021** [comment]
Yeah, I switched local to global. Still having issues.

**Comment by ericsciple** [comment]
The token is added to the local git config using [this code](https://github.com/actions/checkout/blob/096e9277500008410ac4dd98a7bb0d9052330de8/src/git-source-provider.ts#L264)

**Comment by jsg2021** [comment]
i’m wondering it `x-access-token` as the username portion is somehow not working with clone/ls-remote commands that npm is issuing. 😕 still investigating...

**Comment by jsg2021** [comment]
nm, it's just the scope. It needs to be global.
If I add a step before `npm install` that does:
```
auth_header="$(git config --local --get http.https://github.com/.extraheader)"
git config --global http.https\:\/\/github.com\/.extraheader "$auth_header"
git config --local --unset-all http.https\:\/\/github.com\/.extraheader
```

My action passes.

**Comment by jsg2021** [comment]
assuming actions have an exclusive lock on a container (no other actions can run on it) while running...
Can this action grow a global flag?

**Comment by jsg2021** [comment]
I've made a proposal PR. Thoughts?

**Comment by ericsciple** [comment]
@jsg2021 a submodule input has been added now. I merged to master, try it out and let me know. Collecting feedback and will update the `v2` tag next week.

**Comment by jsg2021** [comment]
@ericsciple Sorry, master is not working for my action. My PR does work... but after reading your work on the submodule, is probably not secure?

here is the error from my build:
```
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/<private>/<org-repo>.git /home/runner/.npm/_cacache/tmp/git-clone-5ad02c85/.git
npm ERR! warning: templates not found in /tmp/pacote-git-template-tmp/git-clone-2b10460c
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/<private>/<org-repo>.git/'
```

**Comment by jsg2021** [comment]
Here is my action file:

```yml
name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.actions_repo_access }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm config
        run: |
          npm config set loglevel error
          npm config set progress false

      - run: npm install # <-- fails here, git commands to my repos do not have auth
      - run: npm test
```
