### ISSUE TITLE
Improve error reporting for no such reference

### ISSUE THREAD

**Issue by jsoref** [actions/checkout#1660]
https://github.com/check-spelling-sandbox/actions-checkout-no-such-branch/actions/runs/8296847126/workflow

```yaml

name: checkout missing branch

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: no-such-branch

```

https://github.com/check-spelling-sandbox/actions-checkout-no-such-branch/actions/runs/8296847126

#### Annotations
1 error

> ❌ [checkout](https://github.com/check-spelling-sandbox/actions-checkout-no-such-branch/actions/runs/8296847126/job/22706661159#step:2:60)
>    The process '/usr/bin/git' failed with exit code 1

<details><summary>Logs</summary>

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/no-such-branch*:refs/remotes/origin/no-such-branch* +refs/tags/no-such-branch*:refs/tags/no-such-branch*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 17 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/no-such-branch*:refs/remotes/origin/no-such-branch* +refs/tags/no-such-branch*:refs/tags/no-such-branch*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 17 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/no-such-branch*:refs/remotes/origin/no-such-branch* +refs/tags/no-such-branch*:refs/tags/no-such-branch*
  Error: The process '/usr/bin/git' failed with exit code 1
```

</details>
