### ISSUE TITLE
Improve error reporting for repository reference with `@`

### ISSUE THREAD

**Issue by jsoref** [actions/checkout#1661]
This actually happened as someone was migrating from:

```
  steps:
  - uses: owner/repo@ref
```

to:

```
  steps:
  - uses: actions/checkout@v4
    with:
      repository: owner/repo@ref
      ssh-key: ${{ secrets.OWNER_REPO_KEY }}
  - uses: ./
```

There are two flavors of poor error messages here.

#### Annotations
1 error
> ❌ [checkout](https://github.com/check-spelling-sandbox/checkout-repository-with-at/actions/runs/8297497838/job/22708757793#step:2:59)
Not Found

Workflow: https://github.com/check-spelling-sandbox/checkout-repository-with-at/actions/runs/8297497838/workflow

```yml
name: checkout repository with at

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: check-spelling-sandbox/checkout-repository-with-at@main
```

#### Annotations
4 errors
> ❌ [checkout](https://github.com/check-spelling-sandbox/checkout-repository-with-at/actions/runs/8297497848/job/22708758204#step:2:56)
remote error:
❌ [checkout](https://github.com/check-spelling-sandbox/checkout-repository-with-at/actions/runs/8297497848/job/22708758204#step:2:62)
remote error:
❌ [checkout](https://github.com/check-spelling-sandbox/checkout-repository-with-at/actions/runs/8297497848/job/22708758204#step:2:68)
remote error:
❌ [checkout](https://github.com/check-spelling-sandbox/checkout-repository-with-at/actions/runs/8297497848/job/22708758204#step:2:71)
The process '/usr/bin/git' failed with exit code 128

Workflow: https://github.com/check-spelling-sandbox/checkout-repository-with-at/actions/runs/8297497848/workflow

```yml
name: checkout repository with at (private)

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: check-spelling-sandbox/checkout-repository-with-at@main
          ssh-key: ${{ secrets.REPO_KEY }}
```
