### ISSUE TITLE
fetch-tags=true do not work when fetch-depth > 0

### ISSUE THREAD

**Issue by marcindabrowski** [actions/checkout#1662]
Description of the `fetch-tags` says: `Whether to fetch tags, even if fetch-depth > 0`,
but it seems that action in version `4.1.1` do not pull the tags, only the PR branch.

I set these action options:

```yaml
fetch-depth: 1
fetch-tags: true
ref: ${{ github.head_ref }}
```
