### ISSUE TITLE
@apurvdeodhar

### ISSUE THREAD

**Issue by ghost** [actions/checkout#1680]
@apurvdeodhar 
I can confirm that my act local run now works after adding the GITHUB_TOKEN secret parameter, even though I was using 
```
      - name: Checkout Branch release/k8s_merged
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
          ssh-key: ${{ secrets.SSH_KEY }}
```

act command:
```
act -P ubuntu-latest=-self-hosted -W .github/workflows/local-merge-from-master.yaml --container-architecture linux/amd64 -s GITHUB_TOKEN=$GITHUB_TOKEN
```

_Originally posted by @mills-nick in https://github.com/actions/checkout/issues/298#issuecomment-1961351783_
