### ISSUE TITLE
Recent Update to v4.1.3 Causes LibGit2SharpException with Sparse Checkout

### ISSUE THREAD

**Issue by skylayer** [actions/checkout#1689]
Hello,

After the recent update to `actions/checkout@v4.1.3`, we have encountered an issue when handling repositories after a sparse checkout using LibGit2Sharp. The workflow that was functioning correctly with `v4.1.1` started throwing an exception post-update.

Here's the snippet of the workflow configuration that triggers the issue:

```yaml
- name: Checkout repository
  uses: actions/checkout@v4
  with:
    submodules: true
    fetch-depth: 0
    fetch-tags: true
    filter: blob:limit=100k
```

When our program processes the repository with the above checkout command, it results in the following unhandled exception:

```
Unhandled exception. LibGit2Sharp.LibGit2SharpException: unsupported extension name extensions.worktreeconfig
```

This exception did not occur with version `v4.1.1`. I'm unsure how to proceed and address this issue, and any guidance would be greatly appreciated.

Thank you for looking into this.

**Comment by jww3** [comment]
Hi @skylayer.  We will investigate.  In the meantime, you can pin your workflow to `v4.1.1`

### Example
```
- name: Checkout repository
  uses: actions/checkout@v4.1.1
  with:
    submodules: true
    fetch-depth: 0
    fetch-tags: true
    filter: blob:limit=100k

```
