### ISSUE TITLE
Recent update breaks GitVersion

### ISSUE THREAD

**Issue by chadgrant** [actions/checkout#1690]
Previous config:

 ```
     - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
```
Gitversion now errors with "unsupported extension name extensions.worktreeconfig"

I was able to fix it with:

```      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: fix git
        run: |
          git config --unset-all extensions.worktreeconfig || true
          git config --global --list

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
```
