### ISSUE TITLE
Version 4.1.3 breaks Sentry auto-detection

### ISSUE THREAD

**Issue by PodStuart** [actions/checkout#1691]
When updating to version 4.1.3 our workflows start to fail with the following error:

`ERROR in Sentry CLI Plugin: Unable to determine version. Make sure to include `release` option or use the environment that supports auto-detection https://docs.sentry.io/cli/releases/#creating-releases.`

Our checkout step looks like this:

```
    - name: Checkout
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      with:
        fetch-depth: 0
        filter: tree:0
        ref: ${{ github.event.pull_request.head.sha }}
```

I see a couple other issues reported against version 4.1.3 and perhaps this has the same root cause.
