### ISSUE TITLE
`filter` options not applied to submodules?

### ISSUE THREAD

**Issue by Crzyrndm** [actions/checkout#1714]
Checking the log of an action which is using the following
```yml
- uses: actions/checkout@v4
  with:
    submodules: true
    fetch-depth: 0
    filter: blob:none
```
The submodule checkout step indicates the filter is not applied
```
# Fetching the primary repo
git -c protocol.version=2 fetch --prune --no-recurse-submodules --filter=blob:none ...
# fetching / checking out submodules
git -c protocol.version=2 submodule update --init --force
```
I was expecting to see the `--filter=...` also present in the submodule. Is there a reason this is not the case?
