### ISSUE TITLE
Error: File was unable to be removed Error: EACCES: permission denied, rmdir '/opt/actions-runner/_work/...

### ISSUE THREAD

**Issue by mihalt** [actions/checkout#1720]
When I run checout second+ times I have error like this on title on my ubuntu self-hosted runner. Config is very simple like

```
on:
  push:
    branches: [ "production", "developing" ]
  pull_request:
    branches: [ "production", "developing" ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  testing:
    runs-on: self-hosted

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          up-flags: "--build"
      - name: testing
        run: "docker compose exec app pytest"
...
```

This command can help, but just once. After next running of job I see the same errors:
```
sudo chmod -R u+w /opt/actions-runner/_work/
sudo chown -R <username>:<group> /opt/actions-runner/_work/
```

**Comment by seniordev-ca** [comment]
@mihalt , any updates on this how to fix the error?
<img width="1078" alt="image" src="https://github.com/actions/checkout/assets/50069715/6e2ccb91-6817-4f2a-8a18-6cce9539b2b0">

**Comment by mihalt** [comment]
@seniordev-ca Nothing better than this yet

> This command can help, but just once. After on the next running of job I see the same errors:
> 
> sudo chmod -R u+w /opt/actions-runner/_work/
> sudo chown -R <username>:<group> /opt/actions-runner/_work/

**Comment by rainerh** [comment]
We are facing the same issue on all GitHub managed runners since this morning.

```cli
Error: File was unable to be removed Error: EACCES: permission denied, unlink '/home/runner/work/<reponame>/<reponame>/pkg/mod/golang.org/x/telemetry/config@v0.28.0/LICENSE'
```

A quick workaround for us was to disable the `GOPROXY` before the first `checkout` step as described here: https://github.com/golang/go/issues/67463#issuecomment-2120473780

```yaml
      - run: |
          echo "GOPROXY=off" >> $GITHUB_ENV
```

**Comment by asei-proxima** [comment]
I faced same issue. But the following code resolve this issue:

```bash
./svc.sh install root
```

**Comment by marissareyes80** [comment]
Y como lo hago?

**Comment by pmabres** [comment]
Having the same issue with Github cloud hosted runners and custom docker images using ghcr.io registry.
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/${{ github.repository_owner }}/MY_CUSTOM_IMAGE:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4.1.0
```
Is producing the following output
```text
/usr/bin/docker exec  9c1ef0722b50a35be011c94cd4b11613abd66de932815320787efe6a556b42ec sh -c "cat /etc/*release | grep ^ID"
node:fs:2346
    return binding.writeFileUtf8(
                   ^

Error: EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_67a1c14a-d0a9-4347-a4e9-91d95775aead'
    at Object.writeFileSync (node:fs:2346:20)
    at Object.appendFileSync (node:fs:2427:6)
    at Object.issueFileCommand (/__w/_actions/actions/checkout/v4.1.0/dist/index.js:2967:8)
    at Object.saveState (/__w/_actions/actions/checkout/v4.1.0/dist/index.js:2884:31)
    at 8647 (/__w/_actions/actions/checkout/v4.1.0/dist/index.js:2343:10)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v4.1.0/dist/index.js:[18](https://github.com/###REDACTED###/actions/runs/10448856273/job/28973868656#step:3:19)273:43)
    at 2565 (/__w/_actions/actions/checkout/v4.1.0/dist/index.js:146:34)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v4.1.0/dist/index.js:18273:43)
    at 9[21](https://github.com/###REDACTED###/actions/runs/10448856273/job/28973868656#step:3:22)0 (/__w/_actions/actions/checkout/v4.1.0/dist/index.js:1144:36)
    at __nccwpck_require__ (/__w/_actions/actions/checkout/v4.1.0/dist/index.js:18273:43) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/__w/_temp/_runner_file_commands/save_state_67a1c14a-d0a9-4347-a4e9-91d95775aead'
}
```

**Comment by jdebbink** [comment]
Also getting this issue. I'm using this workaround with some success.
```
- uses: actions/checkout@v4
   with:
     path: ${{ github.sha }}
```

**Comment by jacescheffler-tanduo** [comment]
> Also getting this issue. I'm using this workaround with some success.
> 
> ```
> - uses: actions/checkout@v4
>    with:
>      path: ${{ github.sha }}
> ```

This worked for one of our pipelines that had two jobs running on a single self hosted server runner. The first one always succeeded but the second one would fail until we added `path: ${{ github.sha }}`

**Comment by djha-skin** [comment]
I found the problem, at least what it looks like on our end. The build couldn't get rid of some golang build files, and I looked in the directory that couldn't be gotten rid of. Look what I found:


```
total 128K
dr-xr-xr-x 19 github github 4.0K Dec 23 20:48 .
drwxr-xr-x  8 github github 4.0K Dec 23 20:48 ..
dr-xr-xr-x  2 github github 4.0K Dec 23 20:48 cases
dr-xr-xr-x  3 github github 4.0K Dec 23 20:48 cmd
-r--r--r--  1 github github   21 Dec 23 20:48 codereview.cfg
dr-xr-xr-x  4 github github 4.0K Dec 23 20:48 collate
-r--r--r--  1 github github  913 Dec 23 20:48 CONTRIBUTING.md
dr-xr-xr-x  2 github github 4.0K Dec 23 20:48 currency
dr-xr-xr-x  2 github github 4.0K Dec 23 20:48 date
-r--r--r--  1 github github  653 Dec 23 20:48 doc.go
dr-xr-xr-x 12 github github 4.0K Dec 23 20:48 encoding
dr-xr-xr-x  3 github github 4.0K Dec 23 20:48 feature
-r--r--r--  1 github github 8.8K Dec 23 20:48 gen.go
-r--r--r--  1 github github  345 Dec 23 20:48 .gitattributes
-r--r--r--  1 github github  206 Dec 23 20:48 .gitignore
-r--r--r--  1 github github  220 Dec 23 20:48 go.mod
-r--r--r--  1 github github  523 Dec 23 20:48 go.sum
dr-xr-xr-x 16 github github 4.0K Dec 23 20:48 internal
dr-xr-xr-x  4 github github 4.0K Dec 23 20:48 language
-r--r--r--  1 github github 1.5K Dec 23 20:48 LICENSE
dr-xr-xr-x  4 github github 4.0K Dec 23 20:48 message
dr-xr-xr-x  2 github github 4.0K Dec 23 20:48 number
-r--r--r--  1 github github 1.3K Dec 23 20:48 PATENTS
-r--r--r--  1 github github 3.0K Dec 23 20:48 README.md
dr-xr-xr-x  2 github github 4.0K Dec 23 20:48 runes
dr-xr-xr-x  2 github github 4.0K Dec 23 20:48 search
dr-xr-xr-x  4 github github 4.0K Dec 23 20:48 secure
dr-xr-xr-x  2 github github 4.0K Dec 23 20:48 transform
dr-xr-xr-x  7 github github 4.0K Dec 23 20:48 unicode
dr-xr-xr-x  2 github github 4.0K Dec 23 20:48 width
```

The files all have `github` as their owner, which is correct, but they are a lot of them marked `-r--r--r--`, which disallows the build from removing the file.

The solution (workaround) is to add this build step _before_ checkout:

```yaml
      - name: https://github.com/actions/checkout/issues/1720
        run: |
          chmod -R u+rwX .
```

Perhaps you guys might add a `chmod` option to fix?
