### ISSUE TITLE
:error::codeql/upload-sarif action failed: Input required and not supplied: token

### ISSUE THREAD

**Issue by chdonncha** [actions/checkout#1725]
I'm having an issue where using the default Eslint workflow configuration, it's providing me with this error:
![image](https://github.com/actions/checkout/assets/8567795/e8a1398c-08fa-460d-899b-fd4329bb8bd5)

I've given my token the appropriate security privileges but still not changing  from this error.

Here is my eslint.yml for the workflow action:

```
name: ESLint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '38 15 * * 3'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-processing: true
```

**Comment by cory-miller** [comment]
This isn't related to `actions/checkout`. Please use community discussions (https://github.com/community/community/discussions/categories/actions-and-packages) for questions like this in the future.

You may be getting this error because you are not accessing the built-in token. Instead you are trying to use a repository secret (found under the settings for actions).

```
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          token: ${{ github.token }}
          wait-for-processing: true
```

If this doesn't work, please reach out to the community link above.
