### ISSUE TITLE
Try out the new input `submodules`

### ISSUE THREAD

**Issue by ericsciple** [actions/checkout#176]
Collecting feedback for the new input `submodules`.

Use `actions/checkout@master`. Refer [here](https://github.com/actions/checkout/blob/master/README.md) for usage.

SSH support landing in master soon (tomorrow).

Will update the tag `v2` after collecting feedback. Likely next week.

**Comment by peaceiris** [comment]
It works well :tada:

log: https://github.com/peaceiris/hugo-test-project/runs/490347719?check_suite_focus=true#step:2:135

**Comment by ericsciple** [comment]
Also seeking feedback on this proposed change https://github.com/actions/checkout/pull/178 to convert SSH URLs to HTTPS when an ssh-key is not supplied.

**Comment by m-hilgendorf** [comment]
What is the approach for checking out private submodules over SSH? That solution doesn't seem to work, unless I'm doing something totally off base here: 

```yaml 
    - name: checkout hack 
      run: git config --global url."https://username:${{ secrets.USER_PWD }}@github.com/".insteadOf "git@github.com:"
    - uses: actions/checkout@master 
      with: 
        submodules: recursive 
```

For all private submodules I receive: 

```
 ##[error]fatal: repository 'https://github.com/user/repo.git/' not found
```
