### ISSUE TITLE
fetch-tags is not working according to the docs with v4

### ISSUE THREAD

**Issue by 64J0** [actions/checkout#1781]
Hello, hope you're good. I'm running some experiments in order to build a custom action that demands the tags from the repo. I noticed that it was possible, in theory, just using the `fetch-tags: true`, but it does not work. I can only get the tags if I use the `fetch-depth: 0`.

Example workflow:

```yaml
jobs:
  custom-action:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: tagaction
          fetch-tags: true
      - name: Try to get the tags
        run: |
          cd tagaction
          git tag --sort -creatordate
```

The last command (`git tag --sort -creatordate`) shows nothing in this case.

But, if I use the `fetch-depth: 0`, it lists correctly the tags from the repository.
