### ISSUE TITLE
Hey @m-chirodea!

### ISSUE THREAD

**Issue by rondales** [actions/checkout#1788]
Hey @m-chirodea!

Tried this:
```yml
name: Casual test
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-12, macos-13, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Print
      run: |
        echo "!"
```

All green:
<img width="318" alt="Screenshot 2024-06-20 at 11 36 33" src="https://github.com/actions/runner-images/assets/110455084/759abfb1-56d8-45e7-a831-06ddfa673406">

Are you sure it is service related?

_Originally posted by @erik-bershel in https://github.com/actions/runner-images/issues/10099#issuecomment-2180247256_
