### ISSUE TITLE
Lack of support for GITHUB_SERVER_URL with subpath

### ISSUE THREAD

**Issue by Indeedornot** [actions/checkout#1817]
Currently this action does not support GITHUB_SERVER_URL with subpath; In this case I am using this for gitea which I am hosting through  Nginx subpath /gitea/.

However getFetchUrl in the code uses `serverUrl.origin` stripping the `/gitea/` and making my actions fail.

Possible solution is not cleaning the path specified in input that way I can do and it should work by trusting the user given url

```
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: main
          github-server-url: ${{ secrets.GITHUB_SERVER_URL }}
```
