### ISSUE TITLE
Cannot checkout named `v8` ref in a container

### ISSUE THREAD

**Issue by laverdet** [actions/checkout#1876]
This action does not work correctly from a container workflow.

```yaml
name: Build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:experimental-20240812
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "12.8.20"
          repository: v8/v8
```

A failed run is here:
https://github.com/laverdet/checkout-bug/actions/runs/10690612018/job/29635384696

Logs copy/pasted below here:
```
Run actions/checkout@v4
/usr/bin/docker exec  7decb8ab921da4135c8fd3c2d1401826f3be7aa4ff4d407986b566668edfe365 sh -c "cat /etc/*release | grep ^ID"
Syncing repository: v8/v8
Getting Git version info
Deleting the contents of '/__w/checkout-bug/checkout-bug'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.[18](https://github.com/laverdet/checkout-bug/actions/runs/10690612018/job/29635384696#step:3:19) or higher to the PATH
Downloading the archive
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
Waiting 10 seconds before trying again
Downloading the archive
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
Waiting 18 seconds before trying again
Downloading the archive
Error: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
```

If I change ref to `"tags/12.8.20"` then it works. Additionally if I run without a container then it works.
