### ISSUE TITLE
Authentication failed with proxy

### ISSUE THREAD

**Issue by Ardear** [actions/checkout#1897]
I set up the proxy "https://ghp.ci/" to my runner machine, but I got an error:
```
Error: fatal: Authentication failed for 'https://ghp.ci/https://github.com/xxx/xxx/'
```
The code in workflow is:
```
    steps:
      - name: Checkout
        uses: actions/checkout@v4
```

After that, I tried  to authenticate the identity using a custom PAT, I added the secret and changed the code to:
```
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
```
I still get the same error.
But if I try to run command locally and enter the PAT as password, it runs successfully:
```
git clone https://ghp.ci/https://github.com/xxx/xxx/
Username for 'https://ghp.ci':xxx
Password for 'https://xxx@ghp.ci':
remote: Enumerating objects: 317, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 317 (delta 38), reused 46 (delta 27), pack-reused 221 (from 1)
Receiving objects: 100% (317/317), 143.40 KiB | 315.00 KiB/s, done.
Resolving deltas: 100% (144/144), done.
```
