### ISSUE TITLE
Add an option to create a new branch from the default branch if the specified ref does not exist

### ISSUE THREAD

**Issue by Shion1305** [actions/checkout#1920]
### Problem
Currently, when using `actions/checkout`, specifying a `ref` that does not exist causes the action to fail. In some workflows, it would be more efficient if, when the specified branch does not exist, a new branch could be automatically created from the default branch.

### Proposed Solution
I propose adding an `auto-create` option to `actions/checkout`. This option would allow the action to:
1. Checkout the default branch (e.g., `main`) if the specified `ref` does not exist.
2. Create a new branch with the specified `ref` from the default branch.

This behavior would only occur when the `auto-create` option is enabled, keeping the current behavior unchanged by default.

### Example YAML
```yaml
- name: Checkout code
  uses: actions/checkout@v3
  with:
    ref: 'feature-branch'
    auto-create: true
```
