### ISSUE TITLE
action doesn't use git repo with git > 2.18 installed

### ISSUE THREAD

**Issue by acnicholls** [actions/checkout#1936]
I can't seem to get my runner to create or use a repository

Here's my action calling code

```
      - name: Check out the code with a filter
        id: download-compose-files
        uses: actions/checkout@v4
        with:
          ref: develop
          sparse-checkout: |
            docker-compose.ghcr-stage.yml
          sparse-checkout-cone-mode: true
```

and here's the result from the workflow log:

![image](https://github.com/user-attachments/assets/9c04fa88-931b-46fe-8b55-98201c8b6064)

this is a self-hosted running and non-root user.
what am I missing?
