### ISSUE TITLE
Unable to locate executable file: ssh

### ISSUE THREAD

**Issue by ndlanier** [actions/checkout#1942]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

Using the checkout action to pull a dependency repository via ssh
```
- name: Checkout common-modules@${{ steps.set_versions.outputs.MODULE_VERSION }}
      uses: actions/checkout@v4.2.0
      if: steps.set_versions.outputs.MODULE_APPS && steps.run_condition.outputs.RUN_CONDITION
      with:
        repository: ${{ inputs.COMMON_MODULE_REPO }}
        ssh-key: ${{ secrets.COMMON_MODULE_SSH }}
        ref: ${{ steps.set_versions.outputs.MODULE_VERSION }}
        path: common_modules
```

I am seeing the following error:
`Error: Unable to locate executable file: ssh. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`

We have changed the version we are using back and forth and are still having the issue.
Is the image it's pulling missing the ssh executable or is this a misleading error?
