### ISSUE TITLE
Unable to npm install private repo via ssh using with `ssh-key`

### ISSUE THREAD

**Issue by RobinBol** [actions/checkout#195]
I am trying to setup an action which checks out a git repo which has private npm dependencies (e.g. `"my-package": "git+ssh://git@github.com/myOrg/myPrivateRepo.git"`.

Previously I would use:
```yaml
       - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
```

Running `npm ci` afterwards results in a successful installation of `my-package`.

Now I say `checkout@v2` has its own `ssh-key` property, so I'd like to use that instead of the `webfactory/ssh-agent@v0.2.0` action. 

However the following configuration results in a `git@github.com: Permission denied (publickey).`:
```yaml

      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          token: ${{ secrets.PAT }}

      - name: Build
        run: npm ci
```

<details>
<summary>Full error log</summary>

```
Run npm ci
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q ssh://git@github.com/athombv/node-zigbee-clusters.git /home/runner/.npm/tmp/git-clone-60d07701/.git
npm ERR! warning: templates not found in /tmp/pacote-git-template-tmp/git-clone-5994cbe0
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-03-24T10_03_37_383Z-debug.log
##[error]Process completed with exit code 1.
```
</details>

I would expect that the `ssh-key` option would setup the ssh key in the local git config similary to `webfactory/ssh-agent@v0.2.0` but that does not seems the case. Anyone an idea what is happening here?

Thanks!

**Comment by ericsciple** [comment]
@RobinBol when ssh-key is provided, it is configured in the local git config using `core.sshCommand`

**Comment by alexrindone** [comment]
Was there a solution to this? I am having a similar issue.

**Comment by RobinBol** [comment]
@alexrindone as stated in the issue description, I worked around this by:
```yaml
       - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
```

But, I did not manage to get it working without `webfactory/ssh-agent`, it seems as @ericsciple suggests there is a difference between the way the two approaches setup ssh in the action workspace.
