### ISSUE TITLE
Missing .github directory

### ISSUE THREAD

**Issue by h2oearth** [actions/checkout#1976]
I am using the latest checkout version; somehow, the .github directory is missing when I check the repository.  I appreciate your help :-)

```
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          ref: master
          repository: mine/github-workflows
          token: ${{ secrets.REPO_ACCESS }}
```

**Comment by valentindeaconu** [comment]
We are experiencing the same (or similar) issue with our setup:

```
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ./.github/actions/compute-jobs

      - name: 'Compute jobs'
        id: jobs
        uses: ./.github/actions/compute-jobs
```

The step `Checkout` finishes successfully, but `Compute jobs` fails with:
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/_work/maple/maple/.github/actions/compute-jobs'. Did you forget to run actions/checkout before running your local action?
```

We started to experience this when we upgraded to `actions/runner:v2.320.0`.
