### ISSUE TITLE
Sparscheckout breaks cached repository

### ISSUE THREAD

**Issue by imarinov3** [actions/checkout#1992]
When we use sparsecheckout in some job, the next jobs continue to use sparscheckout.

```yaml
- uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          .github/
```
After this job finishes any other job that runs on the same machine using normal checkout preserves the sparse option.

```yaml
- uses: actions/checkout@v4
```
We run into this issue when running multiple jobs while only one of those have sparse checkout. All jobs are from the same repository.

In the logs we see that the second job executes git sparse-checkout disable (during checkout), but this command does not seem to take effect. We still see the sparseCheckout = true option if we look inside the .git/config of the repo.
