### ISSUE TITLE
Actions V4 unable to find repository using windows runner

### ISSUE THREAD

**Issue by ClaireLundy** [actions/checkout#2010]
I am create a github action using the `windows-latest` runner and write permissions. The issue is that the action is failing on the 'Checkout GitHub Action' step:

![Screenshot 2024-12-18 at 2 59 47 PM](https://github.com/user-attachments/assets/01b49616-7ce5-47f8-aa1d-1f5183005e49)

Here the the relevant part of my yaml file:
```
name: Build and deploy dotnet core app to Azure Function App - ConvertToJsonFRCM

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: 'v4.0' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
```

I have tried added the repository name explicitly using the `repository` option. I've validated that my user has the correct permissions.
