### ISSUE TITLE
Feature request: explicit fetch-depth:0 to also fetch tags

### ISSUE THREAD

**Issue by jasonkarns** [actions/checkout#204]
v2 is great! It's much faster and optimized for most "main" scenarios of running tests or builds on the latest commit.

However, on tag events, a very common workflow is to publish the tag as a release somewhere (homebrew, npm, github releases, etc). A major component of most release flows is generating release notes which requires knowledge of prior tags.

Using v2, I expected `fetch-depth:0` to make this possible.

Problematic run: https://github.com/nodenv/nodenv/runs/549286319?check_suite_focus=true

Error:
```
Run script/release-notes | tee relnotes.txt
fatal: No tags can describe '443076f046e3db1820d725f6d82947c55dcbdc8f'.
Try --always, or create some tags.
```

workflow:

```yml
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - run: script/release-notes | tee relnotes.txt
```

My hope is that when fetch-depth:0 is supplied (which implies we want _all history_) that tags will be fetched as well. I believe this would keep the non-tag "main" scenario fast as desired; while also making the most common tagging scenario more intuitive.

related to #100
