### ISSUE TITLE
verify configuration directive names

### ISSUE THREAD

**Issue by vladak** [actions/checkout#205]
I happened to setup the `checkout@v2` like so:
```yml
    - name: Checkout gh-pages branch                                            
      uses: actions/checkout@v2                                                 
      with:                                                                     
        path: gh-pages                                                          
        refs: gh-pages
```
however instead of complaining that I used `refs` instead of `ref` it happily checkout out the `master` branch.
