### ISSUE TITLE
I am not able to fetch all tags

### ISSUE THREAD

**Issue by tillbrodbeck-oviva** [actions/checkout#2095]
Looking at 
```yaml
name: Foo Bar

on:
  push:
    branches:
      - main

jobs:
  tag-dependabot-prs:
    name: Build & Tag containers for Dependabot PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Tag changed base images
        run: |
          git fetch --prune --tags
          git tag | wc -l
```

Locally, using act, I am seeing 885 (all of the) tags. When I run it on GitHub online, it only gives me like 8 tags (only the current commit). 

I have also tried a distinct step to fetch tags - also does not work
```yaml
  - name: Fetch all tags
    run: git fetch --tags --force
```

This must be a bug, right? Or am I doing something wrong. Anyone has a good workaround for the moment?
