### ISSUE TITLE
We are checking for a way to pass multiple option to the `actions/checkout@v4`, when used in a reusable workflow.

### ISSUE THREAD

**Issue by mrmontoya913** [actions/checkout#2097]
We are checking for a way to pass multiple option to the `actions/checkout@v4`, when used in a reusable workflow.

Something like following
```yaml
jobs:
  docker:
    name: Docker
    uses: ./.github/workflows/docker.yml
    with:
      docker_file: Dockerfile
      dockerhub_repo: account/repository
      checkout: |
        repository: ''
        ref: ''
        token: ''
        path: ''
        clean: ''
        fetch-depth: ''
        fetch-tags: ''
    secrets: inherit
```

Is there a way to pass a list of options in that way?

_Originally posted by @air3ijai in https://github.com/actions/checkout/discussions/2093_
