### ISSUE TITLE
unable to get local issuer certificate for no reason

### ISSUE THREAD

**Issue by ze42** [actions/checkout#2105]
Context: I'm trying to clone a private repository containing some actions to launch further...

* Cloning the main repository works fine:
```
      - name: Clone default repo
        uses: "actions/checkout@v4"
        continue-on-error: true
        with:
          path: ./src
```
* Cloning it again with a token works:
```
      - name: Clone default repo with token
        uses: "actions/checkout@v4"
        continue-on-error: true
        with:
          repository: me/myrepo
          path: ./src2
          token: ${{ secrets.GT_TOKEN }}
```
* Cloning an other repository fails (with `unable to get local issuer certificate` error message)
```
      - name: Clone action repo with token
        uses: "actions/checkout@v4"
        continue-on-error: true
        with:
          repository: me/actions
          path: ./actions
          token: ${{ secrets.GT_TOKEN }}
```
* The repo is still properly setup, and allows a `git fetch` to just work and do it job!
```
          cd "actions" &&
          git status &&
          git fetch
```

Some more context notes:
* I am running an a private git repository, not on github.
* It uses a private domain, with some local CA
* All repository are on the same vhost, and the root CA is properly added, which explains why most commands works fine
* Yes, a curl also work fine, and does not have any certificate issue
