### ISSUE TITLE
Permission denied when "Deleting the contents of"

### ISSUE THREAD

**Issue by soasada** [actions/checkout#211]
Hi checkout team,

I'm having an issue when actions/checkout@v2 is trying to delete the repository:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/7634531/78761035-4fd09300-7982-11ea-867d-2bf9121d27e9.png">

I tried to change the permissions of the file but still happening, this has been happening since yesterday. I think that could be a bug but correct me if I'm wrong.

My `.github/workflow/docker.yml` is like this:

```
name: MorciTravel CI

on: [push]

jobs:

  morcitravel_job:
    name: Morcitravel job
    runs-on: ubuntu-latest
    env:
      KILL_JAVA_SH: ${{ github.workspace }}/ci/kill_java_process.sh
      SERVER_PUB_KEY: ${{ github.workspace }}/data/server/server_pub_key.txt
      JAVA_CMD_PATH: /opt/prod_jdk/bin/java
      JAR_NAME: morci-travel-api-
    services:
      mongodb:
        image: mongo:4-bionic
        ports:
          - 27017:27017
        volumes:
          - ${{ github.workspace }}/data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Test & Package frontend
        run: mvn -B clean install -pl :morci-travel-frontend
      - name: Create version
        run: |
          APP_RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          APP_RELEASE_VERSION_ARRAY=(${APP_RELEASE_VERSION//./ })
          ((APP_RELEASE_VERSION_ARRAY[2]++))
          APP_RELEASE_VERSION="${APP_RELEASE_VERSION_ARRAY[0]}.${APP_RELEASE_VERSION_ARRAY[1]}.${APP_RELEASE_VERSION_ARRAY[2]}"
          echo "::set-env name=JAR_NAME::$JAR_NAME$APP_RELEASE_VERSION-SNAPSHOT.jar"
          mvn -B --batch-mode release:update-versions -DdevelopmentVersion=$APP_RELEASE_VERSION-SNAPSHOT
      - name: Test & Package backend
        run: mvn -B clean test package -pl :morci-travel-api
      - name: Prepare SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat "$SERVER_PUB_KEY" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Kill java process
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -s' < $KILL_JAVA_SH
      - name: Remove old artifacts
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rm -rf morci-travel-api-*.jar"
      - name: Copy jar to server
        run: |
          scp -P ${{ secrets.PORT }} ${{ github.workspace }}/morci-travel-api/target/$JAR_NAME ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~
      - name: Launch app
        run: |
          ssh -f -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "$JAVA_CMD_PATH -Xms64M -Xmx256M -jar $JAR_NAME &"
      - name: Commit version
        run: |
          git config --global user.name 'Nicolas Vargas Ortega'
          git config --global user.email 'soasada@users.noreply.github.com'
          git commit -am "AUTOMATIC: Updated version"
          git push
```

**Comment by ericsciple** [comment]
You may need to specify the checkout `path` input to avoid the volume mount being under the repository.

The containers are setup at the beginning of the job. And git clone will fail if the directory isnt empty.

You could always symlink the dir back in place (or copy the files), if you need the data underneath the repository. Or if it's your test data, consider updating your scripts to allow the location to be overridden using an env var.

**Comment by soasada** [comment]
> You may need to specify the checkout `path` input to avoid the volume mount being under the repository.
> 
> The containers are setup at the beginning of the job. And git clone will fail if the directory isnt empty.
> 
> You could always symlink the dir back in place (or copy the files), if you need the data underneath the repository. Or if it's your test data, consider updating your scripts to allow the location to be overridden using an env var.

I just removed the service and is working again. The thing is that I was able to use the script without problems (with the service) in the past.

So AFAIK, the problem is that the service mount the volume before the github checkout and this create a existing file with the same name (I guess) and github/checkoutv2 cannot remove it, right?

**Comment by jeremylynch** [comment]
I experienced the same issue. To get around this I ran a command to change file permissions right before executing actions/checkout: 
```bash
sudo chown -R $USER:$USER /home/github/actions-runner/_work/{REPOSITORY_NAME_HERE}
```

**Comment by ericsciple** [comment]
I'm going to add a troubleshooting doc. I'll add a section for this.

**Comment by karancode** [comment]
Thank you for reporting this,. I am also facing the same issue...

**Comment by soasada** [comment]
> Thank you for reporting this,. I am also facing the same issue.. But I still couldn't figure out a way to resolve this. Please help.

Could you take a look at @jeremylynch response?

**Comment by zpsjs** [comment]
I had to add "echo password" before, otherwise sudo is asking for password.

`echo ${{secrets.DEPLOY_PASSWORD}} | sudo -S chown -R $USER:$USER /home/github/deployment/{REPOSITORY_NAME_HERE}`

Is there a better solution?

**Comment by guykeller** [comment]
@ericsciple I have encountered a similar issue, but have not been able to sort it using the suggested solution by @jeremylynch.
![image](https://user-images.githubusercontent.com/33782301/82991470-67cda600-a006-11ea-9697-3d83b54e8b13.png)

We're getting this error when using this action:
![image](https://user-images.githubusercontent.com/33782301/82991537-80d65700-a006-11ea-9ea4-f0edd876e79d.png)

And secrets.Nothing contains our PAT, which should be valid (defined for a user that has access to the repo, saved as a secret in the repo).
Moreover, I've tried adding the permissions as suggested above, removing the token field, and using several different endpoints.

Important note - the same flow works without using the container, and the checkout is successful.

Any idea as to what the problem might be?  I'll appreciate any advice

**Comment by JungHanter** [comment]
> @ericsciple I have encountered a similar issue, but have not been able to sort it using the suggested solution by @jeremylynch.
> ![image](https://user-images.githubusercontent.com/33782301/82991470-67cda600-a006-11ea-9697-3d83b54e8b13.png)
> 
> We're getting this error when using this action:
> ![image](https://user-images.githubusercontent.com/33782301/82991537-80d65700-a006-11ea-9ea4-f0edd876e79d.png)
> 
> And secrets.Nothing contains our PAT, which should be valid (defined for a user that has access to the repo, saved as a secret in the repo).
> Moreover, I've tried adding the permissions as suggested above, removing the token field, and using several different endpoints.
> 
> Important note - the same flow works without using the container, and the checkout is successful.
> 
> Any idea as to what the problem might be? I'll appreciate any advice

@guykeller Is it solved? I have same problem when initialzing the repository

**Comment by ekahannes** [comment]
Also having the same issue if I use a container.

**Comment by guykeller** [comment]
I was not able to solve this, and instead had to stop using a container altogether.
Would love a solution if anyone has one.
FYI @JungHanter @ekahannes

**Comment by jef** [comment]
Potentially related to https://github.com/actions/runner/issues/434

**Comment by xanantis** [comment]
@guykeller You may find something helpful [here](https://github.com/xanantis/docker-file-ownership-fix#docker-file-ownership-fix).

**Comment by xanantis** [comment]
@felipecrs Well, how it looks, GitHub runner, is running under user, with UID: 1001 and GID: 116
So, change it to:
```ỳaml
clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user 1001
  steps:
      - uses: actions/checkout@v2
```

**Comment by felipecrs** [comment]
> @felipecrs Well, how it looks, GitHub runner, is running under user, with UID: 1001 and GID: 116

It makes sense. Do you know if is there any way to discover the UID dynamically?

The `options: --user "$(id -u)"` does not work by the way.

**Comment by xanantis** [comment]
@felipecrs  No idea.  Currently, I can see only two options. Hardcoded value or  "Configure" Job where you can fetch UID and use it later. But it does not make sense.

**Comment by xanantis** [comment]
@felipecrs Something like this (runs-on must be equal):

```ỳaml
  configure:
    runs-on: ubuntu-latest
    outputs:
      containerUser: ${{ steps.get-user.outputs.containerUser }}
    
    steps:
      - id: get-user
        run: echo "::set-output name=containerUser::`id -u`:`id -g`"
    
    
  clone-and-install:
    
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user ${{ needs.configure.outputs.containerUser }}
    steps:
      - uses: actions/checkout@v2
```

But it is ridiculous.

**Comment by felipecrs** [comment]
Thank you so much @xanantis! The need for this is indeed ridiculous, but it solves my problem.

**Comment by xanantis** [comment]
@felipecrs you're welcome  :smile:
If you are using only GitHub runners, you may consider using hardcoded value. Because UID and GID seem to be stable. 116 is a GID of a docker group.

**Comment by felipecrs** [comment]
@xanantis since I didn't find it documented anywhere, I suppose it can change anytime without any warnings, so I prefer to keep my builds safe.

**Comment by gengjiawen** [comment]
Any plan on fix this, this is quite annoying since many services limit user not to be root.

**Comment by felipecrs** [comment]
I believe the maintainers should close this issue since it's not caused by this Action. And of course, point to the relevant repository.

**Comment by felipecrs** [comment]
Since I could not find an issue that exactly describes the real issue and how to solve it, [I created one](https://github.com/actions/runner/issues/691).

I believe this can now be closed.

**Comment by EKami** [comment]
Here is another solution that is a bit hacky but works to clean up the working directory before attempting any checkout:
```
jobs:
  cleanup:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Cleaning up the $GITHUB_WORKSPACE as root from a Docker image
        # Volume auto mounted by gh actions pointing to the current working-directory
        run: find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true

  unit_tests:
    needs: cleanup
    name: Run the unit tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
```

Hope it helps!

**Comment by TrangPham** [comment]
> I experienced the same issue. To get around this I ran a command to change file permissions right before executing actions/checkout:
> 
> ```shell
> sudo chown -R $USER:$USER /home/github/actions-runner/_work/{REPOSITORY_NAME_HERE}
> ```

This worked for me - but I used `${{ github.workspace }}` as the path

**Comment by MakisH** [comment]
> This worked for me - but I used `${{ github.workspace }}` as the path

For me, I had to set the path to `/__w/{REPOSITORY_NAME_HERE}`. I am not sure if something changed, but this is where `checkout` seems to work in my case. If you think that I probably did something terribly wrong, please shout out.

I also [set up passwordless sudo](https://serverfault.com/a/160587/523294) in the container, something that anyway [GitHub Actions runners also set](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#administrative-privileges-of-github-hosted-runners).

**Comment by hkang-vuno** [comment]
I'm still having this issue. I'm running the github action in self-hosted mode on docker in ghcr.  When I updated the container image, I started to get this error.  When I change the image back to the previous one, I don't get this error. Looks like there must be a bug somewhere..

**Comment by SkypLabs** [comment]
Hi,

I'm just sharing a variant of @EKami's [solution](https://github.com/actions/checkout/issues/211#issuecomment-801043540) but with the clean-up task executed as a single step instead of a job to save a runner execution:

```yaml
  generate-openapi-code:
    name: Generate Go code from OpenAPI definitions
    runs-on: [self-hosted, nodejs]
    needs: [lint-openapi]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 🐳 Step spawning a Docker container 🐳
      - name: Generate web API client packages
        working-directory: ./history
        run: |
          npm install
          # This task spawns a Docker container per the OpenAPI Generator CLI configuration file
          # present in the current working directory 👇
          npx @openapitools/openapi-generator-cli generate

      - name: Archive Paylead API client package
        uses: actions/upload-artifact@v3
        with:
          name: openapi-paylead-api-package
          path: |                                                                                       
            history/pkg/paylead_api
          if-no-files-found: error

      # Temporary solution.
      # See https://github.com/actions/checkout/issues/211 for more details.
      - name: Clean up GitHub workspace
        uses: docker://ubuntu:latest # 👈 Clean-up done in a Docker container 🐳
        with:
          args: find /github/workspace/. -name . -o -prune -exec rm -rf -- {} +
```

**Comment by sumanth-sure** [comment]
> I experienced the same issue. To get around this I ran a command to change file permissions right before executing actions/checkout:
> 
> ```shell
> sudo chown -R $USER:$USER /home/github/actions-runner/_work/{REPOSITORY_NAME_HERE}
> ```
Hi was trying this out, but while running this command its asking for password how to pass the password without doing an echo and sending through pipe |

**Comment by EktaPuri12** [comment]
> 
Adding cleaning workspace step in workflow 

 - name: Cleaning Operation
        run : sudo find /opt/actions-runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true

Before Cloning the Repo First clean the workspace it will work.

**Comment by Yalchin403** [comment]
> I experienced the same issue. To get around this I ran a command to change file permissions right before executing actions/checkout:
> 
> ```shell
> sudo chown -R $USER:$USER /home/github/actions-runner/_work/{REPOSITORY_NAME_HERE}
> ```

It was woring perfectly till today, I haven't changed a line, but I got this for today's build:
```sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper```

**Comment by softlberton** [comment]
I was able to resolve this by adding this step:

```yaml
- name: Chown user
  run: |
    sudo chown -R $USER:$USER $GITHUB_WORKSPACE
```

**Comment by aLeX1443** [comment]
If you run inside a docker container, no files are stored so the next time you run you shouldn't get the error:

```
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # NOTE: we want to run inside a container, that way no files are saved locally after
    # the run completes. This way, we can use the on-prem runner without encountering
    # permission errors.
    container:
      image: ubuntu:22.10
```

**Comment by ejortegau** [comment]
I found a solution for this - check out the code of each job in a different directory so that different jobs don't interfere with each other. Here is my setup:
```yaml
name: ci-pipeline
#run-name: CI run for branch ${{ github.ref_name }}
on: [push]
jobs:
  test:
    runs-on: ts-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          path: test
      - run: bash ./scripts/ci.sh test
  lint:
    runs-on: ts-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          path: lint
      - run: bash ./scripts/ci.sh lint
```
No monkey business changing permissions or dealing with sudo.
