### ISSUE TITLE
git lfs checkout fails on 4.1.1

### ISSUE THREAD

**Issue by oharboe** [actions/checkout#2110]
I'm getting the error below, which is strange. I would have thought actions/checkout would handle a git repository that already has lfs set up.

![Image](https://github.com/user-attachments/assets/f6626501-3f31-4efe-8085-713c19da446b)

```
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1
          lfs: true
```

Output:

```
/usr/bin/git lfs install --local
Hook already exists: pre-push

	#!/bin/bash
	
	protected_branch='master'
	
	if read local_ref local_sha remote_ref remote_sha; then

```

I had to add the below or some git lfs files were not checked out properly
  
```
      - name: git lfs pull
        run: git lfs pull
```
