### ISSUE TITLE
URLs in `.gitmodules` starting with `ssh://` do not work.

### ISSUE THREAD

**Issue by sandeepd-nv** [actions/checkout#2178]
You'll need to use an SSH key instead of a PAT if any URL in your `.gitmodules` file starts with `ssh://` instead of `https://` or `git@github.com:` otherwise GitHub will fail to clone the submodule in question with a `Host key verification failed` error.

**Comment by PanDeOps** [comment]
Good afternoon, encountered a similar problem using deploy-key ssh and private submodule

In .gitmodules I specified
```
[submodule "SubModuleRepo"]
    path = SubModuleRepo
    url = git@github.com:Org/SubModuleRepo.git
```
I also tried to specify absolute path but I get the same error
```
    url = ssh://git@github.com:Org/SubModuleRepo.git.
```

When I try to download the sub module I get the error 
```bash
git@github.com: Permission denied (publickey). 
Error: fatal: Could not read from remote repository.
  
Please make sure you have the correct access rights
and the repository exists.
Error: fatal: clone of 'git@github.com:Org/SubModuleRepo.git' into submodule path "<<builder_path>>"
```

In pipeline:
```
- name: Checkout repository
  uses: actions/checkout@v4
  with:
    submodules: recursive
    ssh-key: ${{ secrets.DEPLOY-KEY}}
```

Could you show in detail your settings and how exactly you solved this problem?

**Comment by yyh12138** [comment]
Hi, I also encountered the same problem using deploy-key ssh and private submodule. My solution is to use the **https** instead of **ssh** in .gitmodules, and try token in .yml:

```
- name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
```
