### ISSUE TITLE
fetch-tags: false still fetches tags if fetch-depth is 0

### ISSUE THREAD

**Issue by SethDavenport** [actions/checkout#2195]
I'm trying to fetch all commits and branches, but not tags.

I've added this to my workflow:

```
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
```

But it's still fetching tags:

<img width="1162" alt="Image" src="https://github.com/user-attachments/assets/c8b95dda-5bf3-43f2-87d1-37c72a5a2bda" />

<img width="884" alt="Image" src="https://github.com/user-attachments/assets/e71d9c14-2756-4da5-b287-0718df2ea8f7" />
