### ISSUE TITLE
`fetch-tags: true` doesn't work

### ISSUE THREAD

**Issue by svaningelgem** [actions/checkout#2199]
```yaml
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
```
==> But this doesn't fetch all the tags.
I have to use
```yaml
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
```

For it to retrieve everything.
