### ISSUE TITLE
bad git state on Alpine OS

### ISSUE THREAD

**Issue by kiloexabyte** [actions/checkout#2204]
# Issue
When using an Alpine image in Github Actions runner, actions/checkout will put git into a bad state, causing `go build` to run into a vcs issue. `go build` is running into issue because its detecting git info through the `.git` folder but is not able to get the version info it needed and will exit with code 1.

# Logs
Github actions image used: https://github.com/kiloexabyte/runner-image/blob/main/Dockerfile
Workflow logs: https://github.com/kiloexabyte/vcs-issue-demo/actions/runs/15571879590/job/43849297094
Workflow file: https://github.com/kiloexabyte/vcs-issue-demo/blob/main/.github/workflows/push-main.yml

workflow:
```
name: Push to main

on:
    push:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: kiloexabyte/runner-image  // definition here: https://github.com/kiloexabyte/runner-image/blob/main/Dockerfile
    steps:
    - uses: actions/checkout@v4
    - run: | 
        go build 
```

![Image](https://github.com/user-attachments/assets/6235851f-45c6-43e0-ac61-d91060fbe739)
