### ISSUE TITLE
LFS objects Use Help

### ISSUE THREAD

**Issue by scottschreckengaust** [actions/checkout#2208]
The checkout action only fetches the pointer and not the object even when the `lfs: true`.

Please help me understand how to fetch the objects and not only pointers. My assumption is that files should be downloaded, and not the pointers, but this does not appear to be the case.

From https://github.com/actions/checkout?tab=readme-ov-file#usage:

```text
    # Whether to download Git-LFS files
    # Default: false
    lfs: ''
```

Snippet of workflow file:
```yaml
     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
```

Will add a https://sscce.org repo with example.
