### ISSUE TITLE
could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by kolya182** [actions/checkout#221]
Url to log https://github.com/trustwallet/assets/pull/1898/checks?check_run_id=597005450
```
name: Formatter
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - 'master'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_API_TOKEN }}
```
