### ISSUE TITLE
Add autocrlf option for Windows

### ISSUE THREAD

**Issue by jeroen** [actions/checkout#226]
I'm frequently debugging issues on my Windows builds which are due to the default git behavior of automatically changing line endings upon checkout. This default behavior sort-of makes sense for users that want to edit text files in editors on Windows, but for CI it's really unfortunate.

It would be really nice to have a native option to disable this behavior and checkout the repo as-is.

Currently I have this as a workaround (before running this action):

```yaml
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v2
```

Thanks!
