### ISSUE TITLE
Do I HAVE TO provide a token for checking out a public repository?

### ISSUE THREAD

**Issue by gqqnbig** [actions/checkout#230]
This is the snippet of my workflow file. I set token to empty string on purpose because I think https://github.com/systemd/systemd is a public repository, I don't need to authenticate to download it.

```yaml
    - name: Checkout systemd
      if: steps.restore-systemd-binary.outputs.cache-hit != 'true'
      uses: actions/checkout@v2.1.0
      with:
        token: ''
        path: systemd
        repository: systemd/systemd
        ref: v245
```

However, as the log file shows https://github.com/gqqnbig/advanced-play-search/pull/17/checks?check_run_id=631371897#step:4:31

the checkout action throws error   "##[error]fatal: could not read Username for 'https://github.com': terminal prompts disabled"

The goal of not providing my token is that I want to avoid the post-checkout step, which cleans up the token.
