### ISSUE TITLE
recursive checkout action not work as exptected.

### ISSUE THREAD

**Issue by liudonghua123** [actions/checkout#239]
I tried to use
```yaml
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
```
or
```yaml
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: '0'
```
But during the latter build process, it always failed with something error message like
```
Error: Command failed: git describe --tags
fatal: No names found, cannot describe anything.
```
see https://github.com/liudonghua123/dpo-voyager/runs/662309034?check_suite_focus=true.

And in the end I need to rewrite the checkout steps like the following to make the build process success.
```yaml
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: git fetch --prune --unshallow
```

ref: https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything

Is there any options to make git work as `--prune --unshallow`?
