### ISSUE TITLE
possible to checkout or clone another repo?

### ISSUE THREAD

**Issue by ChrisChiasson** [actions/checkout#24]
I noticed the documentation for `actions` says I can't call an action in another private repo that I own. I have a different question. Is it possible to use the checkout action (of my repo) to checkout a public repo, or a private repo owned by me. This would be useful for pulling the latest version of C++ boost header libraries, or another library I wrote that's needed for the build.

**Comment by maxperrimond** [comment]
I tried to clone another private repository with the action but I only get:
```
##[error]fatal: repository 'https://github.com/orgname/reponame/' not found
```
step:
```yaml
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: orgname/reponame
```
I tried to pass the github token but doesn't change the outcome.

**Comment by TingluoHuang** [comment]
@maxperrimond  try to generate a PAT and set that as repository secret, use that to clone the extra repository, the GITHUB_TOKEN is scope to the workflow repo.
Ex:
```yaml
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: orgname/reponame
          token: ${{ secrets.my_pat }}
```

**Comment by maxperrimond** [comment]
It worked well. Thanks for your support @TingluoHuang

**Comment by ChrisChiasson** [comment]
Thanks

**Comment by rogerprz** [comment]
If it's from another source outside of github do we use the full URL?

**Comment by hohserg1** [comment]
I want to clone multiple repos for together build. How to prevent deleting of prev-cloned repo?
![image](https://user-images.githubusercontent.com/35610168/96369142-f632f780-1160-11eb-8f84-d9d1db759a1c.png)
It's my configuration: https://github.com/ElegantNetworking/ElegantNetworkingRoot/blob/master/.github/workflows/gradle.yml
Can anyone help?

**Comment by hohserg1** [comment]
Ok, now I solve cloning multiple repos by using `path`.
But I have a problem with running gradle from inner directory
'cd' command is not work
![image](https://user-images.githubusercontent.com/35610168/96373415-ef15e480-1174-11eb-89c7-71c3c82ad171.png)

**Comment by hohserg1** [comment]
Yeeeeah! Solved! `--project-dir` is cool!

**Comment by orelviz** [comment]
@hohserg1 can you elaborate on how you solved it? Can you share you're `.yml` file?

**Comment by hohserg1** [comment]
@orelviz yes. 
I use a `path` parameter of `actions/checkout` to specify cloning location. 
https://github.com/ElegantNetworking/ElegantNetworkingRoot/blob/master/.github/workflows/gradle.yml#L21
Next I use a `--project-dir` command line parameter of gradle to specify root location of gradle workspace
https://github.com/ElegantNetworking/ElegantNetworkingRoot/blob/master/.github/workflows/gradle.yml#L55
Link to this yml is posted above

**Comment by rdreyer-godaddy** [comment]
@rogerprz  did you get it to work with a repo outside of github.com?

**Comment by blane1988** [comment]
> @rogerprz did you get it to work with a repo outside of github.com?

I am also wondering if we can clone from another domain besides the one where this action is called. In my case, the domain is githubdev.<GitHub Enterprise Name>.com/<org>/<repo>, and I want to clone from regular old github.com.

Currently, this action appends the githubdev domain to the `repo` arg for the action (org/repo) leading to an incorrect full URL.

**Comment by elect86** [comment]
@hohserg1 How did you manage to get the clone persistent?

**Comment by garvit-joshi** [comment]
Can we checkout or clone a gitlab repo?

**Comment by CartBlanche** [comment]
Does anyone have a simple example of using both path and clean: false, when trying to checkout another repo at the same level as the currently building repo?
I'm trying to get this..
/currentdev/currentrepo
/currentdev/../siblingrepo
before then building the project in `currentrepo`.

**Comment by mochadwi** [comment]
> Can we checkout or clone a gitlab repo?

+1 asking a same questions

**Comment by CaseyLabs** [comment]
This is for anyone coming here from a Google search.

If you receive the following error when trying to clone a public git repo with Github Actions (whether it's on Github or Gitlab or elsewhere):

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: unable to connect to github.com:
    github.com[0: 140.82.113.4]: errno=Connection timed out
```

You need to configure git to clone using HTTPS, and not SSH:

`git config --global url.https://github.com/.insteadOf git://github.com/`

Example:

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run shell commands
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/githubtraining/hellogitworld.git
```
