### ISSUE TITLE
[error]fatal: could not read Username

### ISSUE THREAD

**Issue by jinzishuai** [actions/checkout#26]
Hi there,

Without changing anything, my github actions stopped working last night and I got an error of
```
##[error]fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
Does anyone know what is wrong here?

Thank you
Shi

**Comment by TingluoHuang** [comment]
@jinzishuai any link to your check run or repository?
the error means getting 401 from github.com

**Comment by jinzishuai** [comment]
@TingluoHuang  thank you but my repo is a private one so I cannot share that.
But here is a screenshot of what I got.
![image](https://user-images.githubusercontent.com/1074685/63959643-d961cf00-ca49-11e9-84fa-e4d8dd360797.png)

**Comment by jinzishuai** [comment]
magically it is working again. Maybe just some cloud infrastructure problem.

**Comment by TingluoHuang** [comment]
@jinzishuai did you generate a new PAT token for the checkout action?

**Comment by jinzishuai** [comment]
@TingluoHuang  I did try with a newly generated PAT token but that didn't help.
Then half a day later, it started to work again.

**Comment by aaemnnosttv** [comment]
Seeing this today when checking out a wiki for a public repo:

https://github.com/google/site-kit-wp/pull/1168/checks?check_run_id=484311428

Seems like a fluke since this works fine on other runs.

**Comment by Akrog** [comment]
Seeing it as well:

https://github.com/embercsi/ember-csi/runs/615414645?check_suite_focus=true

**Comment by ericsciple** [comment]
@Akrog see this issue: https://github.com/actions/checkout/issues/221

**Comment by Akrog** [comment]
@ericsciple  Thanks, you are right.  The token was revoked and I hadn't noticed. 😅

**Comment by midhuntp** [comment]
@ericsciple  Thanks, Same here also

**Comment by HendrikKlug-synthara** [comment]
I'm having the same problem, all of a sudden the actions stopped working with the same error (since its a private repo I cannot share the link):
![image](https://user-images.githubusercontent.com/94362637/151212227-27c75f8a-e719-4d19-bb2e-ad85f2a67748.png)

The actions were running fine with the organisation secret, which I tried updating but the error persisted:
![image](https://user-images.githubusercontent.com/94362637/151210597-c3d80617-a9fc-4c97-8674-eb8d1397227c.png)

The relevant part in the workflow config is:
```
    steps:
      - uses: actions/checkout@v2

      - name: Checkout M-WDG-Chassis
        uses: actions/checkout@v2
        with:
          repository: synthara/M-WDG-Chassis
          token: ${ secrets.PERSONAL_ACCESS_TOKEN }
          path: M-WDG-Chassis
          ref: development
```

Is there anything I'm doing wrong here?
