### ISSUE TITLE
Is it possible to checkout the whole history since the branch creation?

### ISSUE THREAD

**Issue by leoheck** [actions/checkout#266]
Hello, is it possible to checkout the whole history since the branch creation?
If, yes. How can I do it?

**Comment by ericsciple** [comment]
If you set the input `fetch-depth: 0`, all history for all branches and tags will be fetched.

You can then use `git log origin/master..my-branch` to find all commits in `my-branch` that aren't in `origin/master`.

Does that help? If not can you provide more information about the scenario?

**Comment by leoheck** [comment]
I was able to do it yesterday sometime after my question.
Yes, it was useful. Thank you.

**Comment by ryan-williams** [comment]
It would be nice to fetch just the commits being proposed in a given pull request. Fetching the entire repo history can be quite slow/expensive.

Git lets you clone just the commits between a branch `branch` and upstream `master` like:

```bash
git clone --shallow-exclude master --single-branch --branch branch git@github.com:<org>/<repo>.git
```

Might make sense to reopen this issue to track exposing that functionality in this action.

A related, combination of steps [I've used](https://github.com/runsascoded/nbconvert/blob/0807b9851b3c5ef6643f30fe8b4564965790856e/.github/workflows/main.yml#L12-L19) to have the PR base and head available (but none of the interceding history) is:
```
- name: Check out repository
  uses: actions/checkout@v2  
  with:
    ref: ${{ github.head_ref }}
- name: Add PR base ref
  run: |
  git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
```

That's enough to do e.g. `git diff --name-only <base>..<head>` to see which files have changed as part of a PR, but it doesn't know how many or which commits lie between the two endpoints.

It would be nicei if actions/checkout streamlined this multi-ref use-case (perhaps in a `refs` list?), fetching refs in addition to the one that is ultimately checked out.

Some of these common patterns could even merit their own top-level flags (just the PR history, just the PR endpoints, just the PR head without the merge, etc.).

**Comment by leoheck** [comment]
@ryan-williams Can I use something like your command to initialize submodules behind a private repo? I was not able to achieve this so far.

**Comment by polarathene** [comment]
> but it doesn't know how many or which commits lie between the two endpoints.

You can use the github context to get how many commits belong to the PR, fetch that depth, and a `git fetch` to the other branch will have a common commit identified between the two to fetch roughly what is needed only, instead of full history.

```yaml
- name: 'Checkout PR and all PR commits'
  uses: actions/checkout@v3
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      fetch-depth: ${{ github.event.pull_request.commits }}

- name: 'Fetch the other branch with enough history for a common merge-base commit'
  run: |
    git fetch origin ${{ github.event.pull_request.base.ref }}
    # If the fetch-depth included the commit branched from as the oldest commit, then this should be more specific hint to fetch:
    git fetch --negotiation-tip $(git rev-list --max-parents=0 HEAD) origin ${{ github.event.pull_request.base.ref }}
```

When testing locally, it seemed I had to fetch an extra commit to get the common ancestor between the two branches. If you need to increment the commit a bit more in an action, you can run a shell step earlier to set it as a var:

```yaml
- name: 'PR commits + 1'
  run: echo "pr_commits=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

- uses: actions/checkout@v3
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      fetch-depth: ${{ env.pr_commits }}
```
