### ISSUE TITLE
Failed to checkout submodule

### ISSUE THREAD

**Issue by yinonov** [actions/checkout#271]
Trying to checkout a repo with single submodule in it.

- both repos are part of the same organization
- both repos are private
- organization requires sso and ssh keys to access repos

the workflow fails at the following
```
steps:
  - name: Checkout
     uses: actions/checkout@v2
     with:
       ref: develop
       ssh-key: ${{ secrets.SSH_KEY }}
       submodules: true 
```

the failure message
```
Load key "/home/runner/work/_temp/dc2e5ba9-c8ee-424c-a39b-a15919ec6f72": invalid format
git@github.com: Permission denied (publickey).
##[error]fatal: Could not read from remote repository.
```

Not sure if I miss coded the flow, but it's unclear why I'm not able to access the remote repo with the SSH_KEY

**Comment by MichelBartz** [comment]
This same error is preventing me from relying on `action/checkout@v2` in my workflows and is currently blocking work.

I'm using a self hosted worker which has an already configured git client with ssh access to my organisation's private repos. My workflow is setup as such:

```
      - uses: actions/checkout@v2
        with:
          ssh-key: <path/to/id_rsa>      
```

The `id_rsa` file is 100% valid as tested with `ssh -T git@github.com` with the given output: `Hi <account-name>! You've successfully authenticated, but GitHub does not provide shell access.`

```
  Load key "/home/worker/GoodlordRunner1/_work/_temp/70c9361e-051f-49c4-8db1-f7d66ed077a6": invalid format
  git@github.com: Permission denied (publickey).
```

**Comment by ericsciple** [comment]
> Load key "/home/runner/work/_temp/dc2e5ba9-c8ee-424c-a39b-a15919ec6f72": invalid format

Is `secrets.SSH_KEY` the private key? Is it protected by a passphrase?

For that error, saw some interesting [troubleshooting here](https://superuser.com/questions/1370877/ssh-error-loading-key-id-rsa-invalid-format) throughout the various answers/comments. Especially the ones about different versions of OpenSSL and "Perhaps it has accidentally enabled FIPS mode and refuses any algorithms except those part of its original FIPS validation". It makes me wonder whether you are using a [job container](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer) (may have an insufficient version OpenSSL), if so have you tried on the host machine instead (e.g. `runs-on: ubuntu-latest`)?

**Comment by ericsciple** [comment]
Also if it helps for troubleshooting, I think the following script should mostly preserve the characters accurately and dump the value to disk (havent tested, may need to write an extra line ending?):

```yaml
jobs:
  runs-on: ubuntu-latest
  steps:
    - run: |
        echo "$MY_PRIVATE_KEY" > mykey
      env:
        MY_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
```

Also could try [steps here](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key) to create a new SSH key. Although would need to skip passphrase step
