### ISSUE TITLE
Could not read username error.

### ISSUE THREAD

**Issue by portlek** [actions/checkout#279]
My github action is giving me the error.

![image](https://user-images.githubusercontent.com/12835420/84714476-701a6080-af76-11ea-960b-922af3d37fa0.png)
```yaml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initiate repository
        uses: s4u/maven-settings-action@v2.1.0
        env:
          MAVEN_READ_URL: ${{ secrets.MAVEN_READ_URL }}
          MAVEN_SERVER_ID: ${{ secrets.MAVEN_SERVER_ID }}
          MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}
          MAVEN_SERVER_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
        with:
          servers: '[{"id": "%MAVEN_SERVER_ID%", "username": "%MAVEN_SERVER_USERNAME%", "password": "%MAVEN_SERVER_PASSWORD%"}]'
          properties: '[{"myMavenRepo.read": "%MAVEN_READ_URL%"}]'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          repository: MinecraftHouse/Ppom
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ppom

#      - name: Build with Maven
#        run: mvn install -Dgpg.skip=true -B -ntp --file pom.xml --settings /home/runner/.m2/settings.xml
```
