### ISSUE TITLE
checking out fails on public repo but works on private...

### ISSUE THREAD

**Issue by jeffmcaffer** [actions/checkout#280]
Using the workflow below **fails** if the cited repo (`repository: foo/works-if-private`) is **public** but **works if it is private**. I understand that a token is not "necessary" if the repo is public but in the general case we don't know if the repo is public or private and it may change over time.

```yaml

name: "foo"
on: 
  pull_request:
    branches:
      - master

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get repo
      uses: actions/checkout@v2
      with: 
        repository: foo/works-if-private
        ref: master
        token: ${{ secrets.PAT }}
        path: dest
        persist-credentials: false
```
Here is what appears to be the relevant part of the log (from `Fetching the repository`)
 
```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 18 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
```

**Comment by ericsciple** [comment]
Can you try setting the following env vars so fetch will print more info:

GITHUB_TRACE=1
GIT_CURL_VERBOSE=1

For example:

```yaml
jobs:
  foo:
    steps:
      - uses: actions/checkout@v2
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
```
