### ISSUE TITLE
Checkout@v2 and multiple branches on "push" event

### ISSUE THREAD

**Issue by monocasual** [actions/checkout#288]
I have a workflow configuration like this one:

```
on:
    push:
        branches:
            - master 
            - feature
            - experimental
```
and I would like checkout@v2 to work with all branches. Is it possible for the action to detect which branch the workflow is running on without specifying anything in the `ref` field?
