### ISSUE TITLE
Accessing generated files from the previous job.

### ISSUE THREAD

**Issue by 3mmarg97** [actions/checkout#29]
Hello,
How can I access the files between different jobs?
I have two jobs: Build and Deploy.
The Build job has the following steps:
```yml
    - uses: actions/checkout@master
    - name: Install Packages
      run: npm install
      
    - name: Build dist
      run: npm run build
```

That will generate a new folder called "dist". How can I access "dist" folder contents in the Deploy job?

This is the output of running ls command in the Build job:

![image](https://user-images.githubusercontent.com/16087389/64066746-547fdc80-cc26-11e9-8e59-d0047fd1ce7e.png)

But the Deploy job has only the files in master branch. And doesn't contains the new "dist" folder.
