### ISSUE TITLE
Preserve tag annotations

### ISSUE THREAD

**Issue by martinthomson** [actions/checkout#290]
The technique this tool uses for checking out tags only preserves the relation between tag and ref, not any annotations created with `git tag -a`.

```
git fetch origin +$HASH:refs/tags/$TAG
git checkout -f refs/tag/$TAG
```

I have a CI action that depends on information from annotated tags.  Specifically, the name of the person who applied the tag: `git tag --list --points-at HEAD --format '%(taggeremail)'` (I can't use `${{ github.actor }}` for reasons).

The workaround is to run `git fetch -f origin ${{ github.ref }}:${{ github.ref }}`.  But it would be better not to need this workaround.

**Comment by morrone** [comment]
Agreed! This breaks the "git describe" command too. We need tags to be in their correct original form.

**Comment by martinthomson** [comment]
I realize now that this is complicated by a desire to checkout the specific code identified by the hash when the tag has been re-applied on the repository.  I would be happy to have an option that would cause the checkout to fail if the hash didn't match.

For example:
```
git fetch origin refs/tags/$TAG
[ `git rev-parse refs/tags/$TAG` != $HASH ] || fail
git checkout -f refs/tag/$TAG
```

**Comment by ericsciple** [comment]
@martinthomson does the input `depth: 0` help? It will cause all history for all branches and tags to be fetched?

**Comment by morrone** [comment]
> @martinthomson does the input `depth: 0` help? It will cause all history for all branches and tags to be fetched?

I didn't try 0, but I tried "fetch-depth: 2000" at one point. It fetched the _other_ tags in that history correctly, but if the thing that triggered the workflow was itself an annotated tag, that one tag will still be converted from an annotated tag into a lightweight tag.

**Comment by ericsciple** [comment]
`fetch-depth: 0` triggers a different behavior. Curious if that solves the issue?

**Comment by Stanzilla** [comment]
It does not solve the issue, I ran into this today.

**Comment by andreineculau** [comment]
`fetch-depth: 0` does solve the issue. I don't see how it wouldn't because it fetch all branches, all tags

**Comment by Stanzilla** [comment]
@andreineculau sadly does not.

**Comment by Envek** [comment]
+1 on preserving tag annotations. `fetch-depth: 0` alone doesn't help, `git fetch --tags --force` does help.

```yaml
name: Create release from annotated tag
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Doesn't help
      - name: "Extract data from tag: version, message, body"
        id: tag
        run: |
          git fetch --tags --force # Retrieve annotated tags. THIS TRICK REALLY HELPS
          echo ::set-output name=subject::$(git for-each-ref $GITHUB_REF --format='%(contents:subject)')
          # …
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.tag.outputs.subject }}
```
