### ISSUE TITLE
ssh-key didn't checkout with ssh url

### ISSUE THREAD

**Issue by lunawen** [actions/checkout#291]
Hi,
I've got a simple automated workflow for my static blog, here's my config:

```
- name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
```

- I've got DEPLOY_KEY in my repo's secret, 
- the public key is added to my user settings.
- The workflow can run successful 

**except when I use `git remote get-url origin`, I find it is still an HTTPS url.**
**I would like to have ssh url, is there anything I missed in this config?**

![image](https://user-images.githubusercontent.com/34984218/85948957-2a5a9080-b997-11ea-8e78-49011e8d2a34.png)

Thanks for your help.

Luna

**Comment by ericsciple** [comment]
Is it a fork PR? Secrets aren't available during fork PRs.

**Comment by lunawen** [comment]
Hi Eric, thanks for your reply. It's not a fork PR, it's my private repo.

But today when I check again, it shows the remote url is ssh (hurray!)

The problem now is that, when I manually pull the repo in the remote server, it gives me error.

![image](https://user-images.githubusercontent.com/34984218/86060038-49e0de80-baa7-11ea-8538-6a09f23e07d4.png)

Any idea why is this happening?

**Comment by ericsciple** [comment]
I haven't seen that error before. Are you using a [job container](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer)?

**Comment by lunawen** [comment]
Hi Eric,

Nope, here's my full workflow file, it is a basic one. 

```yml
name: Deploy Site on push

on:
  push:
    branches:
      - master 

jobs:
  deploy: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout Repo 
        uses: actions/checkout@v2 
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server 
        uses: AEnterprise/rsync-deploy@v1.0 
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
          ARGS: -avz --delete 
          SERVER_PORT: "22" 
          FOLDER: ./ 
          SERVER_IP: ${{ secrets.SSH_HOST }} 
          USERNAME: ${{ secrets.SSH_USERNAME }} 
          SERVER_DESTINATION: /var/www/xxx/ 
```

So this ssh error is not expected, right? As the workflow can use it without issue, it only happens when I log in the server and do it manually. Maybe something to do with my user role?
