### ISSUE TITLE
Checking out and combining two branches on gh-pages

### ISSUE THREAD

**Issue by Scipionh** [actions/checkout#293]
I did write the following github action:

```
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: develop
      - name: Generate public directory
        uses: ./.github/actions/generate-public-doc
      - name: Checkout blog
        uses: actions/checkout@master
        with:
          ref: blog
          path: ./public/blog
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: public
```

Despite not having an error, the final result is not correct for the blog folder as it is a symlink. Is there anything I am doing wrongly with the way I did nest the checkout of my second (blog) branch ?
