### ISSUE TITLE
Checking out multiple branches: fatal: ambiguous argument 'master': unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by terencedignon** [actions/checkout#296]
Hi Checkout team,

I'm trying to checkout both the PR branch & master so diffs can be run on the two and only modified files are linted. This returns a fatal error because master is not recognized. I think this PR (https://github.com/actions/checkout/pull/155) addresses the issue, but I'm not sure.

Is there a way to hack around this in the meantime? Thank you!

```
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Config
```
name: Javascript Presubmit

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
      - name: Lint
        # Run ESLint on JS and JSX files that diff from master.
        run: git diff-index --name-only master | grep -E "(.*)\.(jsx|js)$" | xargs npx eslint
```
