### ISSUE TITLE
Failed to checkout@v2 ssh private submodules on windows-latest

### ISSUE THREAD

**Issue by hbursk** [actions/checkout#311]
The follow build steps succeed when using `ubuntu-latest` and `macos-latest`.

```
steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        ssh-key: ${{secrets.XREPO_KEY}}
        submodules: recursive
```

However, they get hung up for hours when using `windows-latest`. The actions eventually time out. 

Is there an alternate method I should use on `windows-latest` to checkout private ssh submodules?

**Comment by yair-mantis** [comment]
i also found this issue. 
using the following action which works on `ubuntu-latest`

```yml
name: CI 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          lfs: 'true'
          submodules: 'recursive'
          ssh-key: ${{ secrets.git_ssh_key }}

        env:
          GIT_CURL_VERBOSE: '1'
          GIT_TRACE: '1'
```

will hang on `git-lfs-authenticate`
```
 trace git-lfs: exec: sh '-c' '"C:\Windows\System32\OpenSSH\ssh.exe" -i "$RUNNER_TEMP/-a80a-4230-a3ab-" -o StrictHostKeyChecking=yes -o CheckHostIP=no -o "UserKnownHostsFile=$RUNNER_TEMP/-a80a-4230-a3ab-26ac44c4f1ac_known_hosts" git@github.com 'git-lfs-authenticate ORG/LFSPackage.git download''
```
