### ISSUE TITLE
Error "Parameter 'commandLine' cannot be null or empty"

### ISSUE THREAD

**Issue by artkonr** [actions/checkout#314]
Hi,

I have encounter an odd error when the ``checkout@v2`` is called from a workflow file. The checkout job fails with

``##[error]Parameter 'commandLine' cannot be null or empty.``

Do you have any idea what might have caused it? Did not find any similar error anywhere, hence the issue. I am using a self-hosted runner installed on Win10. Runner is permanently enabled as a windows service. To setup the actions pipeline I just took the template GitHub recommended and installed it as instructed. Did not change any configs either, apart from adding new workflow steps.

Please, find [log file](https://github.com/actions/checkout/files/4994634/log.txt) and [workflow file](https://github.com/artkonr/guess-game/blob/master/.github/workflows/ci.yml) attached.

**Comment by ericsciple** [comment]
A workaround would be to install git 2.18 or higher on the box (must be in the PATH).

When not installed, the action falls back to downloading a zip of the latest files. It looks like there is an issue trying to extract the zip.

Can you enable [step-debug-logging](https://docs.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-step-debug-logging)?

@thboop heard of this issue before w/ `toolCache.extractZip`?

I'll try to repro on the windows-latest hosted runner (after removing git from the PATH)

**Comment by artkonr** [comment]
Thanks, I'll try both options on the weekends and write back whether it puts things right 👍

**Comment by ericsciple** [comment]
fwiw it works on the hosted runner `windows-latest` for me

Here is my workflow:

```yaml
name: CI
on: push
#  issues:
 #   types: [opened, edited]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Add a fake 'git' to the PATH to force checkout to download zipball instead
        shell: cmd
        run: |
          echo echo hello > git.bat
          echo ::add-path::%CD%
      - uses: actions/checkout@v2
        with:
         path: foo
```

Here is the interesting part from the debug logs (says tar.gz but it's actually a zip file, [here's the code](https://github.com/actions/checkout/blob/592cf69a223b04e75ddf345919130b91010eb2a6/src/github-api-helper.ts)):

```
Deleting the contents of 'd:\a\testing\testing\foo'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Downloading the archive
Writing archive to disk
Extracting the archive
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('d:\a\testing\testing\foo\551bf3d8-acdd-44fa-b70e-b02d40a80975.tar.gz', 'd:\a\testing\testing\foo\551bf3d8-acdd-44fa-b70e-b02d40a80975')"
Resolved version ericsciple-testing-ad7fd6d
```
