### ISSUE TITLE
fatal: You are not currently on a branch.

### ISSUE THREAD

**Issue by bidipeppercrap** [actions/checkout#317]
### config
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Build CSS
        run: npm run build
      - name: Push to GitHub
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Build CSS"
          git push
```

### log
```
Run git config user.name github-actions
  git config user.name github-actions
  git config user.email github-actions@github.com
  git add .
  git commit -m "Build CSS"
  git push
  shell: /bin/bash -e {0}
[detached HEAD 706b5f8] Build CSS
 2 files changed, 2 insertions(+), 2 deletions(-)
 rewrite dist/css/plane.min.css.map (83%)
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

##[error]Process completed with exit code 128.
```

### tried (not working)
```
    fetch-depth: 0
    ref: ${{ github.event.pull_request.head.ref }}
```
```
    fetch-depth: 0
    ref: master
```

**Comment by domgreen** [comment]
I seem to get the same ... I am running on a self-hosted runner that generates files and would like to commit back to the repo but get exactly the same as above.

**Comment by sigute** [comment]
I had same issue running push command in pull request. I managed to dig down into [this old issue](https://github.com/actions/checkout/issues/124#issuecomment-586664611). It seems like the problem is that pull requests are not the same as regular branches, and solution ended up being to add this configuration option to my script:

```
uses: actions/checkout@v2
with:
  ref: ${{ github.event.pull_request.head.ref }}
```

**Comment by gfoligna-nyshex** [comment]
Any news on this one?
I'm getting the same issue even using `${{ github.event.pull_request.head.ref }}`:

```
Error:  To github.com:blah/blah.git
Error:   ! [rejected]        master -> master (non-fast-forward)
Error:  error: failed to push some refs to 'github.com:blah/blah.git'
Error:  hint: Updates were rejected because the tip of your current branch is behind
Error:  hint: its remote counterpart. Integrate the remote changes (e.g.
Error:  hint: 'git pull ...') before pushing again.
Error:  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error:  -> [Help 1]
```

**Comment by ChrisAcrobat** [comment]
_Two years later._
I just had this problem as well, but I'm not working with a pull request. This solved it for me:
```YAML
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
```

**Comment by kunaljubce** [comment]
> I had same issue running push command in pull request. I managed to dig down into [this old issue](https://github.com/actions/checkout/issues/124#issuecomment-586664611). It seems like the problem is that pull requests are not the same as regular branches, and solution ended up being to add this configuration option to my script:
> 
> ```
> uses: actions/checkout@v2
> with:
>   ref: ${{ github.event.pull_request.head.ref }}
> ```

This solution is a life saver. Thanks!

**Comment by Sddilora** [comment]
> > I had same issue running push command in pull request. I managed to dig down into [this old issue](https://github.com/actions/checkout/issues/124#issuecomment-586664611). It seems like the problem is that pull requests are not the same as regular branches, and solution ended up being to add this configuration option to my script:
> > ```
> > uses: actions/checkout@v2
> > with:
> >   ref: ${{ github.event.pull_request.head.ref }}
> > ```
> 
> This solution is a life saver. Thanks!

This also resolved our issue. Thanks a lot.

**Comment by sekedus** [comment]
5 years later..

I also had this problem, but I'm not working with a releases.

This solved it for me:

```
uses: actions/checkout@v4
with:
  ref: ${{ github.event.repository.default_branch }}
```

**Comment by alexandervlpl** [comment]
This should be reopened. Using checkout@v4, `${{ github.ref_name }}` currently does not work for me (it tries to check out an invalid ref). Since my workflow needs to run on `pull_request` but also on `push` and `workflow_dispatch`, I need this hack to handle all cases:

```
    - name: Checkout repo (PR)
      uses: actions/checkout@v4
      if: github.event_name == 'pull_request'
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Checkout repo (branch)
      uses: actions/checkout@v4
      if: github.event_name != 'pull_request'
```
