### ISSUE TITLE
feature request to provide and option to checkout code outside of $GITHUB_WORKSPACE

### ISSUE THREAD

**Issue by iamniting** [actions/checkout#327]
I would like to make a feature request. I wanted to use this action for my project which is written in golang. I want to place my code in the `/home/runner/go` with the `path` option instead of `$GITHUB_WORKSPACE` which is not possible as of today.

Can someone guide me, how we can do that if it is possible? Otherwise, I would request to have a feature for that.

**Comment by intolerance** [comment]
Does setting the `path` not work?

```yml
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: /home/runner/go
```
