### ISSUE TITLE
Using checkout twice, keeping the previous folder

### ISSUE THREAD

**Issue by thewavelength** [actions/checkout#33]
**What do I wanto to achieve?**
I want to deploy the `master`-branch and the `beta`-branch to `gh-pages` at the same time. `master` should go to `gh-pages/` (root folder) and `beta`-branch to `gh-pages/beta`-folder.

**My idea**
Currently I'm using actions/checkout twice (in a single job) with those two different branches. First I do checkout, then `npm install && npm run build`. Works quite well, until the second actions/checkout is executed. This action seems to remove the previous folder including all build results, so I'm unable to move both builds to a `deploy`-folder to finally publish it to `gh-pages`. See parts of my script for details:
```
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checking out master
      uses: actions/checkout@v1
      with:
        ref: master
        path: master
    - name: Build master
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
# at this point, everything from master has been built and is on the filesystem of the runner
    - name: Checking out beta
      uses: actions/checkout@v1
      with:
        ref: beta
        path: beta
# at this point, everything from master seems to be lost in the filesystem
    - name: Build beta
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: deploy/
        GH_PAT: ${{ secrets.GH_PAT }}
```

**Questions**

1. Why is this behaviour? Am I understanding actions/checkout wrong?
2. Is there a better strategy to use to publish multiple things to `gh-pages`?

**Notes**
This idea works when not using actions/checkout but raw `git clone`. I guess that actions/checkout runs in some sort of docker container, which will be burned after operation.

**Comment by TingluoHuang** [comment]
`actions/checkout` has some special logic when it tries to handle the workflow triggering repository, since the triggering repository will become the `GITHUB_WORKSPACE`, so you can't use `checkout` action to make 2 copy of the triggering repository, the workaround I can think of is to write a script to clone/checkout the second copy of your repo.

**Comment by Trimud** [comment]
Shame, I was hoping this is possible...
As a workaround I did the following:
`git clone https://<username>:${{ secrets.GH_TOKEN }}@github.com/<user>/<repo>`

**Comment by fregante** [comment]
Just use 2+ separate jobs, they'll run in parallel too.

**Comment by Trimud** [comment]
You mean in different yml files or in the same action yml file?

**Comment by ericsciple** [comment]
@thewavelength i'm working on a [PR](https://github.com/actions/checkout/pull/70) to fix

will be in actions/checkout@v2 and will hopefully merge early next week

**Comment by gabrieljoelc** [comment]
For anyone else that's a clear answer

Setting the `path` of the second checkout `uses` allowed me to clone the second repo into a sub-directory:
```
- uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: gabrieljoelc/fresh-themes
        path: fresh-themes
    - run: ls
```
build output for the `run`:
```
README.md
default.yml
fresh-themes # <= 2nd repo here
manager.yml
node_modules
package-lock.json
```

**Comment by yasirroni** [comment]
@gabrieljoelc how to add the `run` so that both repository run in parallel?

For example run benchmark on both repository, but ensure both run in the same machine.

**Comment by yasirroni** [comment]
This will run in error
```
    steps:
    # Parallel checkout repository
      # HEAD
      - uses: actions/checkout@v3
        with:
          # ref to HEAD automatically
          path: head
      - name: Print current commit
        run: |
          git rev-parse --short HEAD

      # Ref
      - uses: actions/checkout@v3
        with:
          ref: my_tag
          path: ref
      - name: Print current commit
        run: |
          git rev-parse --short HEAD
```
