### ISSUE TITLE
Checkout action randomly fails on self-hosted runner

### ISSUE THREAD

**Issue by return-tosleep** [actions/checkout#333]
Checkout action randomly fails on self-hosted runner with the following error message: `##[error]No such file or directory`

### My workflow:
```yml
on: push
name: ci
jobs:
  ci:
    name: Run CI
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
```

### Error message on action run

![Screenshot](https://user-images.githubusercontent.com/42698168/90412238-7e960d00-e0ca-11ea-957f-a30fe04ceb72.png)

### Information about self-hosted runner:

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

```bash
$ git --version
git version 2.28.0
```

This issue occurs randomly. Sometimes re-running the action fixes this.
