### ISSUE TITLE
Feature: add support for path as environment variable

### ISSUE THREAD

**Issue by jwillemsen** [actions/checkout#339]
We are using environment variables throughout our scripts to point to the location of the various git repositories we are using. Within our github action we are using for example

```
env:
  DOC_ROOT: ${{ github.workspace }}/ACE_TAO
```

When now using checkout we need to pass ACE_TAO as path but it would be more easier for maintenance that we can use $DOC_ROOT, so 

```
    - name: checkout ACE_TAO
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: ACE_TAO
        ref: Latest_Micro
```

to something like below, refer to DOC_ROOT env

```
    - name: checkout ACE_TAO
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: $DOC_ROOT
        ref: Latest_Micro
```

**Comment by jwillemsen** [comment]
Ok, this seems to work, so the documentation should be enhanced

```
name: linux

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      DOC_ROOT: ${{ github.workspace }}/FOO/ACE
    steps:
    - name: checkout ACE_TAO
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: ${{ env.DOC_ROOT }}
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "FOO/ACE/README.md"
```

**Comment by mtazzari** [comment]
Thanks for posting the working solution! I was surprised that this was not working:
```yml
env:
  BUILD_REPO: owner/repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone build repository
        uses: actions/checkout@v3
        with:
          repository: $BUILD_REPO
```
and using `"$BUILD_REPO"` or `${BUILD_REPO}` or any combination didn't work either. I was getting the following error in GH Actions:
```
Invalid repository '${BUILD_REPO}'. Expected format {owner}/{repo}.
```

However, using contexts works:
```yml
env:
  BUILD_REPO: owner/repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone build repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.BUILD_REPO }}
```
