### ISSUE TITLE
Retrieving the default branch name failed

### ISSUE THREAD

**Issue by poborin** [actions/checkout#347]
An action fails during the checkout action with the following error:
```
Determining the default branch
Retrieving the default branch name
Not Found
Waiting 12 seconds before trying again
Retrieving the default branch name
Not Found
Waiting 13 seconds before trying again
Retrieving the default branch name
##[error]Not Found
```

The checkout action in a workflow is configured as follows:
```yml
      steps:
      # checkout podspec repository
      - uses: actions/checkout@v2
        with:
          repository: Bluedot-Innovation/PointSDK-iOS.git
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
```

However, the same repository with the same configuration has passed an action 21 Apr 2020.

**Comment by billputer** [comment]
I had the same error message, and my issue was that the token holder didn't have read access to the repository I was attempting to access. I was able to fix by granting that user read access. You're trying to access a public repository, so it's not the same issue.

It looks like you just need to remove the `.git` from the end of your repository name. It should read `repository: Bluedot-Innovation/PointSDK-iOS`.

**Comment by poborin** [comment]
Yes, that works! Thank you.

**Comment by TomasVotruba** [comment]
I had a similar problem with public repository. Same error message.

```bash
  steps:
      - uses: actions/checkout@v2
        with:
          repository: ssch/typo3-rector
```

It might help somebody, so I share :))

Where was the problem? We used a composer package name instead of **GitHub repository url**. The latter is the correct one. Basically the repository must be found at `https://github.com/ssch/typo3-rector`.

It took a while to figure out, because "Retrieving the default branch name failed" lead me to assumption the repository was found corretly.


This was the fix:

```diff
  steps:
      - uses: actions/checkout@v2
        with:
-         repository: ssch/typo3-rector
+         repository: sabbelasichon/typo3-rector
```

**Comment by dhamo-pk** [comment]
I now have the same error message. I am in a repo1 (that is where I have this workflow file) and trying to pull repo 2 (both are in the same orgn1) from repo 1 with the following code:

```
# Checkout UI repo 
    - name: Checkout voy-frontend repo
      uses: actions/checkout@v2
      with:
        repository: Orgn1-Global/voy-frontend
        path: develop
        github-token: ${{ github.token }} 
```
From the below error, I assume that without the token also, it is able to locate the repository but only has a problem in locating the branch. Is this correct? 
```
Warning: Unexpected input(s) 'github-token', valid inputs are ['repository', 'ref', 'token', 'ssh-key', 'ssh-known-hosts', 'ssh-strict', 'persist-credentials', 'path', 'clean', 'fetch-depth', 'lfs', 'submodules']
Run actions/checkout@v2
Syncing repository: Orgn1-Global/voy-frontend
Getting Git version info
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Determining the default branch
  Retrieving the default branch name
  Not Found
  Waiting 17 seconds before trying again
  Retrieving the default branch name
  Not Found
  Waiting 12 seconds before trying again
  Retrieving the default branch name
  Error: Not Found
```
and what's the right way to pull the 'main' branch of repo 2 from this repo 1.

**Comment by davewichers** [comment]
I have the same problem as @dhamo-pk.  Seems like you should be able retrieve a specific branch (main in this example), by either doing this:

repository: Orgn1-Global/voy-frontend@main

or

repository: Orgn1-Global/voy-frontend
branch: main

But neither works/seems to be supported.  When I go to MY project and look at it in github it says under Settings / Branches / Default branch - main.  (Is the default branch).

So seems to me like I shouldn't have to try to specify the branch as 'main' since that is already the default. If it is a permissions issue, then it would be much better if 'Retrieving the default branch name' said there was a Permissions error, rather than just 'Not Found'. HOW/WHY is the default branch name 'not found'. Can this actions/checkout@v2 action script be improved to explain WHY?

**Comment by isner** [comment]
I was also confused by this error and didn't realize at first that it was an access issue. Leaving my experience here in case it benefits someone in the future.

In my case, I was moving my workflow to a separate repo to take advantage of the [reusable workflow](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) functionality, not realizing that the `${{ secrets.GITHUB_TOKEN }}` generated by the new "called" workflow wouldn't grant access to the repository that the old "caller" workflow was checking out.

My solution was simply to pass a valid token from the caller workflow to the called workflow [as a named secret](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow).

**Comment by migounette** [comment]
FYI, I dig a little bit and I found the following issue...
For my understanding it seems to be linked to the ${{ secrets.GITHUB_TOKEN }} itself, as the token expires when done, it appears that there is a bug in the engine. Even if it not recommended I tried to use my PAT (Personal Access Token) and it works....

You need a copy in the settings/secrets/new repository secret
eg. MY_PAT
```
      - name: Check out somehting cool
        uses: actions/checkout@v3
        with:
          repository: <your repo>/<your projet>
          token: ${{ secrets.MY_PAT }}
          path: <your path>
```

I need to find a way to report it to Github... ? any idea of which project to be used ?

**Comment by barywhyte** [comment]
I am having this problem right now too. Attempting to pull down repo2 from repo1 with git action workflow. Both repos are private and within the same organisation. I am using PAT as token
```
 # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: myOrg/myRepo
          token: dfdgdgdgdggdd
          path: master
```

Error:
```
Retrieving the default branch name
  Bad credentials
  Waiting 17 seconds before trying again
  Retrieving the default branch name
  Bad credentials
  Waiting 10 seconds before trying again
  Retrieving the default branch name
  Error: Bad credentials
```

Is this really working for anyone at all?

**Comment by f1lander** [comment]
> 

But what does mean `sabbelasichon` ?

**Comment by darrenvechain** [comment]
> 

Same problem here

> I am having this problem right now too. Attempting to pull down repo2 from repo1 with git action workflow. Both repos are private and within the same organisation. I am using PAT as token
> 
> ```
>  # Checkout the repository to the GitHub Actions runner
>       - name: Checkout
>         uses: actions/checkout@v3
>         with:
>           repository: myOrg/myRepo
>           token: dfdgdgdgdggdd
>           path: master
> ```
> 
> Error:
> 
> ```
> Retrieving the default branch name
>   Bad credentials
>   Waiting 17 seconds before trying again
>   Retrieving the default branch name
>   Bad credentials
>   Waiting 10 seconds before trying again
>   Retrieving the default branch name
>   Error: Bad credentials
> ```
> 
> Is this really working for anyone at all?

**Comment by migounette** [comment]
Several possibilites when PAT does not work
- Insure that the token in use has the right level of credentials to checkout your projects
https://docs.github.com/en/actions/security-guides/automatic-token-authentication
- In order to validate the token, try to git clone with your credential <your user name> <your crendential>

**Comment by synth** [comment]
For us, it was also proper credentials! We needed a minimum of these 3: `read:user, repo, user:email`. We tried with with just `read:user, repo` and that failed with this same error. Once we added `user:email` to the token scopes, it worked! Also, note, this is with "Classic" tokens. We couldn't get it to work with the new "Beta" Fine Grained Tokens.

**Comment by rafaelrezend** [comment]
Just in case it helps. I was having this exact issue. Tried renewing the token and giving full access, but nothing worked.
In the end, what worked for me was to specify the branch explicitly (`ref`), like

```
 # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: myOrg/myRepo
          ref: 'main'
          token: dfdgdgdgdggdd
          path: master
```

The `Bad credentials` message is strange, if not misleading. Access to the repository is granted, but for some reason my Workflow was unable to retrieve specifically the default branch name, which I confirmed to be set as expected.

> Retrieving the default branch name
>   Bad credentials
>   Waiting 17 seconds before trying again
>   Retrieving the default branch name
>   Bad credentials
>   Waiting 10 seconds before trying again
>   Retrieving the default branch name
>   Error: Bad credentials
