### ISSUE TITLE
Submodules from private repositories

### ISSUE THREAD

**Issue by chorrell** [actions/checkout#35]
Apologies if this has already come up...I haven't been able to find an answer to this.

I'm attempting to setup Actions for a private GitHub repo. The repo pulls in two submodules, each of which are also private GitHub repos. My Action fails on checkout with `##[error]fatal: Could not read from remote repository.`

How do I configure the **checkout** action with the right credentials to pull in these private submodules?

This is what I currently have for the checkout step as a starting point:

```
    - uses: actions/checkout@v1
      with:
        submodules: true
```

**Comment by thorker** [comment]
I think u need #14 

```
- uses: actions/checkout@v1
   with:
        submodules: true
        token: ${{ secrets.CI_TOKEN }}
```

CI_TOKEN is a workflow secret & a personal access token, u can configure in the settings section.

**Comment by chorrell** [comment]
Oh! Perfect thanks, that solved my issue :)

**Comment by bernardolm** [comment]
You can use too:
```yaml
    - name: Fix up git URLs
      run: git config --global --add url."https://${{ secrets.GITHUB_SECRET }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      run: git config --global --add url."https://${{ secrets.GITHUB_SECRET }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"
```
