### ISSUE TITLE
clean submodule

### ISSUE THREAD

**Issue by GongT** [actions/checkout#358]
When `clean: true`, during `Cleaning the repository`, it will do:
```
git clean -ffdx
git reset --hard HEAD
```

When `submodules: true` or `submodules: recursive`, I want it also do:
```bash
git submodule foreach [--recursive] git clean -ffdx
git submodule foreach [--recursive] git reset --hard
```

**Comment by Hish15** [comment]
Hello,

Why is this still open? This is a big deal!
It's not possible to have a reliable CI without the mean to clean the submodules when checking-out.

**Comment by OscarVanL** [comment]
I ran into this issue recently. For me, a file in a submodule got modified by a previous run and then was present in the next run, causing issues.

It would be nice if this got merged so I can have reliable CI without adding hacks.

This was my workaround by the way:
```
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Submodule cleanup fix  # Bodge for https://github.com/actions/checkout/issues/358
        run: |
          git submodule foreach --recursive git clean -ffdx
          git submodule foreach --recursive git reset --hard
```
