### ISSUE TITLE
[error]fatal couldn't find remote ref

### ISSUE THREAD

**Issue by rster2002** [actions/checkout#36]
I'm having issues when using actions/checkout. When it runs, I get
`##[error]fatal: couldn't find remote ref refs/pull/217/merge`

The line can (and full log) can be found [here](https://github.com/rster2002/rster2002.github.io/commit/2de8d4216d05897d72839c0a1e535340e2a74279/checks#step:2:18).

The action itself is called [node-swn-build](https://github.com/rster2002/rster2002.github.io/blob/master/.github/workflows/node-swn-build.yml).

Do I miss some config?

Thanks in advance!

**Comment by jofftiquez** [comment]
Same problem here

![image](https://user-images.githubusercontent.com/8638243/64632334-7437b180-d42b-11e9-8e77-1c73dce47a79.png)

```yml
name: Deploy

on: 
  pull_request:
    branches:
      - master

jobs:
  deploy_to_live:
    name: Deploy prod hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install yarn
        run: npm install yarn@latest -g
      - name: Install dependencies
        run: yarn
      - name: Run build
        env: 
          VUE_APP_API: ${{ secrets.VUE_APP_API }}
          VUE_APP_CMS_URL: ${{ secrets.VUE_APP_CMS_URL }}
          VUE_APP_ENV: ${{ secrets.VUE_APP_ENV }}
          VUE_APP_SIGNIN_URL: ${{ secrets.VUE_APP_SIGNIN_URL }}
        run: yarn build
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn deploy:prod

```

**Comment by TingluoHuang** [comment]
did you guys merged your PR before the action workflow start running? the error means the pull request merge ref is not there anymore.

**Comment by rster2002** [comment]
Oh, uhm... maybe...

**Comment by jofftiquez** [comment]
@TingluoHuang wow. I thought `pull_request` means after the PR has been merged. How do I do that? I want to workflow to run after the PR has been merged to master? Thanks.

**Comment by TingluoHuang** [comment]
i think it might be
``` yaml  
on: 
  push:
    branches:
    - master
```
