### ISSUE TITLE
fatal: not a git repository when using checkout@v2

### ISSUE THREAD

**Issue by DannyFriedmanQC** [actions/checkout#363]
I am trying to run git commands in an action using checkout@v2 but I am getting the error

`fatal: not a git repository`

My yaml looks like the following 

```
name: name
on: [push, pull_request]
jobs: 
  some_job:
    name: some_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: some_name
         run: |
           git status
 ```

**Comment by GMNGeoffrey** [comment]
I'm experiencing something similar with my action that tries to `git pull --ff-only origin master` from within a submodule. I get an intermittent error

https://github.com/GMNGeoffrey/llvm-bazel/runs/1201180187
https://github.com/GMNGeoffrey/llvm-bazel/runs/1201199207
https://github.com/google/llvm-bazel/runs/1180737413
https://github.com/google/llvm-bazel/runs/1130264635
https://github.com/google/llvm-bazel/runs/1114116468

**Comment by chenrui333** [comment]
@DannyFriedmanQC can you attach your reference run (if possible)?

I have seen such errors before, I think it is more like github action performance issue.

**Comment by HebaruSan** [comment]
Seeing the same. No `.git` directory is created. Checked with a `ls -la` in the workflow to see what is there.

https://github.com/HebaruSan/NetKAN/runs/1534015545?check_suite_focus=true

```
total 168
drwxr-xr-x 5 1001  116   4096 Dec 10 23:14 .
drwxr-xr-x 6 root root   4096 Dec 10 23:14 ..
drwxrwxr-x 3 root root   4096 Dec 10 23:05 .github
-rw-rw-r-- 1 root root     50 Dec 10 23:05 .gitignore
-rw-rw-r-- 1 root root    210 Dec 10 23:05 .travis.yml
-rw-rw-r-- 1 root root   6502 Dec 10 23:05 LICENSE.md
drwxrwxr-x 3 root root 135168 Dec 10 23:05 NetKAN
-rw-rw-r-- 1 root root   1241 Dec 10 23:05 README.md
drwxrwxr-x 2 root root   4096 Dec 10 23:05 bin
```

**Comment by dopey** [comment]
Just wanted to add my voice and say that I'm seeing the same thing.

**Comment by HebaruSan** [comment]
After reading #335, removing this fixed it for me:

```yaml
       container:
           image: ubuntu:latest
```

Somehow this was causing the wrong version of `git` to run. I don't pretend to understand why.

**Comment by rudolfbyker** [comment]
I'm also seeing this when using self-hosted runners on Windows Server. No .git directory is created. This causes all sorts of issues.

**Comment by DaniBencz** [comment]
> After reading #335, removing this fixed it for me:
> 
> ```yaml
>        container:
>            image: ubuntu:latest
> ```
> 
> Somehow this was causing the wrong version of `git` to run. I don't pretend to understand why.

I don't understand it either, but removing my custom container from the job helped in my case, thanks!

**Comment by morlowska** [comment]
Removing
```
       container:
           image: …
```
isn’t solution here. If you remove this code, workflow will be run on your self-hosted machine itself, not in the container. It seems to work because on your machine you must have newer version of Git.

> Ah, I see there is a subtle warning message:
> 
> ```
> The repository will be downloaded using the GitHub REST API
> To create a local Git repository instead, add Git 2.18 or higher to the PATH
> ```
> 
> 🤔
> 
> Edit:
> 
> See #325

according to this warning Git version should be higher than 2.18. So the real solution is to upgrade Git inside of your container’s image. Also there is another dirty workaround - after _actions/checkout@v2_ step run _git init_:
```
name: name
on: [push, pull_request]
jobs: 
  some_job:
    name: some_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git init
      - name: some_name
         run: |
           git status 
```
but this initialize _empty_ repository - git commands will work, but there will be no information about remote repository.

**Comment by petronny** [comment]
@jorgesolebur Try ``git config --global --add safe.directory $(realpath .)`` before any other git operations.

**Comment by dai-mk** [comment]
What worked for me was, installing `git` in the container, `fetch-depth: 1` and `git config --global --add safe.directory "$GITHUB_WORKSPACE"`

**Comment by milesvdw** [comment]
I'm also having this trouble, it's infuriating. A simple command like 
`git status` fails when run after checkout v2. 

Some additional info:
- I'm using a custom built docker image, which is really just ubuntu-latest plus some apt-gets
- My git version (confirmed by running git --version directly before git status) is 2.37.2
- I'm definitely IN a git repo, I can see literally everything from my repo plus meta info like a .git folder full of stuff, including HEAD

**Comment by knocte** [comment]
My workaround was replacing `uses: actions/checkout@v2` with `uses: actions/checkout@v1`.

**Comment by seyuf** [comment]
@petronny your suggestion is working for  lots of people, myself included. Care to explain why?
BTW i get the same result when i run `chown -R root:root` instead of `git config --global --add safe.directory $(realpath .)`
Previously i noticed the .git permission was: 
```drwxr-xr-x  8 1001  123 4.0K Jan 19 18:17 .git```

**Comment by seyuf** [comment]
Looks like this is the explanation ? https://github.com/actions/checkout/issues/766

**Comment by striezel** [comment]
For those of you using container images in their workflows, remember that many smaller container images do not have Git installed by default. So `actions/checkout` cannot use Git in those cases, unless you install it **before** the `actions/checkout` step.

So the basic idea for container workflows should be:
1. Install Git. (`apt-get install git` / `yum install git` / `apk add git` / ...)
2. Inside the container run `git config --global --add safe.directory "$GITHUB_WORKSPACE"` once before any other `git` commands are used.
3. Run `actions/checkout`. If you need the full Git history with tags, etc, also use `fetch-depth: 0`.
4. Run your `git ...` commands.

The workflow should look like this (using Alpine Linux container here as an example):
```yaml
name: Alpine
on: push
jobs:
  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      # Git is required so that actions/checkout does a proper Git checkout
      # instead of using the GitHub REST API.
      - name: Install Git in container
        run: |
          apk update
          apk add git
          # one time fix to avoid permission problems later on
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      # Now the git commands can be used.
      - run: |
          git status
          git log -3
          ...
```
