### ISSUE TITLE
Checkout not respecting .lfsconfig

### ISSUE THREAD

**Issue by CEbbinghaus** [actions/checkout#365]
When Cloning a Repository that uses a third party lfs server it still tries to pull from github's lfs

Action:
```yaml
- name: Checkout repository
  uses: actions/checkout@v2
  with:
    lfs: true
    ref: Release
```

.lfsconfig:
```
[remote "origin"]
	lfsurl = /*Remote url*/
```

output:
```
fetch: Fetching reference refs/remotes/origin/Release
..
..
Error: error: failed to fetch some objects from '/*Repository Url*/'
```

It would be nice if either a Settings for the `lfs-url` were to be exposed or it would simply read the .lfsconfig file and use the provided one. 👍
