### ISSUE TITLE
exclude specific files from being deleted

### ISSUE THREAD

**Issue by aman-koco** [actions/checkout#377]
I am having a problem, whenever my GitHub action executes successfully, the `.env` file is deleted, and thus my application breaks. Is there a way where we can exclude some files or any other way.

Below is my workflow file - 

`
  
    name: KS Backend Beta Deployment
    on   
    push:
    branches:
        - staging
    jobs:
       build:
       runs-on: self-hosted

    strategy:
      matrix: 
        node-version: [10.16.0]

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Restart the application
        run: pm2 restart {APP_NAME}
`

**Comment by Asmitta-01** [comment]
I have the same issue. A current workaround is to disable the `clean` option and clean it manually we can thent exclude what we what.

```yml
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          clean: false

      - name: Manual cleaning excluding secrets files
        run: git clean -ffdx -e .env.prod.local -e .env.*.local
```
