### ISSUE TITLE
Github token not updated automatically to the secret one

### ISSUE THREAD

**Issue by apgapg** [actions/checkout#382]
This following doesn't set TOKEN as GITHUB_TOKEN
```
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
```

Hence i then use fregante/setup-git-token although its deprecated to set new token to GITHUB_TOKEN

The following sets TOKEN as GITHUB_TOKEN
```
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.TOKEN }}
```

I think the token isn't automatically set as mentioned in docs
