### ISSUE TITLE
actions/checkout@v2 fails on self-hosted RHEL 7 runner with "fatal: could not read Username for 'https://github.com': No such device or address"

### ISSUE THREAD

**Issue by citnfm** [actions/checkout#397]
## System Information
- OS Version: RHEL 7.9 (Maipo)
- Git Version: 2.29.2
- Repo Access: Private

## Steps to reproduce
1. Install the Github Actions self-hosted runner service on a CentOS/RHEL 7 host.
2. Create a simple workflow to checkout out the repo that initiated the run.
```
name: Checkout via Github Actions Test
on:
  push:
jobs:
  self-hosted-checkout-test:
    runs-on: self-hosted
    steps:
    # Force a clean up of any files left by a previous run.
    # Required since Actions will not do this for you.
    - name: Clean up files from the previous run
      run: rm -rf ./*

    - name: checkout repo to runner
      uses: actions/checkout@v2
```
3. Run the workflow.

Result: `Error: fatal: could not read Username for 'https://github.com': No such device or address`

## Troubleshooting steps taken
- Provide a PAT from a user that has access to the repo using (example below). Same result.
```
    - name: checkout repo to runner
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_PAT }}
```
 - Cloning the repo manually using a PAT in the workflow. This works.

Any advice on how to make this work or am I stuck using a traditional `git clone` in my workflow?
