### ISSUE TITLE
submodule recursive fails

### ISSUE THREAD

**Issue by aminya** [actions/checkout#402]
Here is the error:

https://github.com/aminya/build2-toolchain/runs/1506543807?check_suite_focus=true#step:6:182
```
  Error: fatal: dumb http transport does not support shallow capabilities
  Error: fatal: clone of 'http://git.sv.gnu.org/r/config.git' into submodule path '/home/runner/work/build2-toolchain/build2-toolchain/build2/config' failed
```

Here is the config:
https://github.com/aminya/build2-toolchain/blob/a0d6e01cb63abca5250981084a7f03c0fa5f2856/.github/workflows/ci.yml#L56
```
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        repository: 'build2/build2-toolchain'
        submodules: recursive
```
