### ISSUE TITLE
Accept env var in 'path'

### ISSUE THREAD

**Issue by cliffordp** [actions/checkout#406]
I want to pass an env var to the 'path' arg for this GitHub Action... but it does not interpret it:

![image](https://user-images.githubusercontent.com/1812179/102005256-0983be80-3cdd-11eb-837e-aab536e94994.png)

**Comment by ericsciple** [comment]
You may need to use a step output. There is an [example here](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions)

```yaml
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
```
