### ISSUE TITLE
workflow creates incorrect directory

### ISSUE THREAD

**Issue by madneal** [actions/checkout#414]
I have created a [workflow](https://github.com/madneal/gshark/blob/master/.github/workflows/go.yml) with the usage of `setup-go`:

```
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
```

The problem is the directory created by the workflow. It creates the directory of the repository as `home/runner/work/gshark/gshark` with repeate names of my project which expected to be `home/runner/work/gshark`. I am not sure if this is a bug or any other configuration to address this.

![image](https://user-images.githubusercontent.com/12164075/103514280-46d80800-4ea7-11eb-8780-edde25fb814f.png)

Thanks in advance.
