### ISSUE TITLE
Optimise fetching all commits in a pull request

### ISSUE THREAD

**Issue by kellyselden** [actions/checkout#416]
My goal is to lint all commit messages in a pull request, or in other words, since branching off the default branch. My workaround is

```yml
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        # otherwise it is missing locally
        ref: ${{ github.base_ref }}
    - run: git checkout ${{ github.head_ref }}
```

but for large repos, it would be nice if this action could do the smart thing and only fetch what is needed. Thanks in advance.
