### ISSUE TITLE
Submodule cloning: Needed a single revision

### ISSUE THREAD

**Issue by Flusinerd** [actions/checkout#418]
**Problem:**
Pipeline failing to clone submodule.
![image](https://user-images.githubusercontent.com/22977969/103777832-bd087600-5031-11eb-827b-f6ee5432f334.png)

**Environment:**
Both the main repository and submodule are private repositories belonging to the same organisation. I am the owner of the organisation and I have created a PAT with full repo access. This PAT is then added as secret the the main repository.

**Pipeline Config:**
```yml
build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_PAT }}
        submodules: true
        persist-credentials: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
```

**Self-Hosted:**
I am running the pipelines on two of our servers. Both have docker installed and I dont have issues with any other repository that does not include any submodules.

**Comment by NotMyself** [comment]
Did you ever find a solution to this issue?

**Comment by Flusinerd** [comment]
Hey, I believe not. We moved to a monorepo.

**Comment by NotMyself** [comment]
Well, if you ever run into it again. This is what worked for me. Note the first step does not get submodules a tall.... The second step does though.

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        token: ${{secrets.TEMPLATE_REPO_PAT}}
        submodules: true
        persist-credentials: true
    - name: Checkout submodules using a PAT
      run: |
        git config --file .gitmodules --get-regexp url | while read url; do
          git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.TEMPLATE_REPO_PAT }}:${{ secrets.TEMPLATE_REPO_PAT }}@github.com\//")
        done
        git submodule sync
        git submodule update --init --recursive
```
