### ISSUE TITLE
##[error]/github/workspace can not be a rooted path.

### ISSUE THREAD

**Issue by rberlind** [actions/checkout#42]
I get the error:
```
##[error]/github/workspace can not be a rooted path.
```

when using  a workflow.yml that looks like this:
```
name: sentinel-test-gcp
on:
  pull_request:
    branches:
      - master
    paths:
      - 'sentinel-policy-sets/gcp/**'

jobs:
  sentinel-test-gcp:
    runs-on: ubuntu-latest
    steps:
      # This step checks out the repository's code
      - name: checkout-code
        uses: actions/checkout@master
      # This step runs `sentinel test` against the GCP policies
      - name: sentinel-test-gcp
        uses: rberlind/sentinel-policy-sets-for-tfc@master
        with:
          args: ./sentinel-policy-sets/gcp
        env:
          STL_ACTION_WORKING_DIR: './sentinel-policy-sets/gcp'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
I get the same thing if I use `uses: actions/checkout@v1`

**Comment by rberlind** [comment]
The full output for the checkout action for v1 is:
```
checkout-code
Run actions/checkout@v1
  with:
    path: /github/workspace
    clean: true
##[error]/github/workspace can not be a rooted path.
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.158.0/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.CheckoutTask, Runner.Plugins"'.
```

**Comment by rberlind** [comment]
It seems to work if I remove the -name before the checkout uses:
```
    steps:
      # This step checks out the repository's code
      - uses: actions/checkout@master
```
And that is how most examples show it, but it seems that I should be able to assign a name to the step and still have the action work.

The output now shows "Run actions/checkout@master" instead of "checkout-code" for the name of the step in the GitHub Action workflow status.

**Comment by pirate** [comment]
We also cant seem to get it working with an absolute path:

```yml
name: Example Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          path: /opt/exampleproj

      - name: Run script
        run: ./example-script --path=/opt/exampleproj/config.json   # this command requires an absolute path (relative doesn't work), which is why we specify it above
```
