### ISSUE TITLE
checkout@v2 doesn't allow `git diff origin/master`

### ISSUE THREAD

**Issue by wdanilo** [actions/checkout#438]
Hi, I have such a step in my actions config:

```
    name: Get list of changed files
    id: changed_files
    run: |
        list=`git diff --name-only origin/master HEAD`
        echo $list
        echo "::set-output name=list::$list"
    shell: bash
```

When using `checkout@v1` it works, while with `checkout@v2` I get

```
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
```

**Comment by skovhus** [comment]
If you want to `git diff` to work, then you need to fetch more than 1 commit (which is the default) for `checkout@v2`. By setting the `fetch-depth` to 0, you will fetch the entire git history:

```
 - uses: actions/checkout@v2
    with:
      fetch-depth: '0'
```

See more: https://github.com/actions/checkout#checkout-head

**Comment by ljharb** [comment]
@skovhus wouldn't a better default for a PR be to fetch whatever commits are needed to include the PR base?

**Comment by skovhus** [comment]
> @skovhus wouldn't a better default for a PR be to fetch whatever commits are needed to include the PR base?

If possible yes. Please share if you know how to do that with `actions/checkout@v2`.

**Comment by ljharb** [comment]
ah sorry, i assumed you were a maintainer.

I don't think it's something we can configure; i think it's something that the checkout action would have to do, by first making a call to the github API, to figure out the requisite fetch depth.

**Comment by Vasfed** [comment]
In PRs usually required depth is `fetch-depth: ${{ github.event.pull_request.commits + 1}}`
but math is not supported inside `${{}}`

**Comment by kolyshkin** [comment]
I found out that that if you want something like `git diff origin/master`, you can do so with

```yml
- uses: actions/checkout@v3
   with:
    fetch-depth: 2
  - run: git diff HEAD~1
```

This works because the last commit being fetched is the merge commit (somehow created by github) which shows the full diff for the PR.

**Comment by JohnStarich** [comment]
This worked for me:
```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: checkout
      run: |
        commits=${{ github.event.pull_request.commits }}
        if [[ -n "$commits" ]]; then
          # Prepare enough depth for diffs with master
          git fetch --depth="$(( commits + 1 ))"
        fi
```
For some actions, the diff is a rich source for data analyses. While this works, I'd love a built-in option (or default) to fetch the current PR's history.
