### ISSUE TITLE
checkout@v2 not getting recent commits

### ISSUE THREAD

**Issue by adnan-kamili** [actions/checkout#439]
Assume a Github action with two Jobs - job1 & job2

In job1: 
Use checkout action to checkout the repo, update any file in the repo, commit and push the changes.

In job2:

Again use checkout action. The repo doesn't contain the commit made in job1.

Here is a replicable sample:
```yaml
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |  
          // update file1.txt
          git add file1.txt
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git commit -m "updated file1"
          git push
        
  deploy:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cat publish file
      run: |
        # the changes made in job1 are not reflected here
         cat file1.txt
```

**Comment by jcharnley** [comment]
what error code is it giving you, something has changed with my pipeline and not sure what the issue is

**Comment by adnan-kamili** [comment]
I don't get any error, the checkout succeeds but it doesn't get the latest commits. Seems to use some sort of cache. As a workaround I am doing the following:

- uses: actions/checkout@v2
- run: git pull origin master

**Comment by vmehra-pcln** [comment]
I ran into the same issue. I have 2 jobs: 
Job-1: actions/checkout@v2, modify a file, commit the file, push the file

Job2: actions/checkout@v2

It doesn't error out but it does log below which shows the last commit pushed within Job-1 is not there.

```
Checking out the ref
  /bin/git checkout --progress --force -B project-name refs/remotes/origin/project-name
  Warning: you are leaving 1 commit behind, not connected to
  any of your branches:
```
As a workaround, I had to do `- run: git pull --no-rebase` (similar to what @adnan-kamili mentioned above)

**Comment by punksta** [comment]
Same here
```
git checkout --progress --force 29289099907df8d8600cf5c8f58bab9a15dcaac8
Error: fatal: reference is not a tree: 29289099907df8d8600cf5c8f58bab9a15dcaac8
Error: Git checkout failed with exit code: 128
Error: Exit code 1 returned from process: file name '/home/runner/runners/2.277.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```

**Comment by sebastian-muthwill** [comment]
I ran into the same problem and came across this issue. But could figure out a solution within the documentation.

```
# The branch, tag or SHA to checkout. When checking out the repository that

    # triggered a workflow, this defaults to the reference or SHA for that event.
    # Otherwise, uses the default branch.
    ref: ''
```

This means by default the commit where the workflow was triggered will be taken. You can specify the master branch with
`ref: 'master'`

**Comment by brianpham** [comment]
Running into the same issue. We should be able to do a checkout again without needing to specific the ref in dispatch workflow. 

Dispatch Workflow starts off with checking out branch (2)

1. Checkout branch (1)
2. Create new branch (2) off branch (1)
2. Force push branch (2) 
3. Checkout branch (2)

Step 3 seems to be pulling an old branch git sha.

**Comment by brianpham** [comment]
Oh maybe this is normal behavior? According to this https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

If I check out branch (2) it will use the last github_ref. So even if I update the branch (2) and run step 4, it will still pull the older branch. Can someone help confirm?

**Comment by mugbug** [comment]
I had a similar issue, while trying to use `standard-version` to generate the changelog with previous commits. The problem was that it wasn't fetching the commit history and only the last commit was available. I was able to solve this by running this command, which forces the commit history to be fetched:
```
git fetch --prune --unshallow
```

**Comment by restfulhead** [comment]
As @sebastian-muthwill mentions, you can use the `ref` attribute to point to a specific branch. This way subsequent jobs always pull the latest code from that branch, and not from the revision that started the workflow.

@mugbug I think `fetch-depth: 0` is your friend.

Here's a full example that works for me when running multiple jobs that each generate a change-log file (i.e. modify the branch)

```
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
```

@adnan-kamili Does this solve your issue?

**Comment by kuriel-trivu** [comment]
Problem persists, last changes are not being taken from `actions/ckeckout@v2`.

**Comment by Farrukhbek00** [comment]
In my case, S3 bucket on AWS was cached and was updating cached files in folder, I deleted project folder on aws s3, and ran github action again, hope it helps

**Comment by rockymountainhigh1943** [comment]
The solution from @restfulhead fixed my issues. It was the missing `ref: main`.

**Comment by LastDragon-ru** [comment]
`ref` doesn't work for me :(

![image](https://user-images.githubusercontent.com/1329824/183241259-c2d7e1d4-f6da-4698-b0f0-4ce94ef7e9d6.png)

**Comment by baiyyee** [comment]
Got the same issue too. Steps as below:
1. create new action workflow, we have .github/workflows/xxx.yml here.
2. run workflow, and it's failed due to any wrong config within  .github/workflows/xxx.yml
3. delete workflow and remove .github/workflows/xxx.yml
4. do the same with step 1 - 3, but fix the wrong config with  .github/workflows/xxx.yml
5. run worflow agin, it's failed again

During the error log, it's also take v1 config file as reference and ignore the updated one

**Comment by jlarsen-usgs** [comment]
Having the same issue with actions/checkout@v3. The checkout function is pulling the most recent version of the repository for windows and macos, but not for ubuntu-latest. 

It is pulling an older version of the repository for the ubuntu-latest runner and because of this my linux tests are failing.

**Comment by vicary** [comment]
`fetch-depth: 0` worked for me, `ref:` is irrelevant in my case.

**Comment by vincerubinetti** [comment]
I have a Jekyll website. I'm calling two reusable workflows one after the other with `needs` on `pull_request` activity (it has to be set up this way for other reasons). The first one makes some changes then commits some files with `stefanzweifel/git-auto-commit-action`. The second one checks out the code again and builds a preview of the site with `rossjrw/pr-preview-action`.

No matter what I try, I can't get the second workflow to have the commit made from the first one. I've tried permutations of `fetch-depth`, `ref`, [this](https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit), etc. 

Anyone know what I could be missing? Maybe there's some GitHub limitation I'm running into, like how commits from a workflow can't trigger another workflow. Maybe I shouldn't be checking out the code again in the second workflow?

**Comment by shinebayar-g** [comment]
> Having the same issue with actions/checkout@v3. The checkout function is pulling the most recent version of the repository for windows and macos, but not for ubuntu-latest.
> 
> It is pulling an older version of the repository for the ubuntu-latest runner and because of this my linux tests are failing. Tried many of the suggestions above, none have worked to fix this issue.

can't reproduce this.

```yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: main
```

worked as expected.

**Comment by jascodes** [comment]
> Having the same issue with actions/checkout@v3. The checkout function is pulling the most recent version of the repository for windows and macos, but not for ubuntu-latest.
> 
> It is pulling an older version of the repository for the ubuntu-latest runner and because of this my linux tests are failing. Tried many of the suggestions above, none have worked to fix this issue.

I can confirm its still the case.

**Comment by vt89** [comment]
I confirm it is still there.

**Comment by Jarco-Uil** [comment]
> To add to [@restfulhead's answer](https://github.com/actions/checkout/issues/439#issuecomment-965968956), `fetch-depth: 0` is not necessary. This example always checks out the latest commit of the branch that triggered the workflow.
> 
> ```
>       - name: Checkout
>         uses: actions/checkout@v3
>         with:
>           ref: ${{ github.ref }}
> ```

Thanks, This worked for me!

**Comment by schnerring** [comment]
This isn't really an issue, but a topic surrounded by a bit of confusion in regards to how the action works. When we talk about push events to branches, by default, the action ensures that it _exactly_ checks out the commit specified in the `github.sha` variable of the [`github` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context). Because the value of `github.sha` doesn't change over the lifetime of a workflow run, the action checks out the same commit across all jobs, whether you push something or not.

By running `git pull` or setting the `ref` parameter to `main` or `${{ github.ref }}`, the behavior of the action changes and it will instead always pull the latest commit available. This will work fine in the majority of cases, but race conditions may occur:

![image](https://user-images.githubusercontent.com/3743342/229331165-2a956eac-4893-4c9a-a6fb-8fa5c43375cd.png)

IMO "the best" approach is the following:

```yml
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}
    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v3

      - name: Update CHANGELOG.md
        run: echo "Added changes on $(date)" >> CHANGELOG.md

      - name: Commit and Push Changes
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v4

#      Or do things manually instead of using git-auto-commit-action
#      - name: Commit and Push Changes
#        id: commit-and-push
#        run: |
#          git add CHANGELOG.md
#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git config --local user.name "github-actions[bot]"
#          git commit -m "Update changelog"
#          git push
#          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  publish:
    needs: update-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check Out the Repo Again
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.update-changelog.outputs.commit_hash }}

      - name: Display CHANGELOG.md
        run: |
          cat CHANGELOG.md
          # The changes are here 🎉🎉🎉
```

By passing the commit hash of the pushed commit from the first job `update-changelog` to the second job `publish`, we ensure that we check out exactly what we pushed before and not something in between the job runs.

For anyone interested, [you can read more about this topic on my blog](https://schnerring.net/blog/checking-out-code-committed-within-the-same-github-actions-workflow-run/) (shameless plug).

---

The one thing I'm still curious about is people reporting different results between operating systems. I've had a bit of fun analyzing this, [so I created a repository that runs daily tests](https://github.com/schnerring/commit-and-checkout-actions-workflow/actions) with the following scenarios:

1. default checkout
2. default checkout + `git pull`
3. checkout with `ref: ${{ github.ref }}`
4. "checkout exact": the method I explained above

I run these tests on all the runner images available (`ubuntu-22.04`, `ubuntu-20.04`, `macos-12`, `macos-11`, `windows-2022`, `windows-2019`), but so far the everything returns the expected results. 🤷 I thought that these discrepancies might stem from the different Git implementations used within the runner images. I'll keep an eye on the results, maybe something turns up in the future.

For anyone interested, I use Hugo to automatically publish the results here: <https://commit-and-checkout-actions-workflow.schnerring.net/>. Turning this into unit tests would also be pretty straightforward.

**Comment by gruvw** [comment]
I am currently running into this issue:

- https://github.com/gruvw/portfolio/blob/6b82fea7a5c5705e432982406fc5d189badd6809/.github/workflows/build-jekyll.yml#L49
- workflow: https://github.com/gruvw/portfolio/actions/runs/5046101941/jobs/9051182850#step:3:388

**Comment by superarts** [comment]
I'm having this issue all of sudden as well. The funny thing is that `yml` file is updated, but my `Makefile` is not. The branch name and commit ID seems to be correct. This is very interesting...

**Comment by RaulTrombin** [comment]
many thanks [schnerring](https://github.com/schnerring), using this method based on GITHUB_OUTPUT it worked beetwen different jobs, thkns!

**Comment by luqmanrom** [comment]
From the docs:

> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags

**Comment by eliduke** [comment]
I was having this same issue with checkout@v4, thought I was taking wacky pills, so I am very thankful for this thread! It feels great knowing that I am not alone in this issue.

In the end, the `fetch-depth` option wasn't necessary, but adding the `ref: main` to my checkout step did the trick.

So, for any of you checkout@v4 folks this is what worked for me:

```
- name: Checkout
  uses: actions/checkout@v4
  with:
    ref: main
```
