### ISSUE TITLE
Can this action be used to check out a non GitHub repository?

### ISSUE THREAD

**Issue by r3econ** [actions/checkout#447]
I see the docs say I should provide repository name with owner. 
```
- uses: actions/checkout@v2
  with:
    # Repository name with owner. For example, actions/checkout
    # Default: ${{ github.repository }}
    repository: ''
```

Is there a way to provide a repo URL there to check out a non GitHub account?
