### ISSUE TITLE
Checkout on pull_request -> closed event

### ISSUE THREAD

**Issue by luludan** [actions/checkout#45]
Is there a way to checkout the code of a PR when closing the PR?

We are spinning up an environment per PR and need some config from the repo to help tear it down when closing the PR.

Currently it tries to checkout the branch based off the special github pr branch

![image](https://user-images.githubusercontent.com/49213261/65472178-05912580-de27-11e9-946f-39b8681f18c1.png)

**Comment by filipesilvaa** [comment]
hi @luludan try to use another ref, by default, `actions/checkout` uses ${{ github.ref }} which referes to something like: `refs/pull/#/merge`

an example, referencing another ref:
```yml
- uses: actions/checkout@v1
  with:
    ref: refs/heads/${{ github.head_ref }} # it could be ${{ github.base_ref }} also
```

**Comment by tomagi671** [comment]
Thanks

**Comment by tomagi671** [comment]
Closed

**Comment by tomagi671** [comment]
#45

**Comment by ericsciple** [comment]
i'll play around with this, i think i might know a way.

if you have the `on: ` syntax handy, please provide

**Comment by filipesilvaa** [comment]
hi @ericsciple thanks for your support,

here is a sample of `.yml`:
```yml
name: Build

on:
  pull_request:
    branches:
    - master
    types: [opened, synchronize, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout PR Ref
      if: github.event.action != 'closed'
      uses: actions/checkout@v1

    - name: Git Checkout Base Ref
      if: github.event.pull_request.merged == true
      uses: actions/checkout@v1
      with:
        ref: refs/heads/${{ github.base_ref }}
```

**Comment by fezho** [comment]
@ericsciple I got an issue when using goveralls, https://github.com/mattn/goveralls/issues/150
And I think it's because checkout fetches the specific SHA rather than the ref, however goveralls gets the wrong sha:
```
	if os.Getenv("GITHUB_EVENT_NAME") == "pull_request" {
		ghPR := getGithubEvent()["pull_request"].(map[string]interface{})
		ghHead := ghPR["head"].(map[string]interface{})
		commitRef = ghHead["sha"].(string)
	}
```
This can be fixed by using ` ref: ${{ github.event.pull_request.head.sha }}`, but i do not want to use it when push to master. Any advice to fix this issue?

**Comment by Gopikrishna19** [comment]
@fezho you can add event check:

```yml
    steps:
      - uses: actions/checkout@v2
        name: Checkout PR
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v2
        name: Checkout Branch
        if: github.event_name == 'push'
```
When in pull request
![On PR](https://user-images.githubusercontent.com/2506698/220975869-58e17be2-a879-4ecc-b138-0409b710f89a.png)

When in a branch
![On Branch](https://user-images.githubusercontent.com/2506698/220975873-e3757ef6-4418-49ac-a162-58b003655a81.png)
