### ISSUE TITLE
Submodule update fails with Host key verification failed

### ISSUE THREAD

**Issue by arihannu** [actions/checkout#454]
We have a private repository which has many submodules, which are in our corporate git servers. We have self hosted runners which do the checkout. Every time when one of those submodules need to be updated (new commits), pull fails with Host key verification failed. ~/.ssh/known_hosts file must be correct, because **when I run git submodule update locally on the same runner, there are no issues**. It seems like known_hosts is not even read or something else is wrong. Here is the checkout action:
```
- uses: actions/checkout@v2
      timeout-minutes: 30
      with:
        token: ${{ secrets.CI_TOKEN }}
        lfs: true
        submodules: recursive
```

We have also many submodules which are in github.com, with which we have never trouble. Only with the ones which are outside of Github and have url ssh://server...

Could it be that checkout action does not respect user's known_hosts file since modifying it seems to have absolutely no effect?
