### ISSUE TITLE
Checkout Specific Folder/Directory/Path within GitHub Repository

### ISSUE THREAD

**Issue by NickLiffen** [actions/checkout#483]
👋 

Let's say I have `repositoryA` that has a high-level folder structure of:

```
- .github
- actions
- docs
- tests
readme.md
...
```

I also have a repository called `repositoryB`. From `repositoryB`, I am trying to checkout `repositoryA`. I have that working by something like the below:

```
      - name: Checkout Central Actions Repo
        uses: actions/checkout@v2
        with:
          repository: ${{org}}/repositoryA
          ref: main
          token: ${{ secrets.token }}
          persist-credentials: false
          path: ./github-app-jwt-action
```

This works and checks out the **whole** repository. I am looking for a way to only checkout the **actions**
 directory from `repositoryA`, vs the whole repository. I was thinking something like this would work:

```
      - name: Checkout Central Actions Repo
        uses: actions/checkout@v2
        with:
          repository: ${{org}}/repositoryA
          ref: main
          token: ${{ secrets.token }}
          persist-credentials: false
          path: ./github-app-jwt-action
          dir: ./actions
```

This obviously isn't possible, but I wondered if there was another way around this?

**Comment by rexwangcc** [comment]
Running into a similar case, I noticed that there's a way to achieve that using `git` commands, as explained [here](https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/52269934#52269934), but it would be great if there's an Actions solution too :-)

**Comment by gnrlbzik** [comment]
There is this github action i found: https://github.com/marketplace/actions/checkout-files

**Comment by andyslack** [comment]
We are moving towards one repo per client which holds both their `backend` and `frontend` to save having multiple repos per client. This feature would be really helpful for me.

**Comment by LeviPesin** [comment]
Isn't this supported since v3.5.3 by using `sparse-checkout`?

**Comment by andyslack** [comment]
> Isn't this supported since v3.5.3 by using `sparse-checkout`?

Works like a dream 👍

**Comment by danial-k** [comment]
Example with sparse checkout (would be nice if this was handled with a shortcut per #1430 ):
```yaml
jobs:
  eas-preview:
    name: EAS preview
    runs-on: ubuntu-latest
    steps:
      # Checkout project code
      # Use sparse checkout to only select files in mobile app directory
      # Turning off cone mode ensures that files in the project root are not included during checkout
      - uses: actions/checkout@v3
        with:
          sparse-checkout: 'frontend/mobile'
          sparse-checkout-cone-mode: false

      # This step is needed because expo-github-action does not support paths.
      # Therefore all mobile app assets should be moved to the project root.
      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv frontend/mobile/* .
          rm -rf frontend
          ls -lah
```
