### ISSUE TITLE
Make GITHUB_SERVER_URL configurable

### ISSUE THREAD

**Issue by killermoehre** [actions/checkout#488]
Hi,

I work on a GitHub Enterprise instance (`https://github.internal.company`) and want to check out something from `https://github.com`. My naive approach is
```
      - name: Checkout github.com/sapcc/fedIPA
        env:
          GITHUB_SERVER_URL: 'https://github.com'
        uses: actions/checkout@v2
        with:
          repository: sapcc/fedIPA
          submodules: true
```
but even though I overwrite the environment variable `GITHUB_SERVER_URL` (as used in https://github.com/actions/checkout/blob/main/src/url-helper.ts#L24) the action is still checking from the internal URL, trying to access `https://github.internal.company/sapcc/fedIPA`.
Mirroring the whole repository is not my goal as I just want to use the code to run some custom workflow.

Any advice?

**Comment by cory-miller** [comment]
The code linked will prefer whatever is set with the action input:

https://github.com/actions/checkout/blob/a5ac7e51b41094c92402da3b24376905380afc29/action.yml#L98C3-L100

```
      - name: Checkout somewhere-else.com/sapcc/fedIPA
        uses: actions/checkout@v4
        with:
          repository: sapcc/fedIPA
          submodules: true
          github-server-url: https://somewhere-else.com
```
