### ISSUE TITLE
Missing .yarn folder after checkout

### ISSUE THREAD

**Issue by mrowles** [actions/checkout#490]
My repository is checked out without some folders, of particular necessity is the `.yarn` cache folder.

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup OS
        run: |
          sudo apt-get update
          sudo apt-get upgrade

      - name: Setup Git
        run: |
          sudo apt-get install git

      - name: Checkout repository
        uses: actions/checkout@v1
        #uses: actions/checkout@v2
```

I have tried updating the OS, git (seems to be the latest anyways) and attempted both v1 and v2 of the checkout action to no avail.

When I list the files, it seems to be grabbing dot files e.g., .gitignore, but not the folders like .yarn
