### ISSUE TITLE
Checking out HEADs of submodules

### ISSUE THREAD

**Issue by vvasuki** [actions/checkout#503]
I recently had much trouble using this action as part of an attempt to checkout submoudle HEADS - See [here](https://stackoverflow.com/questions/67457510/git-submodule-update-remote-merge-yields-fatal-needed-a-single-revision?noredirect=1#comment119241675_67457510) . It would be great if **the action were to be able to do it automatically!** Anyway, what I tried was:

```
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    - name: Update submodules
      if: ${{ github.event_name != 'pull_request'}}
      run: |
        git pull --recurse-submodules --depth 1
        git submodule update --remote --merge
```

The result was:

```
Run git pull --recurse-submodules --depth 1
From https://github.com/vvasuki/kAvyam
 * [new branch]      content         -> origin/content
 * [new branch]      gh-pages        -> origin/gh-pages
 * [new branch]      offline_android -> origin/offline_android
 * [new branch]      trigger_branch  -> origin/trigger_branch
Fetching submodule content
Fetching submodule themes/sanskrit-documentation-theme-hugo
Already up to date.
fatal: Needed a single revision
Unable to find current origin/content revision in submodule path 'content'
Error: Process completed with exit code 1.
```

The following worked:

Disabling submodules initialization in the action as below

```
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: false
```

Manual updation:

```
    - name: Update submodules
      if: ${{ github.event_name != 'pull_request'}}
      run: |
        set -o xtrace
        git submodule update --init --recursive
        git submodule update --remote --merge --recursive
```
