### ISSUE TITLE
[suggestion] Respect the job:defaults:run:working-directory as the default path

### ISSUE THREAD

**Issue by kuvaldini** [actions/checkout#516]
As I feel GITHUB_WORKSPACE should correspond to working-directory. But it does not. And we have no GITHUB_WORKDIR env variable.

My current workflow looks like:
```
build-iroha-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: &workdir 'C:\github\iroha'  ## Use disk C: because D: is out of space
    steps:
      - name: create working-directory
        run: set -x; mkdir -p "$workdir"; echo $PWD
        working-directory: 'C:\'
        env: { workdir: *workdir }
     - 
        name: Checkout
        uses: actions/checkout@v2
        with: 
          path: *workdir 
```
*Here you can see YAML anchors. They are dereferenced with `yq eval 'explode(.)'`*

All scripts runs in `C:\github\iroha`, so I also would like to checkout to that directory. 

###  Suggestion
Add preference path to checkout to:
0. with:path
1. job:defaults:run:working-directory
2. GITHUB_WORKSPACE

if `with:path` is relative, than try to be relative to job:defaults:run:working-directory(if not empty) before GITHUB_WORKSPACE
