### ISSUE TITLE
Checking out a merge commit in `pull_request_target` workflows

### ISSUE THREAD

**Issue by mpdude** [actions/checkout#518]
I am coming from https://github.com/dependabot/dependabot-core/issues/3253, where there is a lot of confusion of how to safely run actions with secrets when untrusted code from external PRs comes into play.

The bottom line is that there may be situations where you – **after you understood the risks** – might want to use the `pull_request_target` event because it has access to secrets; but combine that with a checkout of the PR.

One suggested way of doing this is with 

```
- name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
```

which will check out the PR head commit.

This is, however, not 100% what you'd get for a simple `uses: actions/checkout@v2` on a `pull_request` event, because that would check out a _merge commit_.

I wonder whether it would be possible for this action here to also support checking out such a merge commit on `pull_request_target` events? 

I don't know if creating such a merge commit involves advanced Git trickery to get-it-right™️ , so I thought this was the best place to ask.

**Comment by mpdude** [comment]
Here's another reason why it would be helpful if this could be supported directly in the action:

I'd like to use `actions/checkout` with `persist-credentials: false` to leak as little sensitive information as possible. But with this, I cannot easily run any `git` commands myself in subsequent steps to create a merge commit (for example, it seems I'd need an extra `git fetch` to get the PR head commit first).

If the merge commit could be created by the action, then the action could create it before doing the cleanup of persisted credentials.

**Comment by Trim21** [comment]
```yaml
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
```

this should work as you expected I think.

**Comment by geekflyer** [comment]
> ```yaml
>       - name: Checkout code
>         uses: actions/checkout@v2
>         with:
>           ref: "refs/pull/${{ github.event.number }}/merge"
> ```
> 
> this should work as you expected I think.

I wonder if this is safe fully safe though? With this approach, if a malicious PR author pushes unsafe code between PR approval and the checkout action being run, your CI system might checkout a different version of the code than what the maintainer approved.

` ref: ${{ github.event.pull_request.head.sha }}` on the other hand is safe since it references a fixed head.sha that corresponds to the time the pull_request_target has triggered.

**Comment by Trim21** [comment]
> > ```yaml
> >       - name: Checkout code
> >         uses: actions/checkout@v2
> >         with:
> >           ref: "refs/pull/${{ github.event.number }}/merge"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this should work as you expected I think.
> 
> I wonder if this is safe fully safe though? With this approach, if a malicious PR author pushes unsafe code between PR approval and the checkout action being run, your CI system might checkout a different version of the code than what the maintainer approved.
> 
> ` ref: ${{ github.event.pull_request.head.sha }}` on the other hand is safe since it references a fixed head.sha that corresponds to the time the pull_request_target has triggered.

It's not safe.

That's why you shouldn't execute any test code or lint plugin from PR, you should only execute code like lint(with out loading plugin from repo) or formatter.

**Comment by geekflyer** [comment]
> > I wonder if this is safe fully safe though? With this approach, if a malicious PR author pushes unsafe code between PR approval and the checkout action being run, your CI system might checkout a different version of the code than what the maintainer approved.
> > ` ref: ${{ github.event.pull_request.head.sha }}` on the other hand is safe since it references a fixed head.sha that corresponds to the time the pull_request_target has triggered.
> 
> It's not safe.
> 
> That's why you shouldn't execute any test code or lint plugin from PR. They can read env and maybe able to read your repo secret.
> 
> you should only execute code like lint (with out loading plugin from repo) or formatter.

I mean `${{ github.event.pull_request.head.sha }}` is safe the maintainer has fully reviewed the the PR code and determined that the code is safe (let's say for a README change). However `ref: "refs/pull/${{ github.event.number }}/merge"` is not safe, because even if the original PR was just changing some README, a malicious actor can push more code changes in a specific time window that are then being tested against.

**Comment by Trim21** [comment]
Yes, but `github.event.pull_request.head.sha` is not what we want in this situation. We want to know that the repo will look like after the pr is merged.

**Comment by geekflyer** [comment]
> Yes, but `github.event.pull_request.head.sha` is not what we want in this situation. We want to know that the repo will look like after the pr is merged.

yeah, I mean there is probably other ways to achieve the merge and test against the merged state. But using `refs/pull/${{ github.event.number }}/merge"` alone is not exactly the safest way since it references a ref that can be updated.

**Comment by dvdhrm** [comment]
Workaround:

Checkout `refs/pull/${{ github.event.number }}/merge` and then verify `HEAD^` equals `github.event.pull_request.head.sha` afterwards. If they don't match, cancel your workflow (a newer one is already scheduled, given that the head-sha changed).

Not ideal, but safe and works.

**Comment by antoniovazquezblanco** [comment]
Gist of the previous sugestion:

```
- name: Checkout
  uses: actions/checkout@v3
  with:
    ref: "refs/pull/${{ github.event.number }}/merge"

# Important security check: https://github.com/actions/checkout/issues/518
- name: Sanity check
  run: |
    [[ "$(git rev-parse 'HEAD^')" == "${{ github.event.pull_request.head.sha }}" ]]
```

**Comment by fxmarty** [comment]
@antoniovazquezblanco I believe the correct syntax should be:

```
- name: Checkout
  uses: actions/checkout@v3
  with:
    ref: "refs/pull/${{ github.event.number }}/merge"
    fetch-depth: 2

# Important security check: https://github.com/actions/checkout/issues/518
- name: Sanity check
  run: |
    [[ "$(git rev-parse 'HEAD^2')" == "${{ github.event.pull_request.head.sha }}" ]]
```

because the branch that is merged into is the first parent. Isn't it?
