### ISSUE TITLE
Is there a way to get all commit history for a single branch?

### ISSUE THREAD

**Issue by emmahsax** [actions/checkout#520]
I'm using this action like this (this works splendidly):

```yml
- name: Check Out Code
  uses: actions/checkout@v2
  with:
    ref: ${{ env.BRANCH }}
    fetch-depth: 0
```

I only need to get the entire commit history for just that one `${{ env.BRANCH }}`. But using `fetch-depth: 0` gets all commit history for all branches and tags, which is unnecessary in my case. Is there a way to get the entire commit history for just the branch referenced in the `ref`?

**Comment by solarmosaic-kflorence** [comment]
This is very painful in our ever growing monorepo.

**Comment by solarmosaic-kflorence** [comment]
See also https://github.com/actions/checkout/issues/285 https://github.com/actions/checkout/issues/346

**Comment by solarmosaic-kflorence** [comment]
If you persist credentials, you can just check out a single commit, and then fetch whatever you want yourself. For example:

```yaml
steps:
  - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    with:
      ref: "${{ github.event.pull_request.head.sha }}"
  - run: git fetch --prune --progress origin +refs/heads/${{ github.event.pull_request.head.ref }}:refs/remotes/origin/${{ github.event.pull_request.head.ref }}
```

This will fetch all refs for the PR branch. This is a hack, though.

**Comment by solarmosaic-kflorence** [comment]
It would probably be better if there was just an action that set up credentials and let users run their own fetches.

**Comment by lourd** [comment]
Here's the job yml for the workaround I just figured out for my use case of running tests and linting on pull requests on my team's Nx monorepo, in case anyone else find this useful. 

```yml
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add PR base ref
        # Fetch the ref of the base branch, just the single commit.
        run: git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
      - name: Track PR base branch
        # Turn the just-fetched ref into a local branch.
        run: git branch --track ${{github.base_ref}} origin/${{github.base_ref}}
      - name: Fetch commits in-between base and HEAD
        # While the ancestor commit between HEAD and the branch base isn't in the local tree
        # fetch X more parent commits of the branch base and branch head.
        run: |
          while [ -z $( git merge-base ${{github.base_ref}} HEAD ) ]; do     
            git fetch --deepen=10 origin ${{github.base_ref}} HEAD;
          done
        # Sets the commit SHAs of head and branch base into two environment variables
        # that `nx affected` will read from.
      - name: Derive SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: ${{github.base_ref}}
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn nx affected --target=lint
      - name: Tests
        run: yarn nx affected --target=test
```

**Comment by polarathene** [comment]
### Single branch history:

```yaml
- name: 'PR commits + 1'
  run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

- name: 'Checkout PR branch and all PR commits'
  uses: actions/checkout@v3
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      fetch-depth: ${{ env.PR_FETCH_DEPTH }}
```

If you need this for a branch that is not a pull request triggered event, and lacks commit context, I have seen others [use the Github CLI](https://github.com/actions/checkout/issues/416#issuecomment-1114056711) (their calculation differs from mine with `expr`, but the way I did it is [what's often advised](https://unix.stackexchange.com/questions/149823/parenthesis-in-expr-arithmetic-3-2-1/149991#149991)):

```bash
# fetch more commits
prCommits=`gh pr view $prId --json commits | jq '.commits | length'`
fetchDepthToPrBase=`expr $prCommits + 2`
git fetch --no-tags --prune --progress --no-recurse-submodules --deepen=$fetchDepthToPrBase
```

- [`gh` CLI tool reference](https://cli.github.com/manual/gh_help_reference) + [Github blogpost with examples](https://github.blog/2021-03-11-scripting-with-github-cli/)
- [`gh auth`](https://cli.github.com/manual/gh_auth_login) (mentions actions auth via `GH_TOKEN` env)
- [`gh api`](https://cli.github.com/manual/gh_api) may be most useful in this case with the [list commits](https://docs.github.com/en/rest/commits/commits#list-commits) endpoint and parameters for branch and `since` date, then counting items with `--jq length` (note page results are limited to 30 by default), otherwise if it is/was a PR branch, you can look that one up.

> This is a hack, though, and it require re-fetching objects and re-resolving deltas.

The overhead should be minimal AFAIK, especially with `fetch-depth: 1` (default) prior. You can otherwise use the example above and set the `fetch-depth` via an ENV value.

### For branch comparisons such as getting a list of files changed:

```yaml
- name: 'Checkout PR branch (with test merge-commit)'
  uses: actions/checkout@v3
    with:
      fetch-depth: 2
- name: 'Get a list of changed files to process'
  run: git diff-tree --name-only --diff-filter 'AM' -r HEAD^1 HEAD
```

- That uses the default fetched "test merge-commit" (from PR to base branch) that Github generates and fetches the two parent commits involved in the merge (1 from each branch, 2nd depth level).
- No merge-base is needed since you can diff between the merge-commit (HEAD) and the parent commit `HEAD^1` (from base branch) and it's effectively a before/after difference.
- This example is filtering change status of files by Added (A) and Modified (M), other differences are excluded (such as deletions).

---

**If you need more history** though, instead of the while loop deepen approach, for a PR branch to the base branch, you can leverage the Github context object for getting how many commits to fetch (_1 more than the PR to get the commit the PR branched from and is a common ancestor with the base branch_).

Note that any merge commits (base to PR branch) add to the count, but don't seem to be part of the fetched count, thus you may over-fetch some excess from N merge commits.

```yaml
- name: 'Checkout PR branch'
  uses: actions/checkout@v3
    with:
      ref: ${{ github.event.pull_request.head.ref }}

- name: 'Get a list of changed files to process'
  run: |
    # Fetch enough history for a common merge-base commit
    git fetch origin ${{ github.event.pull_request.head.ref }} --depth $(( ${{ github.event.pull_request.commits }} + 1 ))
    # Fetch is smart enough to keep commits fetched minimal if it finds local history already has a commit from the base branch:
    git fetch origin ${{ github.event.pull_request.base.ref }}

    # Show only files from the PR with content filtered by specific git status (Added or Modified):
    git diff-tree --name-only --diff-filter 'AM' -r \
      --merge-base origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}
```

---

There is a **slight chance of the previous example not fetching enough commits to derive a merge-base commit** if you have used this action earlier in the workflow and fetched the ref for the test merge commit with a _`fetch-depth` of 2 or more_, since that contains a commit from the base branch in local history.

In that case you can still use this approach, but retrieve the date of the oldest commit (_that is shared by both base and PR branches_), and then fetch commits since that date which provides a common merge-base commit (_unless there are merge commits from the base branch into the PR branch, in which case `--merge-base` / `git merge-base` will prefer as the merge-base_):

```yaml
- name: 'Checkout PR branch'
  uses: actions/checkout@v3
    with:
      ref: ${{ github.event.pull_request.head.ref }}

- name: 'Get a list of changed files to process'
  run: |
    # Fetch enough history for a common merge-base commit
    git fetch origin ${{ github.event.pull_request.head.ref }} --depth $(( ${{ github.event.pull_request.commits }} + 1 ))
    
    # This should get the oldest commit in the local fetched history (which may not be the branched base commit):
    BRANCHED_FROM_COMMIT=$( git rev-list --first-parent --max-parents=0 --max-count=1 ${{ github.event.pull_request.head.ref }} )
    UNIX_TIMESTAMP=$( git log --format=%ct "${BRANCHED_FROM_COMMIT}" )
    # Get all commits since that commit for the base branch (eg: master):
    git fetch --shallow-since "${UNIX_TIMESTAMP}" origin ${{ github.event.pull_request.base.ref }}

    # Show only files from the PR with content filtered by specific git status (Added or Modified):
    git diff-tree --name-only --diff-filter 'AM' -r \
      --merge-base origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}
```

---

[More details from a similar comment I wrote earlier](https://github.com/actions/checkout/issues/552#issuecomment-1167086216)
