### ISSUE TITLE
Is it possible to checkout to enterprise github repo from non enterprise public repo in github actions?

### ISSUE THREAD

**Issue by LakshmiRavali** [actions/checkout#563]
I want to checkout to enterprise github repo from non-enterprise public repo. These are my actions:

```
jobs:
  checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: enterprise/repo
        token: ${{ secrets.ENTERPRISE_TOKEN }} 
        path: main
```
but as I saw it will clone https://github.com/enterprise/repo, but my enterprise account is on a different domain. Is it possible to checkout to the enterprise account?

**Comment by LakshmiRavali** [comment]
When I am checking the code, there is a [environment variable](https://github.com/actions/checkout/blob/25a956c84d5dd820d28caab9f86b8d183aeeff3d/src/url-helper.ts#L25) for server url. I am trying to set it like this:
```
jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
        GITHUB_SERVER_URL: {{ENTERPRISE_URL}}
        GITHUB_API_URL: {{ENTERPRISE_URL}}
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: enterprise/repo
        token: ${{ secrets.ENTERPRISE_TOKEN }} 
        path: main
```
but still, I am getting the error 
```
Retrieving the default branch name
  Error: Bad credentials
```
Can anyone let me know how to use the environment variable to set the server URL?
