### ISSUE TITLE
Feature Request: Use GitHub App to checkout

### ISSUE THREAD

**Issue by alec-pinson** [actions/checkout#567]
We are unable to create service/bot accounts within our Enterprise.
We would really like the option to be able to use a GitHub app for authentication.

I created an example of how this would work below:-

```yaml
      - uses: actions/checkout@v2
        with:
          repository: <org>/github-actions
          github_app_id: ${{ secrets.APP_ID }}
          github_app_key: ${{ secrets.APP_KEY }}
          path: .github/actions
```

This is our current workaround but we would prefer to remove the `generate token` step

```yaml
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - name: Checkout action
        uses: actions/checkout@v2
        with:
          repository: <org>/github-actions
          token: ${{ steps.generate_token.outputs.token }}
          path: .github/actions
```
