### ISSUE TITLE
Providing `with.path` does nothing

### ISSUE THREAD

**Issue by tsal** [actions/checkout#57]
```
jobs:
  handle_labels:
    if: contains(github.event.label.name, 'build-for-integration')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        repository: ${{ 'private-org/github-actions' }}
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 1
        ref: 'v1'
        path: ./github-actions
    - name: Check local directory structure
      run: |
        cd github-actions
```

Results in:

```
/home/runner/work/_temp/{hash}.sh: line 1: cd: github-actions: No such file or directory
##[error]Process completed with exit code 1.
```

removing / adding `./` in various combination has no effect; in addition, providing the full workspace path / variable gives the dreaded "rooted path" error.
