### ISSUE TITLE
Error: Unable to locate executable file: tar. 

### ISSUE THREAD

**Issue by david-webill** [actions/checkout#571]
Hello
I am attempting to use the checkout action but it keeps failing with the following:
`Error: Unable to locate executable file: tar.  Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`

My yaml looks as follows:

```
name: Deploy Foxx Org
on:
  push:
    branches:
      - master
    paths:
      - libs/server/org/org-foxx/**
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: redacted.redacted.org
      DATABASE: wb-org-test
      PATH: libs/server/org/org-foxx
      ENDPOINT: /org-api
    steps:
      - uses: actions/checkout@v2
      - name: Install Foxx CLI
        run: sudo npm i -g foxx-cli
      - name: Add Database
        run: foxx server set arango https://root:"${{ secrets.ARANGO_TEST_PWD }}"@${{ env.HOST }} -D ${{ env.DATABASE }}
      - name: Upload Service
        run: cd ${{ env.PATH }} && foxx upgrade --server arango ${{ env.ENDPOINT }}
```

Error:
```
Run actions/checkout@v2
Syncing repository: WeBill65/wb
Getting Git version info
Deleting the contents of '/home/runner/work/wb/wb'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Downloading the archive
Writing archive to disk
Extracting the archive
Error: Unable to locate executable file: tar. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

It was working fine but now fails consistently

Thanks

**Comment by emmanuelstroem** [comment]
We had the same issue.
It is because you are setting the global `PATH` which is overriding the linux executable paths.

Try removing  `PATH: libs/server/org/org-foxx` and specifying the path directly in the step.

```
name: Deploy Foxx Org
on:
  push:
    branches:
      - master
    paths:
      - libs/server/org/org-foxx/**
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: redacted.redacted.org
      DATABASE: wb-org-test
      ENDPOINT: /org-api
    steps:
      - uses: actions/checkout@v2
      - name: Install Foxx CLI
        run: sudo npm i -g foxx-cli
      - name: Add Database
        run: foxx server set arango https://root:"${{ secrets.ARANGO_TEST_PWD }}"@${{ env.HOST }} -D ${{ env.DATABASE }}
      - name: Upload Service
        run: cd libs/server/org/org-foxx && foxx upgrade --server arango ${{ env.ENDPOINT }}
```
