### ISSUE TITLE
Checkout action is undoing some repo history

### ISSUE THREAD

**Issue by pcolmer** [actions/checkout#573]
I'm checking out a repository thus:

```
      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.LINARO_BUILD_KEY }}
          path: website
```

However, when the repo is fetched, the action does the following:

```
  /usr/bin/git rev-parse refs/remotes/origin/master
  d84ba4322bb75f2aa391d691680fc829293443ac
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules origin +a3a4c887009c42b68bdb359949807ea66deccf77:refs/remotes/origin/master
  From github.com:Linaro/website
   + d84ba432...a3a4c887 a3a4c887009c42b68bdb359949807ea66deccf77 -> origin/master  (forced update)
```

thus **undoing** several commits in the repo. Why is it doing this, please? Is there a setting I'm overlooking? I don't know where the action is getting the commit reference `a3a4c887009c42b68bdb359949807ea66deccf77` from but I need it to stop doing it!
