### ISSUE TITLE
fatal: You are not currently on a branch

### ISSUE THREAD

**Issue by meness** [actions/checkout#577]
What's wrong with this workflow? It throws an error on the `git push` line.

```yaml
name: Release/Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.17.6
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm run release
      - run: git push --follow-tags origin main
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - uses: actions/setup-node@v2.4.0
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by meness** [comment]
I fixed the issue. Hope this helps
```yml
name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.18.0
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm run release
      - run: npm run postrelease
      - run: cp ./package.json ./dist/package.json
      - run: cd ./dist
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - uses: actions/setup-node@v2.4.1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
