### ISSUE TITLE
`Post Check out code` is not able to reset the git state

### ISSUE THREAD

**Issue by nedrebo** [actions/checkout#594]
We are using self-hosted runners and the checkout action. Recently we had a situation where code in one branch managed to break the builds of other branches.

What was done was to add the second step below.

```
steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
          lfs: true
    - name: Remove non-dependencies
      run: |
          git sparse-checkout init --cone
          git sparse-checkout set project1/src
```

This caused a Git state that `Post Check out code` did not manage to recover from.

When a new job later started on the same runner and that job needed files outside of `project1/src` it failed.

I think this case should be handled by the checkout action so that after the `Post Check out code` step the stat in git is the same as after the `Check out code` step above.

**Comment by david-frautnick** [comment]
The same issue happens when using the `sparse-checkout` option.  For example, I have a job with the following step:
```yml
      - name: Fetch Source
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            dirA
            dirB
```
This works fine, however, I have another job that does not use `sparse-checkout` like this:

```yml
      - name: Fetch Source
        uses: actions/checkout@v3
```
If this second job re-uses the same work folder on my runner server, it will not checkout the full repository because the previous job had it set to `sparse-checkout`.  It would be great if the `Post Fetch Source` step would reset the `sparse-checkout` setting for subsequent jobs that reuse the same work folder.

**Comment by Wei18** [comment]
Hi,
I use this to workaround, but it's good to see author put `git sparse-checkout disable` in the post job.
```yml
steps:
    - uses: actions/checkout@v3
      with:
        sparse-checkout: |
          .github
    - run: git sparse-checkout disable # [Workaround] Reset previous sparse-checkout
```
