### ISSUE TITLE
checkout@v1 breaking change - overwrites ~/.gitconfig

### ISSUE THREAD

**Issue by rectalogic** [actions/checkout#60]
As per issue https://github.com/actions/checkout/issues/14, the standard way to make private submodules work with checkout is to use insteadOf to rewrite git@ urls to https:// and to use a private access token, e.g.:

```yaml
    - name: Fix submodules
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
    - name: Checkout server
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: true
        token: ${{ secrets.CUREATR_PAT }}
```

As of a few days ago, checkout@v1 now seems to overwrite ~/.gitconfig and this no longer works.
It appears this PR made the change https://github.com/actions/checkout/pull/56

How should we make private submodules work with the non-backward compatible checkout@v1?
Also where is the source code to the checkout plugin, it would be useful for debugging breaking changes like this.
