### ISSUE TITLE
Feature: Checkout bare repo

### ISSUE THREAD

**Issue by johnnyhuy** [actions/checkout#603]
Hey, is there any way we can use `--bare` in this action? We can't seem to use run actions to clone the repo without using a PAT.

```bash
git clone --bare ${REPO NAME}
```

**Comment by ristiisa** [comment]
@mouismail
@motss
@jww3
@Jcambass
@orhantoy
@lucacome
@yasonk

Any ideas?

**Comment by mwpastore** [comment]
You can get something kind of like a bare repo with:

```yaml
- uses: actions/checkout@v5
  with:
    sparse-checkout: .
    sparse-checkout-cone-mode: false
```

Further customizable with `depth`, `fetch-tags`, etc.
