### ISSUE TITLE
Unable to locate executable file: git-lfs (self-hosted runner on NixOS)

### ISSUE THREAD

**Issue by src386** [actions/checkout#608]
**Describe the bug**

Actions fails on **actions/checkout@v2** with the following message:

> Error: Unable to locate executable file: git-lfs. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

Proof that git and git-lfs are present:
```
[root@nixos-0:~]# whereis git
git: /nix/store/ha0brrajajavga018ysz2wlm3h93dqcn-system-path/bin/git

[root@nixos-0:~]# whereis git-lfs
git-lfs: /nix/store/ha0brrajajavga018ysz2wlm3h93dqcn-system-path/bin/git-lfs

root@nixos-0:~]# git version
git version 2.31.1

[root@nixos-0:~]# git-lfs version
git-lfs/2.13.3 (2.13.3; linux amd64; go 1.16.8; git v2.13.3)

```
**To Reproduce**

1. Install github-runner on a NixOS system
2. Set a `actions/checkout@v2` action with `lfs:true`:
```
name: build

on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: [ 'self-hosted', 'nixos' ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
```
3. Trigger a build

**Expected behavior**
The runner should be able to clone the source code with LFS blobs.

## Runner Version and Platform
- (Linux) NixOS 21.05
- github-runner 2.283.3

## What's not working?

It seems that the self-hosted runner is not able to find `git-lfs`, although it does not have any problems with `git`.
