### ISSUE TITLE
Cannot use parent specifiers in the ref

### ISSUE THREAD

**Issue by mathstuf** [actions/checkout#61]
I'd like to run an action on a pull_request and check out the actual content of the PR, not a merge with `master` (because I want it to run even if there is a merge conflict among other reasons). Support for specifying this has been requested [on the community forum](https://github.community/t5/GitHub-Actions/Support-pull-request-events-without-merge-commit-into-the-target/td-p/36190).

I've tried the following:

```yaml
with:
  ref: ${{ github.ref }}^2
```

Which causes a failure because it tries to do:

```
 git fetch --tags --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/pull/3/merge^2:refs/remotes/pull/3/merge^2
```

which is an invalid refspec.

Doing this seems to just get completely ignored:

```yaml
with:
  ref: ${{ github.sha }}^2
```

I haven't found a way to use `$GITHUB_SHA` yet either (it seems to be used literally when in a `with` block).

**Comment by ericsciple** [comment]
@mathstuf consider adding a `run` step after checkout, and `git reset --hard HEAD^2`

**Comment by ericsciple** [comment]
Yes. GITHUB_SHA is not set by the checkout action. It is from the server event payload.

**Comment by mathstuf** [comment]
And while that may be a workaround, not being able to specify a valid Git refname in such a way (and that gets silently ignored) seems like a bug in any case.

**Comment by mathstuf** [comment]
Also of note is that manual checkout misses all of the submodule sync/update, depth options, etc. available through the action.

**Comment by ericsciple** [comment]
from the pr event payload, i think `${{ github.event.after }}` is the SHA you want

**Comment by peter-evans** [comment]
I think this will checkout the merging branch instead of the merge commit.
```
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
```

**Comment by ericsciple** [comment]
@peter-evans instead of refs/pull/merge/\<number\> iirc refs/pull/\<number\> contains the commit (for forks and non forks). i may be wrong?

**Comment by peter-evans** [comment]
@ericsciple I tested the following but it didn't work and gave the error `##[error]fatal: couldn't find remote ref refs/pull/281`

```
on: pull_request
jobs:
  pullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/pull/${{ github.event.number }}
```
What does seem to work for me is the following. But to make this work for forks as well you need to use a `repo` scoped PAT. Additionally, specifying the `path` is necessary to keep fork and non-fork checkouts at the same path for the rest of your workflow.
```
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: ${{ github.event.repository.name }}
```

**Comment by ericsciple** [comment]
i'll play with this a bit, i think there's a different way

**Comment by ericsciple** [comment]
@peter-evans sorry its `refs/remotes/pull/###/head` or `pull/###/head`

i played around with this locally by fetching everything under pull:

```
git fetch origin '+refs/pull/*:refs/remotes/pull/*'
git log refs/remotes/pull/70/head/
```

**Comment by ericsciple** [comment]
@mathstuf it sounds like the following solution will work:

```
on: pull_request
jobs:
  pullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/pull/${{ github.event.number }}/head
```
