### ISSUE TITLE
[master] submodule issue about https and user

### ISSUE THREAD

**Issue by kwladyka** [actions/checkout#62]
```yaml
    - name: checkout
      uses: actions/checkout@master
      with:
        submodules: recursive
        fetch-depth: 1
        token: ${{ secrets.OWNER_PAT }}
```

```
[submodule "themes"]
	path = themes
	url = https://owner@github.com/owner/repo.git
```

The point is the user has to be added in https url, because of the error:
```
##[error]fatal: could not read Username for 'https://github.com': terminal prompts disabled
##[error]fatal: clone of 'https://github.com/owner/repo.git' into submodule path '/foo/themes' failed
```

But when add URL with a `owner@` and other user (not an owner) will want to do `git submodule update`, then he will be prompted about `owner` password.

So using current method of authorisation with `token` for user which is set in submodule HTTPS URL is not functional.

**How to solve it? Deploy key? Let set also `user` as parameter in action?**

Just discovered it works on `actions/checkout@v1`. But issue still valid for `@master` and generally worth to implement deploy keys.

**Comment by thboop** [comment]
Related to [https://github.com/actions/checkout/issues/60]

As a general rule, we would recommend you bind to the major tag (@v1), otherwise you run the risk of your workflows breaking as we make changes.

We are looking into this issue.

**Comment by zivkaziv** [comment]
Hey,
I'm trying to checkout different private repository using the following configuration
```
  - name: Checkout server
        uses: actions/checkout@v1
        with:
          repository: <account>/<repo>
          ref: refs/heads/master
          token: ${{ secrets.GitHub_PAT }}
```
And I'm getting this error too

> ##[error]fatal: could not read Username for 'https://github.com': terminal prompts disabled

Is it relted too?
Please help...

**Comment by kwladyka** [comment]
@zivkaziv I guess changing url from https to ssh link to repo should help in your case. But yes, it is related.

**Comment by zivkaziv** [comment]
Thank you for the quick answer..
Do you mean running something like this?
`run: echo -e '[url "git@github.com:"]\n  insteadOf = "https://github.com/git@github.com:"' >> ~/.gitconfig`

**Comment by kwladyka** [comment]
I think `git remote set-url origin git@github.com:user/repo.git`

**Comment by zivkaziv** [comment]
Sorry for being so junior:)
Is it instead of `uses: actions/checkout@v1`?

**Comment by kwladyka** [comment]
Do you have this issue on `uses: actions/checkout@v1`?
It is not instead.

Generally with `https://github.com/user/repo.git` there is no username info.
With `https://user@github.com/user/repo.git` it is username. Also with `git@github.com:user/repo.git`.

In my case the solution was `actions/checkout@v1` with `https://github.com/user/repo.git` instead of `actions/checkout@master`.

**Comment by zivkaziv** [comment]
So do you mean to set the step something like this?

```
  - name: Checkout server
        uses: actions/checkout@v1
        with:
          repository: https://user@github.com/user/repo.git
          ref: refs/heads/master
          token: ${{ secrets.GitHub_PAT }}
```
And yes. `actions/checkout@v1` didn't solve it in my case

**Comment by kwladyka** [comment]
yes, or `git@github.com:user/repo.git`. I didn't try your case. One of this should work.

**Comment by zivkaziv** [comment]
Well.. Unfortunately it didn't work.. It seems that I have to use SSH for it

**Comment by thboop** [comment]
@zivkaziv, I've been trying to reproduce your issue but have been unable to do so. Could you please try the following:

Please try
```yaml
- uses: actions/checkout@v1
  with:
    repository: myAccount/myRepository  #For example thboop/test-repo
    ref: refs/heads/master
    token: ${{ secrets.GitHub_PAT }} 
```
and make sure you have the secret `Github_PAT` set in your [secrets](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables) and ensure it has the correct reading permissions
