### ISSUE TITLE
Checkout does not work with specific on another repository

### ISSUE THREAD

**Issue by mwestphal** [actions/checkout#629]
Trying to clone another repository on a specific commit using this action, it does not seems to work, even though the commit is indeed present in the repository.

```
    - name: Checkout VTK 
      uses: actions/checkout@v2
      with:
        repository: Kitware/VTK
        submodules: 'true'
        path: './depencies/vtk'
        ref: 37fe47d9
```
Am I doing something or is it not supported/a bug ?
