### ISSUE TITLE
$GITHUB_WORKSPACE moves when using with.path on repo where action is executed

### ISSUE THREAD

**Issue by Xilonz** [actions/checkout#63]
$GITHUB_WORKSPACE moves when using with.path on repo where action is executed (or when first fired?)
`Repository is current at '/home/runner/work/repo/repo', move to '/home/runner/work/repo/site'.`

This looks like it was intended by the author, but there's no (documented) way to avoid this. 
In my use-case, I have 2 repo's: One with my site's files and one with ansible-playbooks for deployment:
```yaml
    - uses: actions/checkout@v1
      with:
        repository: ${{ github.repo }}
        ref: ${{ github.sha }}
        path: $GITHUB_WORKSPACE/site
    - uses: actions/checkout@v1
      with:
        repository: user/ansible
        ref: master
        token: ${{ secrets.GIT_PAT }}
        path: $GITHUB_WORKSPACE/ansible
        fetch-depth: 1 
```
The goal is to have both of these available in a docker action $GITHUB_WORKSPACE, so I have access to both repo's inside a docker action. I know there are other solutions for this, but this is the most elegant way. 

-edit- I experienced this gives issues with .github/* files not being on their expected places, so I understand that $GITHUB_WORKSPACE has to move with its primary repo. I'd still like to know how I then would be able to achieve something like mentioned above.
