### ISSUE TITLE
[bug] PRs created by dependabot will always fail the check

### ISSUE THREAD

**Issue by waki285** [actions/checkout#636]
Pull Requests created by dependabot will always fail the check.
However, if you run `Re-run all jobs`, they will be executed successfully.

<details>
<summary>.github/workflows/main.yml</summary>

```yaml
name: npm CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: npm install
        run: "npm install"

      - name: eslint and prettier
        run: "npm run fix"
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: ESLint"
```

</details>

Error message:
![Input required and not supplied: token](https://user-images.githubusercontent.com/67305123/141111655-e09120cf-b91b-4782-a1d6-5bf4fc5966e4.png)

I have set my personal access token to `ACCESS_TOKEN` in Secrets.
