### ISSUE TITLE
Push fails when running from pull requests from a different user

### ISSUE THREAD

**Issue by felds** [actions/checkout#644]
Although committing and pushing from the same account is possible with v2, whenever the workflow is running from a pull request made by a different user, the HEAD comes as detached and pushing back is not possible.

### Steps to reproduce:

1. Create new a repo with user 🐮 (ex: `🐮/date-test`)
2. Add the following workflow to the repo:
    ```yaml
    on: [pull_request]
    
    jobs:
      add_date:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Add date
            run: date > date.txt
          - name: Push it 
            run: |
              git config --global user.email "actions@github.com"
              git config --global user.name "GitHub Action"
              git add date.txt
              git commit -m "Add date"
              git push
    ```
1. Fork the repo from user 🐷;
2. Make some changes, commit, and create a new PR.
