### ISSUE TITLE
Ref and fetch-depth are getting ignored

### ISSUE THREAD

**Issue by PleaseStopAsking** [actions/checkout#659]
I am seeing an issue when specifying a `ref` and `fetch-depth` where they are getting ignored and I am unsure why that is. My workflow is called via `workflow_dispatch` with different input values and each time its called, it looks for new releases and if found, will update my `docker-compose` file as needed.

The first invocation of the `workflow_call` always works, its the subsequent calls that fails as the checkout action is not pulling the latest commit from the `ref` branch as expected.

My action is below for reference.

```
name: Update Package Version
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      repo:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  check_for_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.token }}
          fetch-depth: 0
      - name: Get latest release
        id: getLatestRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ inputs.repo }}
          excludes: prerelease, draft
      - name: Update version in compose file
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "${{ inputs.image }}:v?[^/\n]*"
          replace: "${{ inputs.image }}:${{ steps.getLatestRelease.outputs.release }}"
          regex: true
          include: "docker-compose.yml"
      - name: Check modified
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update $image to $version" -a
          git push
        env:
          image: ${{ inputs.image }}
          version: ${{ steps.getLatestRelease.outputs.release }}

```

![image](https://user-images.githubusercontent.com/35308946/146940737-cfe32b78-f680-4cbc-9048-04327d95c69e.png)
