### ISSUE TITLE
Checkout small files only

### ISSUE THREAD

**Issue by pcgeek86** [actions/checkout#663]
I have some large files in my repository that are slowing down the checkout process. To work around this locally, I can use the following command:

`git clone --no-checkout --filter=blob:limit=1m`

However, I cannot find any ways to pass in these additional options to the `checkout` action.

Any ideas how to skip large files with this checkout action?

**Comment by jakub-g** [comment]
Note GitLab supports `GIT_FETCH_EXTRA_FLAGS` which can be used for that purpose:

- https://docs.gitlab.com/ee/ci/large_repositories/
- https://docs.gitlab.com/ee/ci/runners/configure_runners.html#git-fetch-extra-flags

**Comment by flying-sheep** [comment]
As a hack, I assume one could do the following:

```yaml
# sparse checkout to set the blob:none filter, but include all files
sparse-checkout: '/*/'
# allow interacting with the Git history
fetch-depth: 0
```

That way, we get a clone with intact history but no old blobs being downloaded.

A real fix is in https://github.com/actions/checkout/pull/1396
