### ISSUE TITLE
Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by jason-ausmus** [actions/checkout#664]
Hello,

I'm attempting a rollback flow using `actions/checkout@v2`. The problem is that I need to use a PAT in order to rollback commits that change Github Workflows and when I pass that PAT into actions/checkout, I get an error.

`Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled`

My workflow:
```
name: "Dev Deploy"
on:
  workflow_run:
    workflows: ["Versioning"]
    types: [completed]
jobs:
  fail_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: |
          exit 1
  rollback-on-failure:
    runs-on: ubuntu-latest
    needs: [fail_job]
    if: always() && needs.fail_job.result == 'failure'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - run: chmod +x environment/rollback.sh && ./environment/rollback.sh
```
The PAT used has the permissions to change workflows, as well as repository permissions. The issue seems to be that the action doesn't allow me to set a username before it tries to fetch the repository.

**Comment by adamevers** [comment]
I'm having similar issues. Did you ever find a fix @jason-ausmus? 

My workflow:
`
name: Android Beta Prod Distribution

on:
  push:
    branches:
      - android-beta-prod-workflow

jobs:
  beta-distribution:
    runs-on: ubuntu-latest
    name: Beta Distribution
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v1

    - name: Clone secrets
      uses: actions/checkout@v2
      with:
        repository: believrapp/api-env
        ref: main
        path: cloned-secrets
        token: $ {{ secrets.GH_TOKEN}}
`

**Comment by svc-instala** [comment]
same issue here with a PAT

**Comment by jason-ausmus** [comment]
@adamevers surprisingly it did start working for me when I added the `repository` to the with `with` statement. I can't really account for why that fixed it, but it's been running smoothly for me now since I did that.

**Comment by MikulasMascautanu** [comment]
I'm also experiencing the same issue. I wanted to add a checkout of another **private** repo, that lives in the same organisation as the original **private** repo which the workflow is in.

My code:
```
     - name: Checkout the private repo in which the workflow lives :heavy_check_mark: 
        uses: actions/checkout@v2
      - name: Checkout a public repo to see if it works :heavy_check_mark: 
        uses: actions/checkout@v2.3.4
        with:
          repository: actions/checkout
          ref: main
      - name: Checkout another private repo in the same organisation :x: 
      (and provide a PAT with repo, read:user and user:email permissions)
        uses: actions/checkout@v2.3.4
        with:
          repository: org/private-repo
          ref: master
          token: $MY_PAT
```

The error:
![image](https://user-images.githubusercontent.com/68233869/153207440-1bc6a69a-64b4-4335-97bd-4ad31d4639ad.png)

**Comment by charlesanim499** [comment]
@MikulasMascautanu Were you able to fix this issue ? If yes, please do share. thank you

**Comment by dszakallas** [comment]
I stumbled into the same error message and found this issue. However in my case, the cause of the problem was that the token expired. :sweat_smile:
Adding it here, in case it helps folks. The error message is very undescriptive.

**Comment by Ritalina** [comment]
Has anyone found a solution to this issue? I have the same error and nothing seems to work

**Comment by MikulasMascautanu** [comment]
Hi, sorry for my late response.
I did NOT solve the issue, I used a different approach for my original task.
Sorry:/

**Comment by MichaIng** [comment]
You definitely use a PAT which has an expiry date and is not expired?

**Comment by Ritalina** [comment]
> Hi, sorry for my late response. I did NOT solve the issue, I used a different approach for my original task. Sorry:/

Thanks, I think the same, I will change my strategy. :)

**Comment by shrutiburman** [comment]
> 

Thanks for the tip! I wouldn't have figured that out on my own. :)

**Comment by david-renner-dwg** [comment]
@MichaIng Is the PAT something you generate yourself? Or is that the same access token we can reference with ${{secrets.GH_TOKEN}}

**Comment by MichaIng** [comment]
> @MichaIng Is the PAT something you generate yourself? Or is that the same access token we can reference with ${{secrets.GH_TOKEN}}

The "Personal Access Token" is what you need to create yourself in your account's developer settings. In my case, AFAIK, it was required for a workflow to checkout and push to a branch/PR created by dependabot.

**Comment by pcbuildpluscoding** [comment]
I needed to auto-create a release for my private golang repository, and came across this page in my investigations. Being new to github actions and workflows, I needed to resolve how to inject `https://$GH_TOKEN@github.com` instead of `https://github.com`
gitconfig statement into my workflow setup. Found [this blog post](https://blog.fabianmendez.dev/how-to-use-private-go-module-in-github-actions) which exactly solved my issue. Posting here in case someone else needs a pointer

**Comment by ScottG489** [comment]
Using a token that doesn't expire fixed this issue for me.

Could someone explain if there is some underlying reason why these tokens are rejected though?

If GitHub is going to reject tokens that don't expire then they shouldn't let you generate them in the first place.

**Comment by pcbuildpluscoding** [comment]
> 
@ScottG489 - have a look at [this blog post](https://blog.fabianmendez.dev/how-to-use-private-go-module-in-github-actions). Seems there are 3 requirements for a valid token applied in actions.
1. It belongs to the right user or organization account
2. It has repository scope
3. It is not expired

**Comment by MichaIng** [comment]
For a simple checkout indeed no PAT is required.

**Comment by yamavol** [comment]
I prepared two repositories, repo1 and repo2 with almost identical GH-actions setup.  
It checkouts a same private repo from the same organization I belong.

```
  - uses: actions/checkout@v3
    with: 
      repository: 'myorg/my-another-private-repo'
      ref: master     # note: not present in repo2
      path: tmp-path-something
      token: $${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }} # classic PAT used
```
One succeeds, while the other don't. 

This is the failing log from repo1.
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
```

Today, I created a new repository (repo2). This works fine.
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master:refs/remotes/origin/master
  remote: Enumerating objects: 165, done. 
```

The only difference I notice, is the name of the default branch. repo1 was made in 2019, and have master branch. repo2 was made in 2022, and have main branch. I wonder if this difference is causing this issue. 

P.S. If I don't specify the `ref: master` in repo1, I get this error.

```
Determining the default branch
  Retrieving the default branch name
  Bad credentials
  Waiting 14 seconds before trying again
  Retrieving the default branch name
  Bad credentials
  Waiting 17 seconds before trying again
  Retrieving the default branch name
  Error: Bad credentials
```

**Comment by boly38** [comment]
my 2 cents: it would be great that github checkout action automatically detect this kind of error return to provide a tips on this: please verify your token and expiration date. I think in many case this is just "private" + "expired" or "wrong" PAT configuration?

**Comment by papanito** [comment]
@boly38 good idea. I was also very confused by the message, but ultimately I juts had the token not configured

**Comment by gabrielcerioni** [comment]
Should the requirement to have an expiration date in the PAT be documented here?
https://github.com/marketplace/actions/checkout#usage

**Comment by pidgezero-one** [comment]
I'm having the same problem as MikulasMascautanu, but I don't think there's anything wrong with my PAT. I'm only getting this error on one private repo in the entire organization. Every other repo is completing just fine, and they all use an identical CI yaml (the only difference being that this one specifies a working directory).

Is there some repo setting in Github that I might need to change?

**Comment by ocervell** [comment]
Personally I didn't have a PAT in my GitHub workflow and it worked fine till 2 weeks ago for simple checkout, so not sure what happened on GitHub side here.

**Comment by alexey-berdyugin** [comment]
Looks like I found the root cause of this behavior. 
When the first actions/checkout@v2 performs without any options for current repository it caches github token in local git store and further the same token is used. I added flag "persist-credentials: false" to the first checkout step and further steps with github communications started work (ad-m/github-push-action or simple git push https://user:token@github/org/repo). Looks like git cli ignores incoming token if it is already stored in local storage..
At lest it helped me.. :-)

**Comment by pidgezero-one** [comment]
@alexey-berdyugin Interesting! Could I please see an example of how you configured this? I saw [this post](https://github.com/orgs/community/discussions/25275) which is making me scared to try it !

**Comment by alexey-berdyugin** [comment]
In my case:
`      
     - name: Checkout Application Repo
        uses: actions/checkout@v3
        with:
          path: app_repo
          persist-credentials: false
# other steps
     - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.get_github_token.outputs.git_app_token }}
          directory: app_repo
          branch: ${{ github.ref }}
# Or simple
     - name: Manual push
        run: |
          cd app_repo
          git config --local user.email "4github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git diff-index --quiet HEAD || git commit -a -m "Test"
          gut push https://<any-user_or_app-id>:<token>@github.com/user_or_org/repo.git
`

**Comment by ocervell** [comment]
It started working again for me after some time. Probably a misconfig and the cache got erased after a while.

**Comment by willinDrive** [comment]
Works for me with `actions/checkout@v2`, but with `actions/checkout@v3` shows error from the topic

**Comment by ddsharpe** [comment]
I had the same error on multiple repositories.  Tried checkout@v3 and v4, but result was the same. For me, replacing the Action secret in each repository with a new Personal Access Token (with expiration) solved it.

**Comment by MichaIng** [comment]
I had the strange cases where repeating the failed job(s) after updating the PAT did not work. Finally it did work when I re-triggered the same workflow with an empty amended commit. Are secrets somehow hardcoded once a workflow/job is triggered, so that re-runs are not affected by changed secrets (and variables)?

**Comment by ljmf00-wekaio** [comment]
I'm having the same issues, inconsistent failures on checkout with a PAT.

**Comment by ljmf00-wekaio** [comment]
Setting this before the action solved the issue:
```
git config --global credential.https://github.com.username git
git config --global credential.https://github.com.password <your-pat>
```

**Comment by sergiomayo44** [comment]
I'm using a gitlab repo, and unless aI create a token, i can't pull.
So inside the ".git" folder, I modified the file "config". 
In the [remote "origin"] section set url to 
url = https://yourusername:yourpersonalaccesstoken@github.com/...

**Comment by themathmagician** [comment]
In my case the PAT was correct, but the checkout branch did not exist. What and oddly worded error message!

**Comment by omgupta1608** [comment]
None of the different workarounds and solutions worked for me. Tried the following
- With and without `persist-credentials: false`
- With and without token expiry date
- With and without:
```
env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
steps:
- run: git config --global credential.https://github.com.username myusername
- run: git config --global credential.https://github.com.password $GH_ACCESS_TOKEN
```
- All checkout versions `v2`, `v3` and `v4`

Nothing works for me!

**Comment by frans-slabbekoorn** [comment]
I got it working using checkout@v3 with `persist-credentials: false` using the following config:

```yaml
git config --global user.name myusername
git config --global user.email myemail
git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
...git operations
```

**Comment by r-plus** [comment]
I got same error after re-generate PAT.
But resolved with update `runs-on` from `ubuntu-20.04` to `ubuntu-latest`

**Comment by gimi-anders** [comment]
I am having the same issue. It only happens for PRs created by dependabot though, and the strange thing is that if I close the PR and then reopen it, then it works. 

I have tried to apply all fixes suggested here, but nothing seems to work.

**Comment by georg-eckert-zeiss** [comment]
I was able to fix this by using a classic token with the permissionns `public_repo`, `read:user` and `user:email`.

Cheers

**Comment by plowsof** [comment]
this is one of those 'why is nothing easy / the world is against me' problems. the comment from @frans-slabbekoorn fixed it for me. Thank you to others who mentioned the PAT requiring an expiry date.

**Comment by RobertDeibel** [comment]
Hey, just stumbled across this, while encountering the same error message. We use a *organization wide deploy key*, when checking out with the `recursive` and `token` option during parent repo checkout I encountered the same issue. It was fixed by explicitly checking out the submodule as an own repo:
```
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
        #   submodules: recursive                      <----- this is not working
        #   token: ${{ secrets.DEPLOY_KEY }}   <-----
      - name: clone submodule
        uses: actions/checkout@v4
        with:
          repository: <organization>/<repo-name>
          ref: main
          path: ${{ github.workspace }}/path/to/submodule
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          persist-credentials: false
```

Maybe this will help someone.

**Comment by georg-eckert-zeiss** [comment]
> I was able to fix this by using a classic token with the permissions `public_repo`, `read:user` and `user:email`.
> 
> Cheers

Please explain the downvotes so I can learn from it.

**Comment by MichaIng** [comment]
> Please explain the downvotes so I can learn from it.

I did not downvote it, but I did not find your comment very helpful either. It is potentially problematic without more context, given that people tend to just copy&paste (take over without scrutinise whether it fits to their use case) all they find. Which PAT (classic, modern, permissions?) did throw the error before? Then narrow down the minimal required change for this case. If it was not already known/commented before, then we might have another condition, everyone can check 🙂.

In my case, `public_repo` is sufficient to check out a public repo with a classic PAT, while permissions to access user data and email is not required. In my case, it was the missing expiry date only, which made the difference, to checkout a public repo with classic as well as modern PAT. So that is one condition everyone can check.

**Comment by xeruf** [comment]
> Hey, just stumbled across this, while encountering the same error message. We use a _organization wide deploy key_, when checking out with the `recursive` and `token` option during parent repo checkout I encountered the same issue. It was fixed by explicitly checking out the submodule as an own repo:
> 
> ```
>       - name: Checkout
>         uses: actions/checkout@v4
>         with:
>           persist-credentials: false
>         #   submodules: recursive                      <----- this is not working
>         #   token: ${{ secrets.DEPLOY_KEY }}   <-----
>       - name: clone submodule
>         uses: actions/checkout@v4
>         with:
>           repository: <organization>/<repo-name>
>           ref: main
>           path: ${{ github.workspace }}/path/to/submodule
>           ssh-key: ${{ secrets.DEPLOY_KEY }}
>           persist-credentials: false
> ```
> 
> Maybe this will help someone.

Except this makes it ignore the referenced commit of the submodule, making the build non-reproducible

See also https://github.com/actions/checkout/issues/1382

**Comment by RobertDeibel** [comment]
> > Hey, just stumbled across this, while encountering the same error message. We use a _organization wide deploy key_, when checking out with the `recursive` and `token` option during parent repo checkout I encountered the same issue. It was fixed by explicitly checking out the submodule as an own repo:
> > ```
> >       - name: Checkout
> >         uses: actions/checkout@v4
> >         with:
> >           persist-credentials: false
> >         #   submodules: recursive                      <----- this is not working
> >         #   token: ${{ secrets.DEPLOY_KEY }}   <-----
> >       - name: clone submodule
> >         uses: actions/checkout@v4
> >         with:
> >           repository: <organization>/<repo-name>
> >           ref: main
> >           path: ${{ github.workspace }}/path/to/submodule
> >           ssh-key: ${{ secrets.DEPLOY_KEY }}
> >           persist-credentials: false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe this will help someone.
> 
> Except this makes it ignore the referenced commit of the submodule, making the build non-reproducible
> 
> See also #1382

You can pass a reference parameter to this action that holds the correct SHA you want to checkout. To do this from an action you can save it in an environment variable.

```
  - name: Get submodule SHA
        run: |
          cd root_dir
          echo "Getting the submodule at: ""$(git rev-parse HEAD:path/to/submodule)"
          echo "submodule_sha=$(git rev-parse HEAD:path/to/submodule)" >> "$GITHUB_ENV"
          cd ${{ github.workspace }}
      - name: clone submodule
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository: <organization>/<repo>
          ref: ${{ env.submodule_sha }}
          path: ${{ github.workspace }}/path/to/submodule
          persist-credentials: false
```
