### ISSUE TITLE
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/data/workflow_dir/_actions/actions/checkout/v2.4.0'.

### ISSUE THREAD

**Issue by imam** [actions/checkout#692]
Hi,

For some reason since yesterday, whenever Github Action ran, they'll failed on the first attempt, but will always succeed on the second attempt.

The error message:

```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/data/workflow_dir/_actions/actions/checkout/v2.4.0'. Did you forget to run actions/checkout before running your local action?
```

Would be lovely if anyone can help, thanks! :)

![image](https://user-images.githubusercontent.com/8213031/153370390-c27a3745-1555-45be-b270-ebf8887ccfef.png)

![image](https://user-images.githubusercontent.com/8213031/153370730-1f6467dc-ea26-4230-b576-dc09748618e4.png)

**Comment by imam** [comment]
Additional notes:

I've tried to downgrade the `actions/checkout` to 2.3.x and 2.2.x, same error messages occured

**Comment by homeaidepi** [comment]
Any word on this. Lots of people including me are seeing this on post run.  My issue stems from what I believe is I connect via checkout@v2 or v3 to a different repo then the action is running under and if I remove the blocks for that everything works so some wires get crossed when you are on a repo in the main action that kicks off the workflow but then inside that workflow you use a different repo and wires get crossed on Post Run, but everything worked in run. Weird:  Can't find 'action.yml', 'action.yaml' or 'Dockerfile'  Its such a dumb error cause if the action wasnt there it could have never run. Like how the heck CANT a post run find an action that the main run just executed from...

**Comment by homeaidepi** [comment]
> 
Talking out my problem gave me some inspiration. Finally a breakthrough.   So I just added this to the end of my action
`# Checkout the repo
    - uses: actions/checkout@v3
      with:
          # Repository name with owner. For example, actions/checkout
          Default: ${{ github.repository }}`
So Post Run needs to get connected back with this running actions repo and not whatever repo you connect to perform some external operation.  Silly I need to remind the Action what its repo is, (by rechecking out to "this" or "here") but whatever, I got it and hope it helps someone.

**Comment by inlet** [comment]
I'm experiencing the same in combination with:

```
- name: Upload result to GitHub Code Scanning
  uses: github/codeql-action/upload-sarif@v1
  with:
    sarif_file: snyk.sarif
```

**Comment by kaleidawave** [comment]
Was having the same problem. Looks like it only currently supports it as a whole job rather than in a step. https://github.community/t/actions-reusable-workflow-failing-to-find-action-yml-that-does-exist/231258/3

**Comment by DmitriiKalashnik** [comment]
**multi-checkout-action**

checkout@v2 should be the first one

```
- uses: actions/checkout@v2
- name: Checkout private actions
  uses: vweevers/multi-checkout-action@v1
  with:
    token: ${{ secrets.GITHUB_MACHINE_TOKEN }}
    repositories: my-org/example-action my-org/another-action@v3.1.0 my-org/third-action
```
