### ISSUE TITLE
Fail step if ref has typos

### ISSUE THREAD

**Issue by yongzhang** [actions/checkout#693]
Hi,

I have step like this:
```
    - name: Checkout app repo
      uses: actions/checkout@v2
      with:
        repository: 'whatever'
        ref: '${{ env.REF }}'
        token: 'whatever'
```
The $REF is from user input, when user inputs a wrong REF, the step won't fail but pull default branch instead, is it able to fail the step if a wrong ref there? Thanks.
