### ISSUE TITLE
Unable to specify path

### ISSUE THREAD

**Issue by rumblefrog** [actions/checkout#7]
Upon attempting to set the checkout path

https://github.com/actions/checkout/blob/af513c7a016048ae468971c52ed77d9562c7c819/action.yml#L19-L20

The following error was emitted:
```
Your workflow file was invalid: .github/workflows/build.yml (Line: 22, Col: 7): Unexpected value 'path'
```

My action file

```yml
name: Build & Deploy
on: [push]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.12' ]

    steps:
    - name: Use go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        version: ${{ matrix.go-version }}
      id: go

    - name: Checkout source
      uses: actions/checkout@master
      path: ${{ go.module-path }} # Line 22

    - name: Install server dependencies
      working-directory: ${{ go.module-path }}
      run: go get -v -t -d -u ./server

    - name: Build server
      working-directory: ${{ go.module-path }}
      run: go build ./server
```

Minimal reproduce case would be the golang starter workflow: https://github.com/actions/starter-workflows/blob/329e9a8e162a10b5e131d13efb78e57a5b86fdd6/ci/go.yml

**Comment by TingluoHuang** [comment]
@rumblefrog 
what about :)
```
    - name: Checkout source
      uses: actions/checkout@master
      with:
        path: ${{ go.module-path }} # Line 22
```
