### ISSUE TITLE
action delete content after checkout step was finished

### ISSUE THREAD

**Issue by NSLog0** [actions/checkout#703]
I'm trying to build a workflow with terraform. there is a step to call `terraform plan --var-file="./terraform-dev.tfvars"` it turns out that `actions/checkout@v2` remove all my code. so I cannot refer to any `tfvars`

The step of checkout: 

<img width="738" alt="Screen Shot 2565-02-22 at 18 35 10" src="https://user-images.githubusercontent.com/1640817/155124654-d7273451-fd99-4a6c-af69-593ad17dc40a.png">

Error details: 
<img width="1101" alt="Screen Shot 2565-02-22 at 12 00 30" src="https://user-images.githubusercontent.com/1640817/155159579-7de24d9f-bb85-4e32-a621-265e0cc10b16.png">

code snippet:
```
steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
```

Any idea? thannks
