### ISSUE TITLE
fatal: You are not currently on a branch. To push the history leading to the current (detached HEAD)

### ISSUE THREAD

**Issue by 1Mark** [actions/checkout#719]
I've already read https://github.com/actions/checkout/issues/124 

I'm trying to push a commit during **release** but no success

```
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>
```
`python-publish.yml` looks like
```
name: Upload Python Package

on:
  release:
    types: [published,  workflow_dispatch]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0 # probably don't need this 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Bump package version to ${{ github.ref_name }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        pip install bump2version==1.0.1
        # Here we don't use ${{ github.ref_name }} since github action variables can't do sed/cut/slicing
        # Remove leading 'v' from the tag name
        bump2version --new-version ${GITHUB_REF_NAME#v} minor
        # must supply either patch minor or major see https://github.com/c4urself/bump2version/issues/244
        # but it's an ignored argument argument
        git show
        git push
```

**Comment by Fleshgrinder** [comment]
Seems like things changed in v3 and this is what I have in the log:

```
  /usr/bin/git checkout --progress --force refs/remotes/pull/3/merge
  Note: switching to 'refs/remotes/pull/3/merge'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at 4de7325 Merge 90e2ccdb6fca8684e7b90e1f2f0e449752846580 into d8b663327122c864bd9141074ecd5901252d7869
```

This also means that the https://github.com/actions/checkout#Push-a-commit-using-the-built-in-token section is not correct anymore.

**Comment by Fleshgrinder** [comment]
I was able to get it to work with v3:

```yaml
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add --all .
        git commit --message test
        git push
```

If the commit should trigger workflows things get more complicated and a personal access token (PAT) is required:

```yaml
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.pat }}
    - run: |
        user=$(gh api /user)
        user_name=$(jq -r '.login' <<<"$user")
        user_email=$(jq -r ".email | \"$user_name@users.noreply.github.com\"" <<<"$user")
        git config user.name "$user_name"
        git config user.email "$user_email"
        git add --all .
        git commit --message test
        git push
```

Note that the fallback email address might not be correct if the user created the email address after July 18, 2017.[^1]

Note further that it is not possible to cancel the workflow, the only way to stop the current workflow and let it run again is via `exit 1`.[^2]

[^1]: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#about-commit-email-addresses
[^2]: https://github.com/actions/runner/issues/662

**Comment by Shelton2020** [comment]
Bring it home

**Comment by 1Mark** [comment]
> Seems like things changed in v3 and this is what I have in the log:
> 
> ```
>   /usr/bin/git checkout --progress --force refs/remotes/pull/3/merge
>   Note: switching to 'refs/remotes/pull/3/merge'.
>   
>   You are in 'detached HEAD' state. You can look around, make experimental
>   changes and commit them, and you can discard any commits you make in this
>   state without impacting any branches by switching back to a branch.
>   
>   If you want to create a new branch to retain commits you create, you may
>   do so (now or later) by using -c with the switch command. Example:
>   
>     git switch -c <new-branch-name>
>   
>   Or undo this operation with:
>   
>     git switch -
>   
>   Turn off this advice by setting config variable advice.detachedHead to false
>   
>   HEAD is now at 4de7325 Merge 90e2ccdb6fca8684e7b90e1f2f0e449752846580 into d8b663327122c864bd9141074ecd5901252d7869
> ```
> 
> This also means that the https://github.com/actions/checkout#Push-a-commit-using-the-built-in-token section is not correct anymore.

Thanks for your assistance but im trying to get it to push when creating a release

`ref: ${{ github.event.pull_request.head.ref }}` won't work for me.

**Comment by Fleshgrinder** [comment]
Sorry that I missed it, you have:

```yaml
on:
  release:
    types: [published,  workflow_dispatch]
```

This actually should be to work as expected since `workflow_dispatch` is not a valid `release` type ([see](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release)):

```yaml
on:
  release:
    types: [published]
  workflow_dispatch:
```

In your case it is not entirely clear where you want to commit and push to, since a release can refer to any commit within the entire history of the repository. I see multiple ways on how to solve this, but it would be important to know what it is you exactly want to achieve.
