### ISSUE TITLE
terminal prompts disabled when submodules: true

### ISSUE THREAD

**Issue by piuy11** [actions/checkout#738]
Having issue with submodules.
I have a private repo which has other private repos as submodules. Tried with the workflow below, but keeps showing following error message for all my submodules:
```
/usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
Cloning into '<MY_SUBMODULE_REPO>'...
Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
```

However, since removing line with submodules from workflow worked (without cloning submodules), I assume that auth process is broken.

My workflow:

```
name: Testing
on:
  push:
    branches: [ test-action ]
jobs:
  steps:
    runs-on: self-hosted
    steps:        
      - uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY }}
```

What I tried:

- Checked secrets
- Tried with token instead of ssh-key (including checking scopes of PAT) 
- Change self-hosted to ubuntu-latest

All didn't work.
