### ISSUE TITLE
Duplicate name in working directory during checkout

### ISSUE THREAD

**Issue by miguel-martinez-tfs** [actions/checkout#739]
Hello.
I'm having some troubles using actions/checkout@v2 on a self-hosted runner. Here's the current yaml file:
```
name: Test Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  RunUnitTests:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
```
Workflow logs:

```
Run actions/checkout@v2
  with:
    repository: org/test-ui
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
Error: An error occurred trying to start process '/home/runner/externals/node12/bin/node' with working directory '/home/runner/_work/test-ui/test-ui'. No such file or directory
```
The name "test-ui" is duplicated on the working directory. I'd like to know what could've caused this issue (is it possible that the runner is interfering?), and what steps can I take to resolve it. Thanks in advance.
