### ISSUE TITLE
Input 'submodules' not supported when falling back to download using the GitHub REST API with standard setup

### ISSUE THREAD

**Issue by kbegiedza** [actions/checkout#758]
I'm using standard hosted runner with standard actions/checkout@v3, but action is unable to checkout & pull my public repo submodule.
When I executed my pipeline I got:
`Error: Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH.`

It's pretty weird that I'm using ubuntu-latest (20.04) and don't have Git >= 2.18 in PATH.

my pipeline:
```yaml
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ghcr.io/kbegiedza/cuda:11.6.0-sdk

    steps:
    - uses: actions/checkout@v3
      with:
        submodule: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
```

**Comment by kbegiedza** [comment]
I can see that ubuntu-latest (now 20.04) have installed proper version of git:

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#tools

**Comment by kbegiedza** [comment]
Added below step as workaround:

```yaml
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
```

**Comment by nafg** [comment]
I'm getting this error on windows-latest -- https://github.com/slick/slick/actions/runs/2563233013

**Comment by RunningLeon** [comment]
same issue met in ubuntu18.04 and ubuntu 20.04

**Comment by andersonjwan** [comment]
Same issue here! This is my step that fails:

```yml
...
- name: Checkout
  uses: actions/checkout@v3
  with:
     submodules: true
```

**Comment by joshuaVayer** [comment]
In my case, the mistake was caused because I was using the `PATH` environment variable. The issue was resolved by simply renaming my variable. Hope this help.

Errored :
```
env: 
  PATH: "root/directory"
 ```
 Working : 
 ```
 env: 
   ANOTHER_PATH: "root/directory"
 ```

**Comment by andersonjwan** [comment]
> Same issue here! This is my step that fails:
> 
> ```yaml
> - name: Checkout
>   uses: actions/checkout@v3
>   with:
>      submodules: true
> ```

I've appeared to have indirectly fixed the issue indirectly. For those that are using a separate container/image for the job run, you must ensure your image has Git v2.18+ installed; otherwise, you will receive the issues I've faced.

Here is a complete example:

```yaml
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    container: <image with Git v2.18+ installed>
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
```

**Comment by zccrs** [comment]
You need to install the "git > 2.18" in the "ghcr.io/kbegiedza/cuda:11.6.0-sdk" container before actions/checkout@v3

**Comment by peppapiggyme** [comment]
I just faced to same issue recently. 

Thanks to the suggestions of the latest posts, I have solved it as follows.

```
    runs-on: ubuntu-latest
    container:
      image: <your_image>

    steps:
    - name: Install git on container
      run: |
        apt update
        apt install -y git

    - uses: actions/checkout@v3
      with:
        submodules: true
```
