### ISSUE TITLE
Passing data from event payload to a docker step in a github workflow.

### ISSUE THREAD

**Issue by christian-weiss** [actions/checkout#76]
In general i like the documentation but a tracer bullet is missing (at least for me) to establish the following Please give me a tracer bullet on how to pass data from external, to github workflow, to docker-based step.

Lets assume, that i trigger a github workflow by sending a "repository_dispatch" event of type "my_custom_event" as follows:
```
curl -X POST -i -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_PERSONAL_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" -d @custom_event.json https://api.github.com/repos/mydockerhubnamespace/myreponame/dispatches
```
with following payload:
```
{
  "event_type": "my_custom_event",
  "client_payload": {
    "dockerhubrepo": "mydockerhubnamespace/mydockerhubrepo",
    "dockerhubtag": "latest"
  }
}
``` 
My workflow will look like this to start on that event:
```
name: CI
on: 
  repository_dispatch:
    types: [my_custom_event]
jobs:
  security:
    name: "Security related jobs"
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    steps:
      - name: "Vulnerability Scan Of Docker Images With Trivy"
        uses: docker://aquasec/trivy:latest
        with:
          args: $DOCKER_REPO:$DOCKER_TAG
```

What do i need to do to substitute the $DOCKER_REPO with "mydockerhubnamespace/mydockerhubrepo" and $DOCKER_TAG with "latest"?
