### ISSUE TITLE
Allow checking out multiple refs at the same time

### ISSUE THREAD

**Issue by TomasHubelbauer** [actions/checkout#763]
Hi, I would like to use the checkout action like so:

```yml
- name: Check out the Git repository and its main branch (not detached HEAD)
  uses: actions/checkout@v3
  with:
    ref: [main, "refs/notes/*"]
    fetch-depth: 0
```

This would check out the main branch (with all of its history due to `fetch-deptch: 0`) and also `refs/notes/*` so that I have Git notes checked out and associated with the commits on main branch.

Currently, I have to run this extra step to achieve this:

```sh
git fetch origin "refs/notes/*:refs/notes/*"
```
