### ISSUE TITLE
`GITHUB_WORKSPACE` and `github.workspace` are different when running in container

### ISSUE THREAD

**Issue by nkakouros** [actions/checkout#785]
When using a container to run the checkout, the variables `${{ GITHUB_WORKSPACE }}` and `${{ github.workspace }}` are different. 

```yaml
---

name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch: ~

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
```

The [documentation for `github.workspace`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) says:

> The default working directory on the runner for steps, and the default location of your repository when using the [checkout](https://github.com/actions/checkout) action.

The [documentation for `GITHUB_WORKSPACE`](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) says:

> The default working directory on the runner for steps, and the default location of your repository when using the [checkout](https://github.com/actions/checkout) action.

I believe they should be set to the same value.
