### ISSUE TITLE
Multiple Checkout: first with a path info and second without a path info will not work

### ISSUE THREAD

**Issue by bauergeorg** [actions/checkout#792]
Multiple Checkout will not work. - If your first checkout has a path information and the second has no path information.

The action kills the first checkedout folder (thats okay). After the second checkout (without path info) the folder is empty (only the .git subfolder is there).

Here is an example:
```yaml
# Checksout action repository under local
- name: Checkout action own repository
  uses: actions/checkout@v3
  with:
    ref: ${{ github.ref }}
    path: local

# Display files and folders
- name: Display files and folders
  run: |
    pwd
    ls -a -R

# Checksout action repository under $GITHUB_WORKSPACE
- name: Checkout action other repository
  uses: actions/checkout@v3
  with:
    repository: githubtraining/community-contributors
    ref: main

# Display files and folders
- name: Display files and folders
  run: |
    pwd
    ls -a -R
```
