### ISSUE TITLE
Not able to checkout remote repo using secrets.GITHUB_TOKEN

### ISSUE THREAD

**Issue by shyam-ks** [actions/checkout#799]
Not able to checkout remote repo using secrets.GITHUB_TOKEN. Below scenario , checkout 1, 2 works. 3 fails. Is there a limitation for secrets.GITHUB_TOKEN on remote repos?

```
jobs:  
  test:
      name: test
      runs-on: self-hosted
      container: node:14-bullseye
      steps:
      - name: Checkout 1
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      
          
      - name: Checkout 2
        uses: actions/checkout@v3
        with:   
            token: ${{ secrets.MY_PAT }}  
            repository: remote-repo
            ref: 'main'     
            path: 'path-1'    
            
      - name: Checkout 3
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          repository: remote-repo
          ref: "master"
          path: "path-2"
```

**Comment by ukreddy-erwin** [comment]
did you get any solution?
Facing the same error on centos

**Comment by shyam-ks** [comment]
> did you get any solution? Facing the same error on centos

Checked with the support team. Says you can not checkout remote repo using secrets.GITHUB_TOKEN

**Comment by ukreddy-erwin** [comment]
I created a separate token but still same issue.

**Comment by noamgreen** [comment]
Same issue :-(

**Comment by 4441114417342316** [comment]
128
Waiting

**Comment by jacobevansgit** [comment]
`${{ github.token }}` is scoped to the current repository, so if you want to checkout a different repository that is private you will need to provide your own [PAT](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)

https://github.com/actions/checkout/blob/2541b1294d2704b0964813337f33b291d3f8596b/README.md?plain=1#L184

**Comment by igor-imaginemage** [comment]
I was facing this same issue and I was able to use a secret only if the secret name is GH_PAT, like this:

`token: ${{ secrets.GH_PAT }}`

**Comment by DennisGentry-Zoetis** [comment]
Yeah, I was never able to get GITHUB_TOKEN to work.  My thought was that our tokens need to be blessed by our organization's SSO or whatever it is, and that can't ever happen with a GITHUB_TOKEN because it's a one-time thing that is formed at the start of the action and goes away when it ends.

But there's no GitHub Enterprise documentation about it, so who knows?

I'm really not seeing the benefit of this action over a simple shell script.

**Comment by sudhakarinka** [comment]
Gentle people, 

apprepo
`
name: '🚀 Pull Request'
run-name: pr:${{github.ref_name}}:${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}

on:
  pull_request:
    branches:
      - '**'
    types: [opened, reopened, synchronize ]

jobs:
  find_moon_artefacts:
    name: '🔍 Find moon-artefacts'
    uses: '{ORG}/{REPO}/.github/workflows/workflow-on-affected-pr.yml@main'
    with:
      runs-on: 'ubuntu-latest'
      lookup: 'services' #lookup: 'services,projects' #do not give spaces between the comma
      sincehead: -4
      exclude: 'rdf'
`

workflowsrepo  has the above re-usable workflow ; expected to run during PR
`
name: '� workflow on affected PR; set moo,get repo, projects and services details'
run-name: pr:${{github.ref_name}}:${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}


on:
    workflow_call:
        inputs:
          runs-on:
            description: 'The runner to execute the job on'
            required: false
            type: string
            default: 'ubuntu-latest'
          environment:
                description: 'Environment to execute the job on'
                required: false
                type: string
                default: 'dev'  
          lookup:
              description: 'Lookup Comma-separated list of lookup items, "services, projects" etc'
              required: false
              default: 'services'
              type: string
          sincehead:
              description: 'Specify number of commits since HEAD, -ve number considers all commits, default is -0'
              required: false
              type: number
              default: -0
          exclude:
              description: 'Comma-separated list of items to exclude; a partial string match'
              required: false
              type: string
          tags:
              description: 'Comma-separated list of tags used for projects to be affected'
              required: false
              type: string        
          script:
                description: 'Script to execute'
                required: false
                type: string  
                default: 'affected-moon-artefacts.mjs'      
          wkfl_src_branch:
                description: 'Branch to source the workflows and script from'
                required: false
                type: string  
                default: 'main'     
                
jobs:
  on_pull_request:
    name: '⏱ Pull Request'
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.environment }}
      
    steps:
      - name: '🛎️ Checkout'
        uses: actions/checkout@v4
        with:
          ref: "${{github.head_ref || 'main'}}"
          fetch-depth: 0
      
      - name:  '🛎️ Checkout scripts'
        uses: actions/checkout@v4
        with:
          repository: 'xyz_ORG}/xyz_REPO'
          token: ${{ secrets.GH_PAT }}
          path: workflow-tools
          ref: ${{ inputs.wkfl_src_branch }}
`

both repos having secrets with same GH_PAT, GH_XYZ_PAT classic PAT with permissions for repos , pr etc...
GH_PAT though passedm still giving `Input required and not supplied: token`

passing `GH_XYZ_PAT` failes with 3 retrails to download 
do you see an issue in what i am doing!!

**Comment by DancingCorpse** [comment]
I meet the same issue "**_Input required and not supplied: token_**" as @sudhakarinka described, is there any way to resolve the multiple repos checkout issue in reusable workflows?

**Comment by jacobevansgit** [comment]
@sudhakarinka @DancingCorpse  If you are trying to use the secrets in reusable workflows/actions, you will need to pass them in explicitly via `inputs` (actions), or use `secrets: inherit`(workflows)

**Comment by julianCast** [comment]
For clarification, this should work?

Repo A workflow (caller). We pass the organization level secret we created in repo pk at organization level.
```yml
trigger-tests:
    uses: org/pk1/.github/workflows/test-e2e-website.yml@master
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
```
Repo B workflow (caller). We read the secret.
```yml
on:
   workflow_call:
    secrets:
      GH_PAT:
        required: true
...
- uses: actions/checkout@v4
  with:
     repository: org/pk1
     token: ${{ secrets.GH_PAT }}
```
