### ISSUE TITLE
`gecko-dev` checkout takes 10m

### ISSUE THREAD

**Issue by abitrolly** [actions/checkout#818]
A checkout of https://github.com/mozilla/gecko-dev repo takes 10m using this step.

```
      - uses: actions/checkout@v3
        with:
          repository: mozilla/gecko-dev
          path: gecko-dev
          fetch-depth: 0
```

![image](https://user-images.githubusercontent.com/8781107/171740388-7ec77d1c-a9cd-489d-9a58-7d18b1a67443.png)

https://github.com/abitrolly/firefox-lang-stats/runs/6713143940?check_suite_focus=true

Is it possible to speed up it somehow? Like through https://docs.github.com/en/rest/repos/contents#download-a-repository-archive-zip

**Comment by abitrolly** [comment]
Explicitly mentioning branch makes clone 1m slower.

```yaml
      - uses: actions/checkout@v3
        with:
          repository: mozilla/gecko-dev
          path: gecko-dev
          ref: master
          fetch-depth: 0
```

But the clone commands are the same https://github.com/abitrolly/firefox-lang-stats/runs/6716850948?check_suite_focus=true
