### ISSUE TITLE
Unable to checkout files, how to fox that?

### ISSUE THREAD

**Issue by ukreddy-erwin** [actions/checkout#819]
I am trying to checkout few repositories as part of my workflow.

For that, I am using the reference: [Checkout · Actions · GitHub Marketplace · GitHub](https://github.com/marketplace/actions/checkout)

And my workflow file.

```

# This is a basic workflow to help you get started with Actions

name: CIDependencies

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ r12.1_githubactions ]
  pull_request:
    branches: [ r12.1_githubactions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DownloadDependencies:
    runs-on: DevBuild2
    steps:
      - uses: actions/checkout@v3
        with:
          repository: company-inc/company-Installshield
          token: ${{ secrets.DM_TOKEN }}
          fetch-depth: 0      
      - uses: actions/checkout@v3
        with:
          repository: company-inc/company_BookShelf_and_MITI
          token: ${{ secrets.DM_TOKEN }}
          fetch-depth: 0    
       - uses: actions/checkout@v3
        with:
          repository: company-inc/company-DM-Dependencies
          token: ${{ secrets.DM_TOKEN }}
          fetch-depth: 0
```
I am getting error as below.

https://aws1.discourse-cdn.com/github/original/3X/e/5/e55d1616caac5024c6e83565879e03d2f6f6b9bc.png
