### ISSUE TITLE
Feature request: Allow to configure the git clean parameters

### ISSUE THREAD

**Issue by 0x53A** [actions/checkout#823]
We are using self-hosted runners and would like to persist certain cache directories between runs.
It would be really useful if the ``clean`` parameter could be extended from a bool to a string.

For example, [in gitlab I can set](https://docs.gitlab.com/ee/ci/large_repositories/#git-clean-flags)

```
variables:
    GIT_CLEAN_FLAGS: "-ffdx -e DirectoryIWouldLikeToKeep"
```

This _should_ even be backwards compatible by first checking if ``clean`` is either ``true`` or ``false``.

**Comment by EluvK** [comment]
Encountered the same problem, the compromise I used was to run `git clean` manually.

``` YAML 
- name: Checkout repository
  uses: actions/checkout@v3
  with:
    clean: false

- name: Run Git Clean
  run: git clean -ffdx -e cache_directory/
```
Still need this feature to make it more elegant.
