### ISSUE TITLE
Using checkout within a Docker container

### ISSUE THREAD

**Issue by hannesa2** [actions/checkout#841]
Hi, I use actions/checkout with a Docker image

```
jobs:
  dockerRun:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [ 'focal' ]
    container: hannesa2/abc-${{ matrix.ubuntu }}-4:pr-1
    steps:
      - name: investigate
        run: |
          pwd
          whoami
          ls -la
          id -u
      - name: Checkout
        uses: actions/checkout@v2
```
and run into
<img width="765" alt="image" src="https://user-images.githubusercontent.com/3314607/176723694-4707625c-bbb7-4a87-a9c1-aae9620d190c.png">

Does someone has an idea how to solve this user permission issue ?

**Comment by hannesa2** [comment]
To show issue, I transferred to public repo https://github.com/hannesa2/alexa-auto-sdk-public/pull/3

**Comment by SeyoungLeeImprobable** [comment]
Try

```yaml
container:
  image: <image>
  options: --user root
```

**Comment by yoramdelangen** [comment]
> ```yaml
> --user root
> ```

This worked for me, for now

**Comment by hannesa2** [comment]
Thank you ! With your help it's works now.

**Comment by raythurnvoid** [comment]
Running in v4

`--user root` is not enough, actually I think it's useless since it's the default value (not sure).

I have to set the trusted path manually in the container (We use the playwright container to run e2e tests)

```
  e2e:
    runs-on: ubuntu-latest-4-cores
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble

    steps:
      - name: Install git-lfs
        run: |
          apt-get update && apt-get install -y git-lfs
          git lfs update --force || true

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          lfs: true
          submodules: true

      # Required to run git commands in the container
      - name: Configure git
        run: git config --global --add safe.directory "$(pwd)"

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
```
