### ISSUE TITLE
Retrieving the default branch name, Not Found

### ISSUE THREAD

**Issue by Goooler** [actions/checkout#845]
Checkout another private repo but failed, my config here:
```yml
jobs:
  checkout-private-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'Goooler/LearningNote'
          path: './LearningNote'
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
```
log here: 
```
Run actions/checkout@v3
Syncing repository: Goooler/LearningNote
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/1099e687-7685-4c00-817f-a176165b93cc' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/DemoApp/DemoApp/LearningNote
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Determining the default branch
  Retrieving the default branch name
  Not Found
  Waiting 11 seconds before trying again
  Retrieving the default branch name
  Not Found
  Waiting 11 seconds before trying again
  Retrieving the default branch name
  Error: Not Found
```

Link #347, and you can repro this issue in https://github.com/Goooler/DemoApp/pull/153
