### ISSUE TITLE
Checked out directory is always deleted when `path:` is used

### ISSUE THREAD

**Issue by JLHasson** [actions/checkout#847]
I am checking out my repo using
```
    - name: Check out source repository
      uses: actions/checkout@v2
      with:
        path: some-relative-path
```

During a workflow run `${GITHUB_WORKSPACE}/some-relative-path` exists & is checked out successfully. However, upon completion of the run this path is deleted & no longer exists. I followed the suggestion in #430 but I believe this is in reference to the cleanup _before_ running the workflow. I am mostly interested in keeping the working directory around _after_ the workflow has completed. 

As far as I can tell without the `path:` command the working dir is kept around, it's unclear to my why it would be removed when `path:` is used, or how to disable this behavior.
