### ISSUE TITLE
Repository not found - Checkout specific repo

### ISSUE THREAD

**Issue by klepiz** [actions/checkout#853]
Im trying to checkout multiple repos in a same job, one of them if where Im running the job and the second one is an internal repo. 
```
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -  uses: actions/checkout@v2 
        with:
          ref: ${{ secrets.GITHUB_REF }}
          repository: my-org/my-repo
          path: my-repo
          fetch-depth: 0
```
The error that I got: 
```
 remote: Repository not found.
  Error: fatal: repository 'https://github.com/my-org/my-repo/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/testing-workflows*:refs/remotes/origin/testing-workflows* +refs/tags/testing-workflows*:refs/tags/testing-workflows*
  remote: Repository not found.
```
