### ISSUE TITLE
 Changes made to repository are not available to other workflows being called

### ISSUE THREAD

**Issue by vvkjndl** [actions/checkout#857]
Here's the scenario:

I have a file called `release.version` in the repository:

I have a workflow that calls two workflows using `uses:`.

```
name: my workflow

on:
  workflow_dispatch:

jobs:
  workflowA:
    uses: ./.github/workflows/workflowA.yaml
    secrets: inherit

  workflowB:
    needs: [ workflowA ]
    uses: ./.github/workflows/workflowB.yaml
    secrets: inherit
```

`workflowA` has made a change in the file `release.version`.

This change is not available to the `workflowB`. `workflowB` always sees the last version of the file when being called within.

Am I missing something? I am using `actions/checkout@v2` in both of the workflows.
