### ISSUE TITLE
It seems that the most recent git timestamp is always the current time

### ISSUE THREAD

**Issue by Shimada666** [actions/checkout#899]
Hi! My project needs to use git timestamps, but I noticed that using the command "git log -1 --format=%at filepath" in a github action always gives the current timestamp. But it seemed to be working fine a few months ago.

```yml
name: test

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git log -1 --format=%at setup.py
```

Then I get this.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/33391300/185796511-37ddaa74-f97c-412b-bb93-15ca3a93c7d8.png">

It's current timestamp.

How can I get a correct git timestamp?
