### ISSUE TITLE
checkout action produces corrupted clone. 

### ISSUE THREAD

**Issue by finolacahill** [actions/checkout#903]
I've been trying to debug a mystery pytest fail that only occurs during CI (not when reproduced locally)

We have finally narrowed this down to the checkout step itself. For reference this is the current workflow:

```
 name: /<name/>
on:
  workflow_dispatch:
  pull_request:
  workflow_call: 

env:
  CONDA: /opt/anaconda3

jobs:
  misc-sanity-tests:
    runs-on: self-hosted
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: run-on-checkout
        run: |
              source $CONDA/bin/activate $RUNNER_NAME
              pytest tests/misc -v

      - name: run-on-clone
        if: always()
        run: |
              git clone git@github.com:/<repo-address/>
              cd /<repo-name/>
              git checkout <current-branch-name>
              git submodule update --init --recursive
              source $CONDA/bin/activate $RUNNER_NAME
              pytest tests/misc -v
```

The 'run-on-clone' step always passes  for all tests and the run-on-checkout step always fails at a particular test. 
![image](https://user-images.githubusercontent.com/45110160/186137199-e919da01-0f9b-4505-84f1-39b2949a1cc7.png)

![image](https://user-images.githubusercontent.com/45110160/186137261-6c1693ea-8c18-4e8e-a8e3-386fff711a14.png)

if I cd into the clone created by the checkout script I can reproduce (even if i move it to a different location). Normally cloned repos do not have this issue
The diff reveals that the binary files of the submodules are different between a recursive 'normal' clone and a git checkout with recurse submodules. I can't figure out why. I will not attach logs here as it includes proprietary information but they can be provided  via email if necessary.
