### ISSUE TITLE
can't get current branch in V3

### ISSUE THREAD

**Issue by zxcvbnm3057** [actions/checkout#911]
In `actions/checkout@v1` we can get current branch by `$(git branch -r --contains ${{ github.ref }})`, but in V3 this will return `''`. Is there a alternative to do this?

**Comment by zxcvbnm3057** [comment]
Got it. V3 won't fetch more git history commit than 1 by default. Set `fetch-depth: 0` solved this issue.

But still wonder why this issue will reappear even the github.ref is the last commit of the branch?

Here is code with problem
```
name: test
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo $raw
          echo $branch
          echo "BRANCH=$branch" >> $GITHUB_ENV
      - if: ${{ env.BRANCH == 'main' }}
        run: echo ${{ env.BRANCH }}
```

and right code

```
name: test
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
+       with:
+       fetch-depth: 0
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo $raw
          echo $branch
          echo "BRANCH=$branch" >> $GITHUB_ENV
      - if: ${{ env.BRANCH == 'main' }}
        run: echo ${{ env.BRANCH }}
```
