### ISSUE TITLE
The ssh-key mode will be failed in checking out code from AWS EC2 with Agents started by SSM

### ISSUE THREAD

**Issue by charlie-fox** [actions/checkout#917]
Hi Team,

I found an issue when we try to checkout code with SSH key in Github actions and AWS Windows EC2 as Runner ( the Actions Agent is started from SSM).

The checkout process responded us :
--------------
  C:\Windows\system32\icacls.exe C:\actions-runner\_work\_temp\bce01f23-14da-4a3f-bd52-5e95cc5f0517 /grant:r WORKGROUP\EC2AMAZ-XXXXX$:F
  WORKGROUP\EC2AMAZ-XXXXX$: No mapping between account names and security IDs was done.
  Successfully processed 0 files; Failed processing 1 files
Removing auth
Error: The process 'C:\Windows\system32\icacls.exe' failed with exit code 1332
-----------

it is very strange, because in Linux EC2 and normal windows runner without SSM (user normal windows GUI login), no such issues.

check the github Action process, found in Windows checkout, it has a special activity to grant permission: 

[https://github.com/actions/checkout/blob/2541b1294d2704b0964813337f33b291d3f8596b/src/git-auth-helper.ts#L221 ](https://github.com/actions/checkout/blob/2541b1294d2704b0964813337f33b291d3f8596b/src/git-auth-helper.ts#L221)

It will use "USERNAME" and "USERDOMAIN" to locate current user and grant permission.

Check normal windows login shell (from Gui) and , the env list is :
--------
USERDOMAIN                     EC2AMAZ-KNUHKAN
USERNAME                       Administrator
----------
They are correct.

But if you try to get such list from SSM shell :
it would be :
-----------
USERDOMAIN                     WORKGROUP
USERNAME                       EC2AMAZ-XXXXXX$
-----------

in SSM run-command mode (we create runner automatically by AWS SSM run command, with ephemeral way) , the USERNAME should be "system" ,  but even I overwrite the USERNAME with `system`, it would still failed.  because  looks the system is a special username, it can be only work-around by overwriting the USERDOMAIN to blank, and overwrite the username to system.

since AWS windows EC2 is widely used and more and more users are building autoscaled runner with automatic way like SSM, hope it can be resolved.
Thanks.

**Comment by robpomeroy** [comment]
I've had what looks like an identical problem with a self-hosted Windows Server 2022 runner:

```
  C:\Windows\system32\icacls.exe C:\actions-runner\_work\_temp\f637cea8-35b0-4dd3-b600-3d83bdbb9ac8 /grant:r DR\GH-RUNNER-WIN-1$:F
  DR\GH-RUNNER-WIN-1$: Successfully processed 0 files; Failed processing 1 files
  No mapping between account names and security IDs was done.
  Error: The process 'C:\Windows\system32\icacls.exe' failed with exit code 1332
```

It occurred to me that the GitHub Actions service is installed as the "NETWORK SERVICE" user. My fix is to use the following overrides for `USERNAME` and `USERDOMAIN` (which I discovered through this issue raised by @charlie-fox):

```yaml
      - name: Checkout the branch (remote)
        uses: actions/checkout@v3
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          USERDOMAIN: "NT AUTHORITY"
          USERNAME: "NetworkService"
        if: env.SSH_KEY
        with:
          repository: MyOrg/MyRepo
          ref: ${{ github.ref_name }}
          ssh-key: ${{ env.SSH_KEY }}
```

Context: this workflow is being called from a workflow in another repo. Not sure if that has a bearing on this issue. Secrets are set to `inherited` in the calling workflow. The `if` test is here because this workflow may also be called locally, in which case a different step performs the checkout without the SSH key.
