### ISSUE TITLE
Device is not a TTY error

### ISSUE THREAD

**Issue by DonRichards** [actions/checkout#935]
Error message during build "the input device is not a TTY"

I can build locally without any issues but the build fails when running a makefile that fires a docker-compose command (I think). 

The step where the error pops up is at the "**Build Static**" step.
### CI.yml
```yml
name: CI
on:
  push:
    branches:
      - main
      - development
    tags:
      - v*
  pull_request:
    branches:
      - main
      - development
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        outputs:
          matrix: ${{ steps.excludes-matrix.outputs.matrix }}
        steps:
            # Check out current commit
            - name: Checkout
              uses: actions/checkout@v3

            # Make sure buildkit is enabled
            - name: Enable buildkit
              shell: bash
              run: |
                  echo '{"experimental": "enabled"}' > ~/.docker/config.json

            # Build and run the static environment
            - name: Build Static
              run: make static-docker-compose.yml up

            # Run the updatedb command.
            - name: Run Update Hooks
            ...
```
### MAKEFILE
```makefile
# Creates solr-cores according to the environment variables.
.PHONY: solr-cores
.SILENT: solr-cores
solr-cores:
	@echo ""
	@echo "Creating solr-cores for $(COMPOSE_PROJECT_NAME)"
	if [ ! "$(shell docker ps -a --format \"{{.Names}}\" --filter 'status=running' | grep solr)" ]; then \
		echo "  └─ Solr is not running. Attempting to restart it now." ; \
		docker-compose restart solr ; \
	fi
	@echo "  └─ Checking for Drupal"
	if [ ! "$(shell docker ps -a --format \"{{.Names}}\" --filter 'status=running' | grep drupal)" ]; then \
		echo "    └─ Drupal is not running. Attempting to restart it now."; \
		docker-compose restart drupal ; \
		${MAKE} _docker-up-and-wait ; \
	fi
	docker-compose exec -T drupal with-contenv bash -lc "for_all_sites create_solr_core_with_default_config"
	@echo "  └─ Done"
```
### Console output
![Screenshot-46](https://user-images.githubusercontent.com/2738244/193113118-9f1cde79-554d-4e9b-8baf-f619267a2dd4.png)

I noticed there is a possibly related topic of discussion [here (Github Community Discussion)](https://github.com/orgs/community/discussions/31737)
And [Docker compose](https://github.com/docker/compose/issues/7306) has some old info on previous releases with this error. 

Not sure how related they might be but I thought it might give some more context to this.
