### ISSUE TITLE
Cache restore dont restore the bins correctly

### ISSUE THREAD

**Issue by cgarnier** [actions/checkout#977]
When npm the cache is restored with 
```yaml
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
```
It doesn't restore the links, alias or whatever it is on the bins.
To replicate, you can use `eslint` package that include a bin.

package.json
```json
{
  "scripts": { "lint": "eslint ."}
}
```

workflow:
```yaml
name: Tests
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
```
If you run 2 time this job, it will fail the seconde time.
