### ISSUE TITLE
[Documentation] Update actions documentation to note that secondary checkouts will wipe the first checkout

### ISSUE THREAD

**Issue by unlikelyzero** [actions/checkout#978]
I spent a considerable amount of hours trying to track down a networking bug which turned out to be just an oddity with the current github actions/checkout multi-repo documentation.

This preserves both environments: the parent project which sources the GHA and the secondary repo
```yaml
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
     - uses: actions/checkout@v3
        with:
          repository: unlikelyzero/quickstart
          ref: fix-network
          path: 'quickstart'
```

This will wipe the first at the instance that actions/checkout is run -- including any running services in that workspace.
```yaml
      - uses: actions/checkout@v3
        with:
          repository: unlikelyzero/quickstart
          ref: fix-network
          path: 'quickstart'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
```

I think the multi-repo readme should be updated with language to prevent headaches and heartburn.
