### ISSUE TITLE
Failing to checkout private repo

### ISSUE THREAD

**Issue by steve-fraser** [actions/checkout#983]
github action seemly failing to checkout private repo. I have no idea what's going on.

```
name: push-artifact

on:
  pull_request:
    branches:
      - 'main'

permissions:
  packages: write # needed for ghcr.io access


jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
```

```
Run actions/checkout@v3
Syncing repository: weaveworks/weave-gitops-enterprise-tf-aws-provider
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/41c28f00-ec41-4f81-96a1-d367bdc5461e' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/weave-gitops-enterprise-tf-aws-provider/weave-gitops-enterprise-tf-aws-provider
Deleting the contents of '/home/runner/work/weave-gitops-enterprise-tf-aws-provider/weave-gitops-enterprise-tf-aws-provider'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/weaveworks/weave-gitops-enterprise-tf-aws-provider/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 11 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/weaveworks/weave-gitops-enterprise-tf-aws-provider/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting [16](https://github.com/weaveworks/weave-gitops-enterprise-tf-aws-provider/actions/runs/3314729540/jobs/5474385802#step:2:17) seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/weaveworks/weave-gitops-enterprise-tf-aws-provider/' not found
  Error: The process '/usr/bin/git' failed with exit code 128
```
