### ISSUE TITLE
Master/v2 no longer creates a folder for the specified repository.

### ISSUE THREAD

**Issue by dlemstra** [actions/checkout#99]
We are using `@master` of `actions/checkout` and with the help of the `repository: ImageMagick/ImageMagick-Windows` we checkout another repository. This used to create a folder called `ImageMagick-Windows` into our `%GITHUB_WORKSPACE%` folder. But due to the changes for `v2` it now clones the repository into the folder `%GITHUB_WORKSPACE%` without creating a sub directory. Is this by design or should this be fixed? Switching back to `@v1` resolved this issue.

**Comment by ericsciple** [comment]
The `path` input is now always relative to `github.workspace`. So if you desire a side-by-side layout then you could do something like:

```
- uses: actions/checkout@v2-beta
  with:
    path: my-repo
- uses: actions/checkout@v2-beta
  with:
    repository: my-org/my-tools
    path: my-tools
```

i'll update the README to include the scenario.

note, the motivation for the layout changes was:
- Simplify rules wrt how the path input worked. Before it was different depending on whether the worfklow-repo was being checked out
- Improve support for container scenarios. Since github.workspace gets mapped in, the other repos werent accessible within the container.
- The github workspace folder moved to follow wherever the workflow-repo, this is another concept we wanted to remove for simplicity. This also means that the workflow-repo couldnt be checked-out twice side by side, which some users wanted to do

**Comment by ericsciple** [comment]
Also, if you desire nested layout then that would be like:

```
- uses: actions/checkout@v2-beta
- uses: actions/checkout@v2-beta
  with:
    repository: my-org/my-tools
    path: my-tools
```
